\restoregeometry
%---------------------------------------------------------------------------------------------------
\chapter[Análisis de la información financiera y contable con sus tendencias]{Análisis de la
información financiera y contable con sus tendencias}
\label{chp_infofinan}

Tomando en consideración los Estados Financieros del Fondo del Seguro Social Campesino con corte al 31 de diciembre de cada año, para el período 2010-2020, se procede con el siguiente análisis financiero contable, en el que se analizará los principales componentes del Balance General. 

Cabe mencionar que los balances del IESS en el período 2010-2020 han sufrido cambios en los códigos y creación de cuentas, signo negativo para la representación del pasivo, patrimonio e ingresos; por tanto, los balances financieros no son auto consistentes y comparables. Sin embargo por razones técnicas y de análisis se estandarizó la data con números absolutos para todo el capítulo.

\section{Activos}

A continuación, en la tabla \ref{tab:iess_activos_hist_ssc} y figura \ref{fig:iess_activos_hist_ssc}, se presenta la evolución del activo contable del Fondo del Seguro Social Campesino (SSC) para el período 2010-2020.

\begin{table}[H]
 \begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{Evolución del Activo del Fondo de SSC a 31 de diciembre de cada año}
  \label{tab:iess_activos_hist_ssc}
  {\fontsize{10}{12}\selectfont
  
  \begin{tabular}{R{1.0cm}!{\color{white}\vrule}
                  R{3.0cm}!{\color{white}\vrule}
                  R{3.0cm}!{\color{white}\vrule}
                  R{3.0cm}!{\color{white}\vrule}}
                  % R{2.5cm}}
  \toprule \rowcolor{iess_green!60}
    \parbox{1.0cm}{\centering Año}
    &\parbox{3.0cm}{\centering Activo (USD)}
    & Variación anual (USD)
    & Tasa de Variación (\%)\\
    
    \midrule
     \input{tablas/iess_activos_hist_ssc.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución del Activo del Fondo de SSC a 31 de diciembre de cada año\\ (En millones de dólares)}
\label{fig:iess_activos_hist_ssc}
\includegraphics[scale=0.7]{graficos/iess_activos_hist_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado}: DAIE.}
\end{figure}

En la evolución histórica del Activo del Fondo del SSC, se observa que los activos correspondientes al período 2010- 2020 mantuvieron una tasa de crecimiento de 224,95\%, pasando de USD 559,49 millones a USD 1.818,06 millones; es decir, se incrementó promedio (geométrico) anual en 12,51\%. 

El mayor incremento se efectuó en el año 2017 con el 21,50\%, es decir una diferencia de USD 226,61 millones respecto al año anterior; esto debido al incremento de los aportes. A partir del 2017 hasta el 2020 el Seguro Social Campesino mantiene un crecimiento desacelerado, llegando al 2020 con una tasa de crecimiento de 11,88\%. El único año con una variación negativa fue el 2014, mismo que disminuyó con respecto al año anterior en -3,35\% debido a la desinversión de fondos para pago de prestadores internos por valores de salud.

\girarpagina

\subsection{Análisis vertical y horizontal del componente del Activo}

En la tabla \ref{tab:iess_activos_variacion_ssc1}, se presenta los componentes del activo del Fondo del Seguro Social Campesino por el período 2010-2020. 

\begin{table}[H]
 \begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\fontsize{10}{12}\selectfont
   \caption{Análisis de los componentes del Activo del Fondo del Seguro Social Campesino al 31 de diciembre de cada año}
  \label{tab:iess_activos_variacion_ssc1}
 \scalebox{1} {
  \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multicolumn{2}{c}{Descripción de las cuentas} & 2010 & 2011& 2012& 2013& 2014& 2015\\

    \midrule
      \input {tablas/iess_activos_variacion_ssc1.tex}
    \bottomrule
  \end{tabular}
  }
 
  \endgroup
\end{table}
\begin{table}[H]
 \begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\fontsize{10}{12}\selectfont
  \label{tab:iess_activos_variacion_ssc2}
 %\scalebox{1} {
  \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multicolumn{2}{c}{Descripción de las cuentas} & 2016 & 2017 & 2018 & 2019 & 2020\\

    \midrule
      \input{tablas/iess_activos_variacion_ssc2.tex}
    \bottomrule
  \end{tabular}
  %}
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados – DNGF \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}

{\scriptsize
\textbf{Nota Metodológica:}
Los balances del IESS en el período comprendido 2010 al 2020 han sufrido cambios en los códigos de cuentas, creación de nuevas cuentas, por tanto a continuación se presenta la variación y optimización. Un ejemplo de ello se evidencia en los componentes del activo, donde algunas cuentas fueron afectadas como las siguientes:

\begin{itemize}
\item	En la cuenta “Inversiones” a partir del 2010 al 2012 en los balances se las denomina como: “Inversiones deuda renta fija sector privado” (7110) e “Inversiones deuda renta fija Sector Público” (7120); a partir del 2013 al 2014 es optimizada en una sola cuenta registrada en el plan de cuentas como “Inversiones” (12). Finalmente a partir del 2015 al 2020 cambia su denominación a “Recursos/Administra por El BIESS” (714).  

\item	La cuenta “Deuda del Gobierno” en el plan de cuentas del 2010 al 2012 se la reconoce como cuenta principal del activo; sin embargo a partir del 2013 al 2020 dicha cuenta pasa a ser una subcuenta de “Cuentas por Cobrar”, es por ello que en la tabla \ref{tab:iess_activos_variacion_ssc1} no registra valores desde el 2013.

\end{itemize}
}

\regresargirar
A continuación se desarrolla el análisis vertical de los componentes del Activo, dentro de los cuales se encuentran las siguientes subcuentas “Fondos Disponibles”, “Inversiones”, “Cuentas por Cobrar”, “Propiedad Planta y Equipo”, “Deuda de Gobierno”, “Intereses por Cobrar”, “Otros Activos”, “Inventarios”, “Activos Intangibles” y “Activos clasificados”.

La cuenta con mayor representatividad en el período analizado es inversiones denominada en los últimos años como “Recursos/Administra x el BIESS”, la cual representa en promedio el 62,54\% del total de los activos. En segundo lugar se encuentra “Cuentas por Cobrar” con el 25,01\% en promedio, en tercer lugar de representatividad  lo ocupa la cuenta “Deuda de Gobierno” con el 22,10\% en promedio hasta el año 2012, debido que la misma pasó a formar en el 2013 una subcuenta de cuentas por cobrar. Finalmente, el cuarto lugar del total de los activos se lleva la cuenta “Propiedad, Planta y Equipo” con el 4,11\%.

%

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Porcentaje promedio de representatividad de los componentes del Activo correspondiente al período 2010 – 2020}
\label{fig:iess_porcentaje_promedio_representatividad_ssc}
\includegraphics[scale=0.9]{graficos/iess_porcentaje_promedio_representatividad_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF.\\ \textbf{Elaborado:} DAIE.}
\end{figure}

En la tabla \ref{tab:iess_activos_del_fondo_ssc}, se presenta el análisis horizontal de los componentes del Activo del Fondo del Seguro Social Campesino correspondiente al período 2010-2020.


\girarpagina
\begin{table}[H]
 \begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\fontsize{10}{12}\selectfont
   \caption{Análisis horizontal del Activo del Fondo del Seguro Social Campesino al 31 de diciembre de cada año (\%)}
  \label{tab:iess_activos_del_fondo_ssc}
 \scalebox{1} {
  \begin{tabular}{r!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}
                  R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multirow{1}[0]{*}{Descripción de las cuentas}& 2011& 2012 & 2013 & 2014 & 2015 & 2016& 2017& 2018& 2019& 2020\\

    \midrule
      \input{tablas/iess_activos_del_fondo_ssc.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}

{\scriptsize \textbf{Nota Metodológica}
\begin{itemize}
\item	En el año 2011 se evidencia el mayor incremento del Activo con una tasa de 22,83\%, debido al aumento de las subcuentas “Cuentas por Cobrar” (123,15\%) y “Deuda de Gobierno” (54,90\%). En el año 2014 se evidencia el decrecimiento más significativo del pasivo en -3,35\%, debido a la disminución de las inversiones e USD. 56,17 millones respecto al año anterior.

\end{itemize} }


El crecimiento del Activo mantiene una variación positiva en el período analizado, con excepción del año 2014. El año con la tasa de crecimiento más significativa fue el 2011 con el 22,83\%, pasando de USD 559,48 millones en el 2011 a USD 687,21 millones en el 2012; cabe mencionar que el único año con variación negativa se evidencia en el año 2014 con -3,35\%.

Dentro de las subcuentas del componentes del Activo se evidencia el mayor incremento en el año 2013 en “Cuenta por Cobrar” con una tasa de 567,13\%, debido que se incluye como subcuenta la deuda de gobierno. La tasa de decrecimiento más significativa del período se evidenció en la subcuenta “Fondos Disponibles” en el mismo año con el -92,41\%, pasando de USD. 8,59 millones a USD. 652.220,07 respecto al año anterior.

\regresargirar



\subsection{Cuentas por cobrar}

A continuación, se presenta la evolución de las cuentas por cobrar del Fondo del Seguro Social Campesino correspondiente al período 2010 – 2020.

\begin{table}[H]
 \begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{\small {Evolución de Cuentas por cobrar del Fondo de Seguro Social Campesino al 31 de diciembre de cada año}}
  \label{tab:iess_variacion_cuentas_por_cobrar_ssc}
  {\fontsize{10}{12}\selectfont

  \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}R{2.5cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multirow{2}[0]{*}{Año} & Cuentas por cobrar & Incremento anual & Tasa de variación (\%)\\

    \midrule
     \input{tablas/iess_variacion_cuentas_por_cobrar_ssc.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize \textbf{Fuente:}: Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución de Cuentas por Cobrar del Fondo de Seguro Social Campesino al 31 de diciembre de cada año (en millones de dólares)}
\label{fig:iess_variacion_cuentas_por_cobrar_ssc}
\includegraphics[scale=0.8]{graficos/iess_variacion_cuentas_por_cobrar_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE.}
\end{figure}

\vspace{-0.5cm}
Las cuentas por cobrar en el período 2010 al 2020 mantuvo un incremento del 343,38\%, es decir en promedio creció USD 48,69 millones, con una tasa de crecimiento anual promedio (geométrico) de 16,06\%. El incremento más significativo se observa en el año 2015 con una variación positiva de 85,54\%, debido al incremento en las subcuentas “Anticipo Contratistas” en 169,34\% y “Cuentas por cobrar varias” en 289,90\%.

El año 2012 presentó la tasa de decrecimiento más significativa del período con -32,88\%, es decir decreció en USD 75,75 millones respecto al año anterior; la disminución se verifica en la subcuenta “Deuda de Gobierno” misma que paso de USD 195,32 millones (2011) a USD 126,93 millones (2012).

Finalmente, al año 2020 las cuentas por cobrar disminuyeron en -2,88\% respecto al año anterior, pasando de USD 647,40 millones a USD 628,77 millones.

\section {Pasivos}
A continuación, se presenta la evolución de la cuenta Pasivo del Fondo del Seguro Social Campesino correspondiente al período 2010 – 2020.

\begin{table}[H]
 \begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{Evolución del pasivo del Fondo del Seguro de Social Campesino al 31 de diciembre de cada año}
  \label{tab:iess_pasivos_hist_ssc}
  {\fontsize{10}{12}\selectfont

  \begin{tabular}{R{1.0cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}}
                  % R{2.5cm}}
  \toprule \rowcolor{iess_green!60}
    \parbox{1.0cm}{\vspace{0.35cm}\centering Año}
    &\parbox{2.5cm}{\vspace{0.35cm}\centering Pasivo (USD)}
    & Variación anual (USD)
    & Tasa de Variación (\%)\\

    \midrule
     \input{tablas/iess_pasivos_hist_ssc.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}
\vspace{-.6cm} 

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución del Pasivo del Fondo del Seguro de Social Campesino al 31 de diciembre de cada año}
\label{fig:iess_pasivos_hist_ssc}
\includegraphics[scale=0.7]{graficos/iess_pasivos_hist_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE.}
\end{figure}

La cuenta pasivos en el período 2010 al 2020 refleja una tasa de decrecimiento de  -30,35\%, en promedio dicha cuenta disminuyó en USD 863.754,19; es decir, decreció en promedio (geométrico) anual en el -3.55\%.

El Pasivo en su mayoría ha mantenido variaciones negativas en el periodo analizado, con excepción de los años 2011, 2012, 2015 y 2020. La tasa de crecimiento más significativa se evidencia en el año 2011 con el 76,80\%, representando un incremento USD 45,90 millones respecto al año anterior.

Mientras que el decrecimiento más representativo se efectuó en el año 2018 con una variación negativa de -48,15\%, pasando de USD 71,61 millones (2017) a USD 37,13 millones (2018); es decir, el pasivo bajó en 34,48 millones. Finalmente en el año 2020 la cuenta crecer 33,09\% respecto al 2019 debido al incremento de las subcuentas “Proveedores” y “Prestadores Médicos por Pagar”.

\girarpagina

\subsection{Análisis vertical y horizontal del componente del Pasivo}

En la tabla \ref{tab:iess_pasivos_variacion_ssc1} se presenta los componentes del pasivo del Fondo del Seguro Social Campesino por el período 2010 al 2020.

\begin{table}[H]
 \begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
   \caption{Análisis de los componentes del Pasivo del Fondo del Seguro Social Campesino al 31 de diciembre de cada año}
  \label{tab:iess_pasivos_variacion_ssc1}
 %\scalebox{1} {
\fontsize{10}{12}\selectfont
\begin{tabular}{r!{\color{white}\vrule}R{2.5cm}r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multicolumn{2}{c}{Descripción de las cuentas} & 2010 & 2011 & 2012 & 2013 & 2014 & 2015\\
    \midrule
      \input{tablas/iess_pasivos_variacion_ssc1.tex}
    \bottomrule
  \end{tabular}
  %}

  \endgroup
\end{table}

\begin{table}[H]
 \begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
  \label{tab:iess_pasivos_variacion_ssc2}
 %\scalebox{1} {
 \fontsize{10}{12}\selectfont
  \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multicolumn{2}{c}{Descripción de las cuentas} & 2016 & 2017 & 2018 & 2019 & 2020\\

    \midrule
      \input{tablas/iess_pasivos_variacion_ssc2.tex}
    \bottomrule
  \end{tabular}
 % }
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados – DNGF \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}


{\scriptsize\textbf{Nota Metodológica:}

Los balances del IESS en el período comprendido del 2010 al 2020 han sufrido cambios en los códigos de cuentas, creación de nuevas cuentas, por tanto a continuación se presenta la variación y optimización. Un ejemplo de ello se evidencia en los componentes del pasivo, donde algunas cuentas fueron afectadas como las siguientes:
\begin{itemize}
\item	El pasivo refleja dos escenarios dentro de su plan de cuentas, el primero de ellos entre los años 2010 al 2014 mismos que están conformados por cinco subcuentas como son: prestaciones y beneficios, cuentas por pagar, pasivo diferido, deuda de gobierno contra. Mientras que entre el periodo 2015 al 2020 las subcuentas antes mencionadas se consolidan en dos como son: pasivos corrientes y pasivos no corrientes.
\end{itemize} }

A continuación se desarrolla el análisis vertical de los componentes del Pasivo, dentro de los cuales se encuentran las siguientes subcuentas “Prestaciones y Beneficios”, “Cuentas por Pagar”, “Pasivo Diferido”, “Deuda de Gobierno Contra”, “Provisiones”, “Pasivos Corrientes” y “Pasivos No Corrientes”.
 \regresargirar

En el primer escenario (2010-2014) la cuenta con mayor representatividad del pasivo corresponde a “Cuentas por Pagar” con el 61,83\% en promedio, mientras que en el segundo escenario (2015-2020) la mayor representatividad promedio se enfoca en la subcuenta “Pasivos Corrientes” con el 66,58\%, considerando que a partir del año 2015 cuentas por pagar se consolida en pasivos corrientes.

En el periodo 2010 al 2014 el segundo lugar lo ocupa “Deuda de Gobierno Contra” con un porcentaje promedio de representatividad de 33,24\%; mientras que desde el 2015 al 2020 la subcuenta “Pasivos no Corrientes” representa el 33,24\% en promedio. Finalmente el tercer lugar dentro del pasivo lo ocupa la cuenta “Provisiones” para los años 2013 y 2014 con el porcentaje de representatividad promedio de 33,10\%.
%%%%%%%%%
\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Porcentaje promedio de representatividad de los componentes del pasivo correspondiente al período 2010 – 2020}
\label{fig:iess_porcentaje_promedio_pasivos_representatividad_ssc}
\includegraphics[scale=0.8]{graficos/iess_porcentaje_promedio_pasivos_representatividad_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF.\\ \textbf{Elaborado:} DAIE.}
\end{figure}


\girarpagina

En la tabla \ref{tab:iess_pasivos_del_fondo_ssc} , se presenta el análisis horizontal de los componentes del pasivo del Fondo del Seguro Social Campesino correspondiente al período 2011-2020.

\begin{table}[H]
 \begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
   \caption{Análisis horizontal del Pasivo del Fondo del Seguro Social Campesino \\ al 31 de diciembre de cada año (\%)}
  \label{tab:iess_pasivos_del_fondo_ssc}
% \scalebox{1} {
\fontsize{10}{12}\selectfont
\begin{tabular}{r!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}
                  R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multirow{1}[0]{*}{Descripción de las cuentas}& 2011& 2012 & 2013 & 2014 & 2015 & 2016 & 2017& 2018 & 2019 & 2020\\

    \midrule
      \input{tablas/iess_pasivos_del_fondo_ssc.tex}
    \bottomrule
  \end{tabular}
 % }
  \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}

{\scriptsize \textbf{Nota Metodológica:}

\begin{itemize}
\item 	En el año 2011 se evidencia el mayor incremento del Pasivo con una tasa del 76,80\%, debido al incremento de las “Cuentas por Pagar” en 110,99\%. En el año 2018 se evidencia el decrecimiento más significativo del pasivo en -48,15\%, debido a los depósitos no identificados los cuales decrecieron en -75,51\% respecto al año anterior.
\end{itemize} }
Dentro de las subcuentas del componente del Pasivo se evidencia el mayor incremento en el año 2012 en “Prestaciones y Beneficios” con una tasa de 425,46\%, debido a la subcuenta “Obligaciones pendientes de pago” marcando una diferencia de USD 17,13 millones. Mientras que la variación negativa más significativa del período se evidenció en la subcuenta “Pasivos no Corrientes” en el 2018 con -75,51\%, pasando de USD 44,58 millones a USD 10,92 millones, esto debido a la subcuenta “Depósitos no Identificados”.

\regresargirar
%
\subsection{Cuentas por pagar}

A continuación, se presenta la evolución de las cuentas por pagar del Fondo del Seguro Social Campesino por el período comprendido entre el 2010 al 2020.

\begin{table}[H]
 \begingroup\scriptsize\centering
 \captionsetup{justification=centering}
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
    \caption{\small {Evolución de las Cuentas por pagar del Fondo del Seguro Social Campesino al 31 de diciembre de cada año.}}
  \label{tab:iess_variacion_cuentas_por_pagar_ssc}
  {\fontsize{10}{12}\selectfont

  \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}R{2.5cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multirow{2}[0]{*}{Año} & Cuentas por pagar & Variación anual & Tasa de Variación (\%)\\

    \midrule
     \input{tablas/iess_variacion_cuentas_por_pagar_ssc.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución de las Cuentas por pagar del Fondo del Seguro Social Campesino al 31 de diciembre de cada año.}
\label{fig:iess_variacion_cuentas_por_pagar_ssc}
\includegraphics[scale=0.8]{graficos/iess_variacion_cuentas_por_pagar_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE.}
\end{figure}



Las cuentas por pagar en el período 2010 al 2020, mantienen una tasa decrecimiento de 21,16\%, es decir que en promedio dicha cuenta creció en USD 717.875,77; lo que anualmente el promedio (geométrico) creció al 1,94\%. El incremento más significativo se evidencia en el año 2015 pasando de USD. 42,76 millones a USD 101,35 millones.

Mientras que el decrecimiento más representativo se efectuó en el año 2018 con una variación negativa de -48,39\%, pasando de USD 71,25 millones (2017) a USD 36,77 millones (2018), es decir las cuentas por pagar disminuyeron USD 34,47 millones. Finalmente en el año 2020 la cuenta tiene un repunte de 33,50\% respecto al 2019, representando un crecimiento de USD 10,31 millones.

\subsubsection{Porcentaje de cumplimiento de la deuda de Gobierno}
A continuación se analiza la Deuda de Gobierno comprendida en el período 2012-2020, correspondiente al Seguro Social Campesino.

\blfootnote{Debido a la importancia de la cuenta “Deuda de Gobierno” y considerando que la DAIE no cuenta con la desagregación de los asientos contables de las cuentas establecidas en los balances financieros, con fecha 11 de agosto del 2021, el Actuario solicitó a la Subdirección Nacional Financiera del Seguro Social Campesino (SDNFSSC) se asigne un delegado técnico, el cual trabaje en conjunto con la DAIE.\\

Ante lo expuesto, en reuniones mantenidas entre la SDNFSSC y la DAIE se solicitó se remita el valor y porcentaje correspondiente al 40\% de la Deuda que el Gobierno que mantiene con el Fondo de Seguro Social Campesino; información que fue entregada por correo institucional con fecha 23 de septiembre del 2021 a la DAIE.}

\begin{table}[H]
 \begingroup\scriptsize\centering
 \captionsetup{justification=centering}
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
   \caption{Detalle de las cuentas por cobrar correspondiente al 40\% de la Deuda de Gobierno correspondiente al periodo 2012-2020}
  \label{tab:iess_cuentas_por_cobrar_gobierno_ssc}
 %\scalebox{1} {
 \fontsize{10}{12}\selectfont
  \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}
                  R{2.5cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
      Código & Cuenta contable & \multicolumn{2}{c}{2012 - 2020}\\
    \midrule
      \input{tablas/iess_cuentas_por_cobrar_gobierno_ssc.tex}
    \bottomrule
  \end{tabular}
  %}
\caption*{\scriptsize \textbf{Fuente:} Subdirección Nacional Financiera del Seguro Social Campesino. \\ \textbf{Elaborado:} DAIE.}
  \endgroup
\end{table}
\vspace{-0.5cm}

Como se evidencia en la tabla \ref{tab:iess_cuentas_por_cobrar_gobierno_ssc} la deuda de gobierno se encuentra conformada por dos cuentas que hace referencia al 40\% por pensiones de invalides y  vejez; los valores y porcentajes presentados corresponden al periodo comprendido entre el año 2012 al 2020.

\begin{table}[H]
 \begingroup\scriptsize\centering
 \captionsetup{justification=centering}
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
    \caption{Resumen 40\% Deuda de Gobierno periodo 2012 – 2020}
  \label{tab:iess_resumen_deuda_gobierno_ssc}
  \fontsize{10}{12}\selectfont
  %\scalebox{1}{
  \begin{tabular}{r!{\color{white}\vrule}R{3cm}r!{\color{white}\vrule}R{3cm}}
  \rowcolor{iess_green!60}
  \toprule
  \rowcolor{iess_green!60}
  Categoría & Valor \\
  \midrule
    \input {tablas/iess_resumen_deuda_gobierno_ssc.tex}
    \bottomrule
  \end{tabular}
 % }
  \caption*{ \scriptsize \textbf{Fuente:} Subdirección Nacional Financiera del Seguro Social Campesino.\\ \textbf{Elaborado:} DAIE.}
  \endgroup
\end{table}

Como se observa en la tabla resumen \ref{tab:iess_resumen_deuda_gobierno_ssc} en el periodo analizado la deuda de gobierno (40\%) representaba USD 134,36 millones, mientras que los valores cancelados fueron por  USD 44,86 millones, es decir se adeuda aún USD 89,49 millones.

El porcentaje de cumplimento se encuentra respecto al 100\% mismo que representa el 33,39\%, sin embargo si se analiza desde la perspectiva del 40\% que representa la deuda de gobierno, el cumplimiento es apenas del 13,36\%.

Adicionalmente, el Seguro Social Campesino tiene dos cuentas adicionales correspondiente a la Deuda de Gobierno (no corresponden al 40\%), estas son “0,30\% Contribución SSC” y “Contribuciones Especiales”, mismas que se detallan a continuación.

\begin{table}[H]
 \begingroup\scriptsize\centering
 \captionsetup{justification=centering}
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
   \caption{Detalle de las cuentas por cobrar correspondiente a la Deuda de Gobierno correspondiente al periodo 2012-2020}
  \label{tab:iess_cuentas_por_cobrar_gobierno_total_ssc}
 %\scalebox{1} {
 \fontsize{10}{12}\selectfont
  \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}
                  R{2.5cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   Código & Cuenta contable & \multicolumn{2}{c}{2012 - 2020}\\
    \midrule
      \input{tablas/iess_cuentas_por_cobrar_gobierno_total_ssc.tex}
    \bottomrule
  \end{tabular}
  %}
\caption*{\scriptsize \textbf{Fuente:} Subdirección Nacional Financiera del Seguro Social Campesino.\\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}

La tabla \ref{tab:iess_cuentas_por_cobrar_gobierno_total_ssc}
refleja que la cuenta del 0.30\% de contribución del SSC mantiene un porcentaje de cumplimiento del 49,33\%; mientras que las contribuciones especiales representan el 58,33\% del total.

\section{Patrimonio} \label{chp_infofinan:patrimonio}

A continuación, en la tabla \ref{tab:iess_patrimonio_hist_ssc} y figura \ref{fig:iess_patrimonio_hist_ssc} se presenta la evolución de la cuenta patrimonio del Fondo del Seguro Social Campesino correspondiente al período 2010 al 2020.

\begin{table}[H]
 \begingroup\scriptsize\centering
\captionsetup{justification=centering, width=1\textwidth}
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
    \caption{\small {Evolución del Patrimonio del Fondo del Seguro Social Campesino al 31 de diciembre de cada año}}
  \label{tab:iess_patrimonio_hist_ssc}
  {\fontsize{10}{12}\selectfont

  \begin{tabular}{
                  R{1.0cm}!{\color{white}\vrule}
                  R{2.8cm}!{\color{white}\vrule}
                  R{3.5cm}!{\color{white}\vrule}
                  R{3.5cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
    Año & Patrimonio (USD) & Variación anual (USD) & Tasa de Variación (\%)\\

    \midrule
     \input{tablas/iess_patrimonio_hist_ssc.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución del Patrimonio del Fondo del Seguro Social Campesino al 31 de diciembre de cada año}
\label{fig:iess_patrimonio_hist_ssc}
\includegraphics[scale=0.8]{graficos/iess_patrimonio_hist_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado}: DAIE.}
\end{figure}

Se observa que el patrimonio del Fondo del Seguro Social Campesino aumentó en 3,55 veces en el período 2010 al 2020, pasando de USD. 449,72 millones en el 2010 a USD 1.776,43 millones en el 2020; es decir anualmente en promedio (geométrico) creció en 13,52\%.

El incremento más representativo se evidencia en el año 2017 con una variación positiva de 24,42\%, es decir presenta una diferencia respecto al año anterior de USD 237,28 millones; caso contrario ocurre en el 2014 con una tasa de decrecimiento del -1,48\%, siendo la única del periodo analizado, pasando de USD 833,31 millones a USD 820,95 millones, debido a la desinversión de fondos para pago de prestadores internos por salud. Finalmente el patrimonio mantiene un crecimiento desacelerado llegando al 2020 con un valor de USD 1.776,43 millones.

\girarpagina

\subsection{Análisis vertical y horizontal del componente del Patrimonio}

En la tabla \ref{tab:iess_patrimonio_variacion_ssc1}, se presentan los componentes del patrimonio del Fondo del Seguro Social Campesino por el período comprendido entre el 2010 al 2020.

\begin{table}[H]
 \begingroup\scriptsize\centering
 \captionsetup{justification=centering, width=1\textwidth}
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
   \caption{Análisis de los componentes del Patrimonio del Fondo del Seguro Social Campesino del Trabajo al 31 de diciembre de cada año}
  \label{tab:iess_patrimonio_variacion_ssc1}
 %\scalebox{1} {
  \fontsize{10}{12}\selectfont
  \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multicolumn{2}{c}{Descripción de las cuentas} & 2010 & 2011& 2012 & 2013& 2014 & 2015\\

    \midrule
       \input{tablas/iess_patrimonio_variacion_ssc1.tex}
    \bottomrule
  \end{tabular}
  %}

  \endgroup
\end{table}

\begin{table}[H]
 \begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
  \label{tab:iess_patrimonio_variacion_ssc2}
 %\scalebox{1} {
  \fontsize{10}{12}\selectfont
  \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multicolumn{2}{c}{Descripción de las cuentas} & 2016 & 2017 & 2018 & 2019 & 2020\\

    \midrule
       \input{tablas/iess_patrimonio_variacion_ssc2.tex}
    \bottomrule
  \end{tabular}
  %}
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados – DNGF \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}


{\scriptsize\textbf{Nota Metodológica:}
Los balances del IESS en el período comprendido 2010 al 2020 han sufrido cambios en los códigos de cuentas, creación de nuevas cuentas, por tanto a continuación se presenta la variación y optimización; un ejemplo de ello se evidencia en los componentes del patrimonio, donde algunas cuentas fueron afectadas como las siguientes:

\begin{itemize}
\item	Existen dos períodos que se pueden ver desde el 2010 al 2014, y 2015 al 2020; en ambos se mantiene como cuenta principal del patrimonio “Fondos Capitalizados” y “Resultados”.
\item Mientras que en el primer período se recalcan dos cuentas como son “Superávit Revaluación” y  “Otros Fondos Capitalizados”; para el segundo período se consolidan en dos cuentas como son “Reservas” y “Aportes Patrimoniales”, cabe mencionar que superávit revaluación se hace una subcuenta de reservas.
\end{itemize} }
\regresargirar
A continuación se desarrolla el análisis vertical de los componentes del Patrimonio, dentro de los cuales se encuentran las siguientes subcuentas “Fondos Capitalizados”, “Superávit Revaluación”, “Resultados”, “Reservas”, “Otros Fondos Capitalizado” y “Aportes Patrimoniales”.



La cuenta con mayor representatividad dentro del total del patrimonio en el período analizado corresponde a los “Fondos Capitalizados” con el 75,29\% en promedio; dentro de las principales subcuentas se encuentran fondos acumulados, utilidad, pérdida y donaciones. El año de mayor representatividad fue el 2015 con el 93,67\%, mientras que el menor fue en el 2013 con 11,44\%.

En segundo lugar de representatividad lo ocupa la cuenta “Resultados” con el 24,33\% en promedio, cabe mencionar que el año con mayor porcentaje de representación se da en el 2013 con 90,71\%, mientras que el más bajo se visualiza en el año 2015 con 8,30\%, cabe mencionar que en el período dicha cuenta no presentó variaciones negativas.

Finalmente el tercer lugar lo ocupa la cuenta “Superávit Revaluación” con el 1,47\% en promedio correspondiente al período 2010 al 2014, ya que a partir del 2015 al 2020 la misma pasa a formar parte de la cuenta “Resultados”.


%%%%%%%%%
\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Porcentaje promedio de representatividad de los componentes del Patrimonio correspondiente al período 2010 – 2020}
\label{fig:iess_porcentaje_promedio_patrimonio_representatividad_ssc}
\includegraphics[scale=0.9]{graficos/iess_porcentaje_promedio_patrimonio_representatividad_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF.\\  \textbf{Elaborado:} DAIE.}
\end{figure}


\girarpagina

En la tabla \ref{tab:iess_patrimonio_del_fondo_ssc} , se presenta el análisis horizontal de los componentes del Patrimonio del Fondo del Seguro Social Campesino correspondiente al período 2011-2020.

\begin{table}[H]
 \begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\caption{Análisis horizontal del Patrimonio del Fondo del Seguro Social Campesino al 31 de diciembre de cada año (\%)}
\label{tab:iess_patrimonio_del_fondo_ssc}
%\scalebox{1} {
\fontsize{10}{12}\selectfont
\begin{tabular}{r!{\color{white}\vrule}R{1cm}!{\color{white}\vrule} R{1cm}!{\color{white}\vrule}
                                R{1cm}!{\color{white}\vrule}
                                R{1cm}!{\color{white}\vrule}
                                R{1cm}!{\color{white}\vrule}
                                R{1cm}!{\color{white}\vrule}
                                R{1cm}!{\color{white}\vrule}
                                R{1cm}!{\color{white}\vrule}
                                R{1cm}!{\color{white}\vrule}
                                R{1cm}!{\color{white}\vrule}
                                R{1cm}}
\rowcolor{iess_green!60}
\toprule
\rowcolor{iess_green!60}
\multirow{1}[0]{*}{Descripción de las cuentas}& 2011& 2012& 2013& 2014& 2015& 2016 & 2017 & 2018 & 2019 & 2020\\

\midrule
\input{tablas/iess_patrimonio_del_fondo_ssc.tex}
\bottomrule
\end{tabular}
%}
\caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
\endgroup
\end{table}



{\scriptsize\textbf{Nota Metodológica:}
\begin{itemize}
\item 	En el año 2017 se evidencia el mayor incremento del Patrimonio con una tasa de 24,42\%, debido al aumento de la subcuenta “Resultados del Ejercicio Actual” (34,60\%). Cabe mencionar que el único año con variación negativa del período analizado es el año 2014, con una tasa de decrecimiento de -1,48\%, debido a la subcuenta “Resultados del Ejercicio Actual” (-33,32\%).
\end{itemize} }

En el período 2011 al 2020 la cuenta Patrimonio mantiene una tasa de crecimiento de 255,48\%. Dentro del mismo se evidencia el mayor incremento en el año 2013 en la subcuenta “Resultados” con una variación positiva de 662,44\%, debido los resultados del ejercicio actual representando un incremento de USD 656,79 millones respecto al año anterior. En el mismo año se evidencia la tasa de decrecimiento más significativa  en la subcuenta “Superávit Revaluación” con -180,71\%.

A continuación, se procede con el análisis de ingresos y egresos los cuales se encuentran en los Estados de Pérdida y Ganancias al 31 de diciembre de cada año, por el período comprendido entre el 2011 y el 2020.
\regresargirar



\section{Ingresos}

En la tabla \ref{tab:iess_Ingresos_hist_ssc} y figura \ref{fig:iess_Ingresos_hist_ssc} se presenta la evolución de los ingresos del Fondo del Seguro Social Campesino durante el período 2010 al 2020.

\begin{table}[H]
 \begingroup\scriptsize\centering
 \captionsetup{justification=centering}
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
    \caption{\small {Evolución de los Ingresos del Fondo del Seguro Social Campesino\\ al 31 de diciembre de cada año}}
  \label{tab:iess_Ingresos_hist_ssc}
  {\fontsize{10}{12}\selectfont

  \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}R{2.5cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multirow{2}[0]{*}{Año} & Ingresos (USD) & Variación anual (USD) & Tasa de Variación (\%)\\

    \midrule
     \input{tablas/iess_Ingresos_hist_ssc.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución de los Ingresos del Fondo del Seguro Social Campesino\\ al 31 de diciembre de cada año}
\label{fig:iess_Ingresos_hist_ssc}
\includegraphics[scale=0.8]{graficos/iess_Ingresos_hist_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado}: DAIE.}
\end{figure}

Los Ingresos del Fondo del Seguro Social Campesino durante el periodo analizado tuvieron una tasa de crecimiento del 130,98\%, es decir pasaron del USD 181,78 millones (2010) a USD 419,88 millones (2020), creciendo anualmente en promedio (geométrico) al 8,73\%.

En el tiempo dicha cuenta en la mayoría de los años ha mantenido variaciones positivas, siendo el 2019 el año que mayor tasa de crecimiento registró con el 30,06\%, marcando una diferencia respecto al año anterior de USD 108,11 millones.

En los años 2015, 2016 y 2020 se evidencian variaciones negativas, siendo la más significativa en el último año con una tasa de decrecimiento de -10,23\%; motivado por el impacto de las desinversiones, afectando los ingresos financieros por inversiones, adicionalmente se suma la crisis sanitaria y económica vivida en el país lo que ocasionó una disminución en los aportes.

\girarpagina

\subsection{Análisis vertical y horizontal del componente del Ingreso}
En la tabla \ref{tab:iess_Ingresos_variacion_ssc1}, se presentan los componentes del ingreso del Fondo del Seguro Social Campesino por el período comprendido entre el 2010 al 2020.
\begin{table}[H]
 \begingroup\scriptsize\centering
\captionsetup{justification=centering, width=1\textwidth}
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
   \caption{Análisis de los componentes del Ingreso del Fondo del Seguro Social Campesino del Trabajo al 31 de diciembre de cada año}
  \label{tab:iess_Ingresos_variacion_ssc1}
 \fontsize{9}{10}\selectfont
% \scalebox{1} {
  \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multicolumn{2}{c}{Descripción de las cuentas} & 2010 & 2011 & 2012 & 2013 & 2014 & 2015\\

    \midrule
       \input{tablas/iess_Ingresos_variacion_ssc1.tex}
    \bottomrule
  \end{tabular}
  %}

  \endgroup
\end{table}

\begin{table}[H]
 \begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
  \label{tab:iess_Ingresos_variacion_ssc2}
% \scalebox{1} {
 \fontsize{9}{10}\selectfont
  \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multicolumn{2}{c}{Descripción de las cuentas} & 2016 & 2017 & 2018 & 2019 & 2020\\

    \midrule
       \input{tablas/iess_Ingresos_variacion_ssc2.tex}
    \bottomrule
  \end{tabular}
%  }
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados – DNGF \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}
\regresargirar

{\scriptsize\textbf{Nota Metodológica:}
Los balances del IESS en el período comprendido 2010 al 2020 han sufrido cambios en los códigos de cuentas, creación de nuevas cuentas, por tanto a continuación se presenta la variación y optimización; un ejemplo de ello se evidencia en los componentes del ingreso, donde algunas cuentas fueron afectadas como las siguientes:

\begin{itemize}
\item	Entre el 2010 al 2020 se registran dos cuentas, esta son ingresos de operación denominados en esos años como Aportes IESS; del mismo modo los ingresos financieros se encuentran agrupados por subcuentas como inversión deuda renta fija sector privado/público, ingresos inversión sector externo y utilidad en venta de bienes.
\item A partir del 2013 al 2020 se crea ingresos extraordinarios, cuenta constituida por interés, tasas y contribuciones.
\item	En el año 2015 aparece como subcuenta principal “Ingresos por arriendos”, misma que a partir del año 2016 forma parte de ingresos financieros.
\end{itemize} }
% 
A continuación se desarrolla el análisis vertical de los componentes del Ingreso, dentro de los cuales se encuentran las siguientes subcuentas “Ingresos de Operación”, “Ingresos Financieros”, “Ingresos por Arriendos”, “Ingresos extraordinarios “y “Otros Resultados Integrales”.

La cuenta con mayor representatividad dentro del total del ingreso en el período analizado fue los “Ingresos de Operación” con el 82,13\% en promedio. El año con el mayor porcentaje de representación fue el 2011 con el 89,70\%, mientras que el menor se dio en el 2020 con 75,84\%.

En segundo lugar de representatividad se lleva los “Ingresos Financieros” con el 16,06\% en promedio, cabe mencionar que el año con mayor porcentaje de representación se dio en el 2020 con 24,06\%, mientras que el más bajo se visualiza en el año 2011 con 10,30\%. Finalmente el tercer lugar lo ocupa la cuenta “Ingresos extraordinarios”  con el 2,48\% en promedio correspondiente al período 2013-2020.

%%%%%%%%%
\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Porcentaje promedio de representatividad de los componentes del Ingreso correspondiente al período 2010 – 2020}
\label{fig:iess_porcentaje_promedio_Ingresos_representatividad_ssc}
\includegraphics[scale=0.9]{graficos/iess_porcentaje_promedio_Ingresos_representatividad_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF.\\ \textbf{Elaborado:} DAIE.}
\end{figure}

\girarpagina


En la tabla \ref{tab:iess_Ingresos_del_fondo_ssc}, se presenta el análisis horizontal de los Ingresos del Fondo del Seguro Social Campesino correspondiente al período 2011 al 2020.

\begin{table}[H]
 \begingroup\scriptsize\centering
 \captionsetup{justification=centering}
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
   \caption{Análisis horizontal de los ingresos del Fondo del Seguro Social Campesino (\%)}
  \label{tab:iess_Ingresos_del_fondo_ssc}
 %\scalebox{1} {
  \fontsize{10}{12}\selectfont
  \begin{tabular}{r!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}
                  R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}!{\color{white}\vrule}R{1cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multirow{1}[0]{*}{Descripción de las cuentas}& 2011 & 2012 & 2013& 2014 & 2015& 2016 & 2017 & 2018 & 2019 & 2020\\

    \midrule
      \input{tablas/iess_Ingresos_del_fondo_ssc.tex}
    \bottomrule
  \end{tabular}
  %}
  \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}

{\scriptsize \textbf{Nota Metodológica}
\begin{itemize}
\item	En el año 2019 se evidencia el mayor incremento del Ingreso con una tasa de 30,06\%, debido a la subcuenta “Ingresos Financieros” con una diferencia de USD 32,28 millones respecto al año anterior. En el año 2020 se evidencia el decrecimiento más significativo de los ingresos en -10,23\%, debido a la disminución de las subcuentas “Ingresos Extraordinarios” e “Ingresos de Operación”.
\end{itemize} }

En el período 2010 al 2020 la cuenta Ingresos ha mantenido tasas de crecimiento en la mayoría de los años con excepción del 2015, 2016 y 2020. Adicionalmente se evidencia que el año 2020 ha tenido la tasa de crecimiento más baja del período, en parte debido a la crisis sanitaria y económica vivida en el país.

Dentro de las subcuentas de los ingresos se evidencia la mayor tasa de crecimiento del período en el año 2017 con 217,56\%, debido al incremento en subcuenta “Intereses Ganados”, la cual pasó de USD. 7,73 millones a USD. 24,57 millones. Mientras que el decrecimiento más significativo se evidenció en el año 2020 con el -94,16\%, debido a la disminución de los intereses ganados e ingresos varios en 97,02\% y -93,41\% respectivamente.

\regresargirar

  
\subsection{Ingresos por aportes y contribuciones}
En la tabla \ref{tab:iess_Aportes_hist_ssc} y figura \ref{fig:iess_Aportes_hist_ssc} se presenta la evolución de los Ingresos por aportes del Fondo del Seguro Social Campesino durante el período 2010 al 2020.

\begin{table}[H]
 \begingroup\scriptsize\centering
 \captionsetup{justification=centering}
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
    \caption{\small {Evolución de los aportes del Fondo del Seguro Social Campesino al 31 de diciembre de cada año}}
  \label{tab:iess_Aportes_hist_ssc}
  {\fontsize{10}{12}\selectfont

  \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}R{2.5cm}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multirow{2}[0]{*}{Año} & Aportes IESS (USD) & Variación anual (USD) & Tasa de Variación (\%)\\

    \midrule
     \input{tablas/iess_Aportes_hist_ssc.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución de los aportes del Fondo del Seguro Social Campesino al 31 de diciembre de cada año}
\label{fig:iess_Aportes_hist_ssc}
\includegraphics[scale=0.8]{graficos/iess_Aportes_hist_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE.}
\end{figure}

Los ingresos por aportes en el período 2010 al 2020 en el SSC mantuvieron una tasa de crecimiento del 113,13\%, pasando de USD. 147,72 a USD 315.09; es decir en promedio (geométrico) creció anualmente a una tasa de 7,87\%.

El incremento más significativo se evidencia en el año 2011 con una tasa de 34,01\%, misma que mantuvo una diferencia de USD 50,23 respecto al año anterior; mientras que el decrecimiento más significativo se evidencia en el año 2020 con el -14,80\%, pasando de USD 369,84 a USD 315,09, debido en gran medida a la crisis sanitaria y económica vivida en el país.

Los valores de la tabla \ref{tab:iess_Evolucion_aportes_ssc} presentan de manera desglosada los aportes al SSC detallados de la siguiente manera:

\begin{itemize}
\item	Aporte personal de los aliados al SGO 0,35\%
\item	Aporte patronal del SGO 0,35\%
\item	Aporte de los jefes y jefas de las familias protegidas,
\item	Aporte de los Seguros Públicos ISSFA e ISSPOL (0,35\% aporte personal y 0,35\% aporte patronal)
\item	Aporte por primas netas de los seguros privados y cuotas de afiliación de medicina prepagada (0,5\%)
\item	Aporte del Estado: La contribución obligatoria del cero punto treinta (0,30\%) de la materia grabada de todos los afiliados al SGO, con relación de dependencia, para el Seguro Social Campesino.
\item	El cuarenta por ciento (40\%) de las pensiones que paga el IESS a sus jubilados y beneficiarios de montepío.
\item	Aporte del Estado: El valor de USD 288.000,00 anuales que deberá acreditar el Banco Central del Ecuador en la cuenta especial denominada Seguro Social Campesino
\item	Aporte del Estado: Por enfermedades catastróficas
\item	Aporte del Estado: Por atención médica a jubilados
\item	Recargos y multas
\item	Ingresos ejercicio año anterior
\end{itemize}

\girarpagina

\begin{center}
\begin{table}[H]
 \begingroup\scriptsize\centering
\captionsetup{justification=centering} 
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\caption{\small {Evolución de los aportes, contribuciones y rendimientos de las inversiones del Fondo del Seguro Social Campesino}}
\label{tab:iess_Evolucion_aportes_ssc}
   \scalebox{1.2}{
  \begin{tabular}{R{1cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multirow{1}[0]{*}{Año} & APA  35\%  & AP 0,35\% & AJF & ASP & APN & AE  \\
    \midrule
     \input{tablas/iess_Evolucion_aportes_ssc1.tex}
    \bottomrule
    \caption*{\scriptsize  \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\
    \textbf{Elaborado:} DAIE}
  \end{tabular}
  }
  \endgroup
\end{table} 
\justifying
{\scriptsize{ {\bf APA 0,35\%:} Aporte personal de los afiliados al SGO 0,35\%.\\
  {\bf AP 0,35\%:} Aporte patronal del SGO 0,35\%.\\
  {\bf AJF:} Aporte de los jefes y jefas de las familias protegidas.\\
  {\bf ASP:} Aporte de los Seguros Públicos ISSFA e ISSPOL (0,35\% aporte personal y 0,35\% aporte patronal).\\
  {\bf APN:} Aporte por primas netas de los seguros privados y cuotas de afiliación de medicina prepagada (0,5\%).\\
  {\bf AE 0,30\%:} Aporte del Estado: La contribución obligatoria del cero punto treinta (0,30\%) de la materia grabada de todos los afiliados al SGO, con relación de dependencia, para el Seguro Social Campesino.}}



\begin{table}[H]
 \begingroup\scriptsize\centering
\captionsetup{justification = centering}
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
  \label{tab:iess_Evolucion_aportes_ssc2}
   \scalebox{1.2}{
  \begin{tabular}{R{1cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multirow{1}[0]{*}{Año} & 40\% PJ & AESSC & AEEC & AEAM & RM & IEA\\
       \midrule
     \input{tablas/iess_Evolucion_aportes_ssc2.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize 
  \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}

\justifying{
{\scriptsize{\hspace{-0.7cm} {\bf 40\% PJ:} El cuarenta por ciento (40\%) de las pensiones que paga el IESS a sus jubilados y beneficiarios de montepío.\\
  {\bf AESSC:} Aporte del Estado: El valor de USD 288.000,00 anuales que deber\'{a} acreditar el Banco Central del Ecuador en la cuenta especial denominada Seguro Social Campesino.\\
  {\bf AEEC:} Aporte del Estado: Por enfermedades catastróficas.\\
   {\bf AEAM:} Aporte del Estado: Por atención médica a jubilados.\\
   {\bf RM:} Recargos y Multas.\\
   {\bf IEA:} Ingresos ejercicios años anteriores.\\}}}

\end{center}
\regresargirar

Debido al objeto del presente estudio, a continuación se realiza un análisis del impacto respecto a las subcuentas de Ingresos por aportes y contribuciones del Fondo del Seguro Social Campesino.

\begin{table}[H]
 \begingroup\scriptsize\centering
 \captionsetup{justification = centering}
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
    \caption{\small {Porcentaje de Participación de Aportes y Contribuciones}}
  \label{tab:iess_porcentaje_de_Aportes_ssc}
  {\fontsize{10}{12}\selectfont

  \begin{tabular}{R{9 cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multirow{2}[0]{*}{Aportes y Contribuciones} & Valores monetarios & \% de Participación\\

    \midrule
      \input{tablas/iess_porcentaje_de_Aportes_ssc.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}


La tabla \ref{tab:iess_porcentaje_de_Aportes_ssc} evidencia que para el periodo 2010 – 2020 la mayor participación/representatividad de la cuenta ingresos por aportes se encuentra en la subcuenta “Aporte personal de los afiliados Al SGO 0,35\%” con el 35,31\% del total, seguida de “Aporte del Estado: La contribución obligatoria del cero punto treinta (0,30\%) de la materia grabada de todos los afiliados al SGO, con relación de dependencia, para el Seguro Social Campesino” con el 26\%; y finalmente con un tercer lugar con el 24\% la subcuenta denominada “Aporte patronal del SGO 0,35\%”

Las subcuentas con menor representatividad con apenas el 0,1\% corresponden a los “Aporte del Estado: El valor de USD 288.000,00 anuales que debería acreditar el Banco Central del Ecuador en la cuenta especial denominada Seguro Social Campesino” y “Aporte del Estado: Por atención médica a jubilados”; mientras que “Ingresos de ejercicios años anteriores” representó el 0,01\%.

%%%%%%%%%
\begin{figure}[H]
\centering
\captionsetup{justification = centering}
\caption{Porcentaje promedio de representatividad de los egresos prestacionales, gastos de administración y otros gastos correspondiente al período 2010 – 2020}
\label{fig:iess_porcentaje_de_Aportes_ssc}
\includegraphics[scale=0.8]{graficos/iess_porcentaje_de_Aportes_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF.\\ \textbf{Elaborado:} DAIE.}
\end{figure}

\section{Egresos Prestacionales y Gastos de Administración}

 En la tabla \ref{tab:iess_egresos_prestacionales_ssc} y figura \ref{fig:iess_egresos_prestacionales_ssc} se presenta la evolución histórica de los egresos prestacionales del Fondo del Seguro SSC al 31 de diciembre de cada año.


\begin{table}[H]
  \begingroup\scriptsize\centering
  \captionsetup{justification = centering}
 \setlength\extrarowheight{1pt}
 \setlength\aboverulesep{-0.5pt}
 \setlength\belowrulesep{0pt}
     \caption{\small {Evolución de los egresos prestacionales del Fondo de SSC a 31 de diciembre de cada año }}
   \label{tab:iess_egresos_prestacionales_ssc}
   {\fontsize{10}{12}\selectfont

   \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}
                   R{2.5cm}!{\color{white}\vrule}R{2.5cm}}
   \rowcolor{iess_green!60}
     \toprule
     \rowcolor{iess_green!60}
    \multirow{2}[0]{*}{Año} & Egresos Prestacionales & Incremento Anual & Variación Anual\\

     \midrule
      \input{tablas/iess_egresos_prestacionales_ssc.tex}
     \bottomrule
   \end{tabular}
   }
   \caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
   \endgroup
 \end{table}


 \begin{figure}[H]
 \centering
 \captionsetup{justification = centering}
 \caption{Evolución de los egresos prestacionales del Fondo de SSC a 31 de diciembre de cada año (En millones de dólares)}
 \label{fig:iess_egresos_prestacionales_ssc}
 \includegraphics[scale=0.7]{graficos/iess_egresos_prestacionales_ssc.png}
 \caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE.}
 \end{figure}

 Los egresos prestacionales se encuentran compuesto por pensiones de invalidez, vejez, atención médica y hospital, servicios prestados por particulares, auxilio funeral, otros gastos en afiliados, jubilados; es así que entre el año 2010 al 2020 los egresos mantuvieron una tasa de crecimiento del 196,94\% pasando de USD. 56,70 millones a USD. 168,35 millones, incrementando en promedio (geométrico) anual 11,50\%.

 Las tasas de crecimiento más elevadas en el periodo analizado se evidencian en los años 2011 y 2018 con el 33,14\% y 45,79\% respectivamente; mientras que el decrecimiento más significativo se ejecutó en el año 2016 con una variación del -19,16\%, es decir una diferencia de USD. 24,24 millones respecto al año anterior. Es importante recalcar que los dos últimos años a pesar de mantener tasas de crecimiento positivas se evidencian desaceleraciones en su incremento.

 En la tabla \ref{tab:iess_gastos_de_administacion_ssc} y figura \ref{fig:iess_gastos_de_administacion_ssc} se presenta la evolución histórica de los gastos de administración (contribución) del Fondo del Seguro Social Campesino a 31 de diciembre de cada año.

 \begin{table}[H]
  \begingroup\scriptsize\centering
   \captionsetup{justification = centering, width=1\textwidth}
 \setlength\extrarowheight{1pt}
 \setlength\aboverulesep{-0.5pt}
 \setlength\belowrulesep{0pt}
     \caption{\small {Evolución de los gastos de administración (contribución) del Fondo del Seguro Social Campesino a 31 de diciembre de cada año}}
   \label{tab:iess_gastos_de_administacion_ssc}
   {\fontsize{10}{12}\selectfont

   \begin{tabular}{r!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}R{2.5cm}!{\color{white}\vrule}
                   R{2.5cm}!{\color{white}\vrule}R{2.5cm}}
   \rowcolor{iess_green!60}
     \toprule
     \rowcolor{iess_green!60}
    \multirow{2}[0]{*}{Año} & Gastos de Administración & Incremento Anual & Variación Anual\\

     \midrule
      \input{tablas/iess_gastos_de_administacion_ssc.tex}
     \bottomrule
   \end{tabular}
   }
   \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
   \endgroup
 \end{table}


 \begin{figure}[H]
 \centering
\captionsetup{justification = centering}
 \caption{Evolución de los gastos de administración (contribución) del Fondo del Seguro Social Campesino a 31 de diciembre de cada año (En millones de dólares)}
 \label{fig:iess_gastos_de_administacion_ssc}
 \includegraphics[scale=0.8]{graficos/iess_gastos_de_administacion_ssc.png}
 \caption*{\scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE.}
 \end{figure}


 {\scriptsize
 \textbf{Nota Técnica:} Para el análisis del presente componente se consideró la información del Balance Financiero de la Administradora del SSC, debido que en el Fondo del Seguro mencionado a partir del año 2013 no se cuenta con el registro del egreso por “Contribución Administradora”, sino que se registra directamente como un ingreso en los estados financieros de la Administradora.
 }

 Los gastos de administración corresponde a la contribución a la administradora, es así que entre el año 2010 al 2020 los gastos mantuvieron una tasa de crecimiento del 120,41\% pasando de USD 6,06 millones a USD 12,28 millones, incrementando en promedio (geométrico) anual 7,31\%. El comportamiento de la cuenta es variable en el tiempo, manteniendo variaciones positivas como negativas.

 El incremento más significativo del periodo analizado se evidencia en el año 2015 con una variación positiva de 5.495,59\%, pasando de  USD. 221.196 en el 2014 a USD 12,37 millones en el 2015; mientras que el decrecimiento más significativo se  evidencia  en el año 2013 con el -90,69\%, pasando de USD 9,54 millones a USD 888.062.

 A continuación, en la tabla \ref{tab:iess_descripcion_gastos_egresos_ssc} se presenta la evolución de los egresos prestacionales como de los gastos de administración del Fondo del SSC correspondiente al período 2010 - 2020.
 
 \girarpagina
 
\begin{table}[H]
 \begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
    \caption{\small {Evolución de los egresos prestacionales, gastos de administración y otros gastos}}
  \label{tab:iess_descripcion_gastos_egresos_ssc}
  \scalebox{0.9}{

  \begin{tabular}{r!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}R{2cm}!{\color{white}\vrule}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multirow{1}[0]{*}{Descripción de las cuentas} & 2010 & 2011 & 2012 & 2013 & 2014 & 2015 & 2016 & 2017 & 2018 & 2019 &2020\\

    \midrule
     \input{tablas/iess_descripcion_gastos_egresos_ssc.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}


{\scriptsize \textbf{Nota Metodológica:} Para el análisis se considera información de los Balances Financieros de los egresos del Fondo, así como también de los ingresos de las Administradora específicamente en la cuenta “Contribución Administradora”; por tal motivo el total de los egresos mencionados en la tabla 
\ref{tab:iess_descripcion_gastos_egresos_ssc} no serán igual al total registrado en los balances de resultados  del Fondo del Seguro Social Campesino.}

\subsection{Análisis horizontal y vertical de los egresos prestacionales y gastos de administración}

En las tablas \ref{tab:iess_descripcion_cuentas_horizontal_ssc} y \ref{tab:iess_descripcion_cuentas_vertical_ssc} , se presentan los análisis horizontal y vertical de los egresos prestacionales y gastos de administración del Fondo de SSC del período 2011 a 2020.

\begin{table}[H]
 \begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
    \caption{\small {Análisis horizontal de la evolución de los egresos prestacionales y gastos de administración del fondo de SSC (\%)}}
  \label{tab:iess_descripcion_cuentas_horizontal_ssc}
  \scalebox{1}{

 \begin{tabular}{r!{\color{white}\vrule}R{1.5cm}!{\color{white}\vrule}R{1.5cm}!{\color{white}\vrule}R{1.5cm}!{\color{white}\vrule}R{1.5cm}!{\color{white}\vrule}R{1.5cm}!{\color{white}\vrule}R{1.5cm}!{\color{white}\vrule}R{1.5cm}!{\color{white}\vrule}R{1.5cm}!{\color{white}\vrule}R{1.5cm}!{\color{white}\vrule}R{1.5cm}!{\color{white}\vrule}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multirow{1}[0]{*}{Descripción de las cuentas}& 2011 &2012 & 2013 &2014 &2015 &2016 &2017 &2018 &2019 &2020 \\

    \midrule
     \input{tablas/iess_descripcion_cuentas_horizontal_ssc.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}


\regresargirar

Los egresos por prestaciones pagadas mantienen variaciones positivas en la mayoría del período, con excepción de los años 2016 y 2017 en las que presentan tasas de decrecimiento del -19,16\% y -14,07\% respectivamente.

Los egresos prestacionales crecieron anualmente en promedio (geométrico) en 11,50\%. El incremento más elevado se refleja en la cuenta “Atención Médica y Hospital” en el año 2012 con una tasa del 355,31\%, pasando de USD. 1,73 millones a USD. 7,87 millones; caso contario sucedió en el año 2017 (en la misma cuenta) donde la tasa de decrecimiento más significativa representó el -69,56\%. Cabe mencionar que en los dos últimos años dicha cuenta comienza a crecer significativamente llegando al 2020 con una variación positiva del 45,83\%.


\begin{table}[H]
 \begingroup\scriptsize\centering
\captionsetup{justification = centering}
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
    \caption{\small {Análisis vertical de la evolución de los egresos prestacionales y gastos de administración del fondo de SSC (\%)}}
  \label{tab:iess_descripcion_cuentas_vertical_ssc}
  \scalebox{0.75}{
\begin{tabular}{r!{\color{white}\vrule}R{1.2cm}!{\color{white}\vrule}R{1.2cm}!{\color{white}\vrule}R{1.2cm}!{\color{white}\vrule}R{1.2cm}!{\color{white}\vrule}R{1.2cm}!{\color{white}\vrule}R{1.2cm}!{\color{white}\vrule}R{1.2cm}!{\color{white}\vrule}R{1.2cm}!{\color{white}\vrule}R{1.2cm}!{\color{white}\vrule}R{1.2cm}!{\color{white}\vrule}R{1.2cm}!{\color{white}\vrule}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multirow{1}[0]{*}{Descripción de las cuentas}&2010&2011 &2012 &2013 &2014 &2015 &2016 &2017 &2018 &2019 &2020 \\

    \midrule
     \input{tablas/iess_descripcion_cuentas_vertical_ssc.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}
\vspace{-0.5cm}

 \begin{figure}[H]
 \centering
\captionsetup{justification = centering}
 \caption{Porcentaje promedio de representatividad de los componentes del Ingreso correspondiente al período 2010 – 2020}
 \label{fig:iess_porcentaje_promedio_egresos_pres_ssc}
 \includegraphics[scale=0.8]{graficos/iess_porcentaje_promedio_egresos_pres_ssc.png}
 \caption*{\scriptsize \textbf {Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF.\\  \textbf{Elaborado:} DAIE.}
 \end{figure}
\vspace{-0.5cm}
Los “Egresos Prestacionales” es la cuenta con mayor representatividad del total, con un peso promedio del 51,63\% para el período analizado; debido que en la misma se encuentra los gastos por pensiones, atención médica y hospitalaria, servicios prestados por particulares, auxilio de funerales, otras gastos de afiliados y jubilados.

El segundo lugar lo ocupa la cuenta “Otros Gastos” con un porcentaje de representatividad del 43,69\%, en la misma se encuentran gastos financieros, gastos de administración, servicios prestacionales a unidades provinciales, pérdida de venta de activos, depreciación, etc. El tercer lugar lo ocupa los gastos de administración con el 4,68\%, en el que se considera el gasto por contribución para la administradora.



 \section{Ingresos por aportes versus egresos prestacionales}

 Se presenta en la tabla \ref{tab:iess_ingresos_vs_egresos_ssc} la evolución de los ingresos por aportes (personal y patronal) de los afiliados activos versus los egresos pensionales de este fondo por cada año. El resultado corresponde a la diferencia entre los aportes de los afiliados y los egresos pensionales.

 \begin{table}[H]
  \begingroup\scriptsize\centering
  \captionsetup{justification = centering}
 \setlength\extrarowheight{1pt}
 \setlength\aboverulesep{-0.5pt}
 \setlength\belowrulesep{0pt}
     \caption{\small {Evolución de ingresos por aportes vs los egresos prestacionales del Fondo de SSC}}
   \label{tab:iess_ingresos_vs_egresos_ssc}
   \scalebox{0.9}{

   \begin{tabular}{r!{\color{white}\vrule}r!{\color{white}\vrule}r!{\color{white}\vrule}r!{\color{white}\vrule}r!{\color{white}\vrule}R{1.5cm}!{\color{white}\vrule}R{1.5cm}!{\color{white}\vrule}r!{\color{white}\vrule}}
   \rowcolor{iess_green!60}
     \toprule
     \rowcolor{iess_green!60}
    \multirow{1}[0]{*}{Año} & Aportes de Afiliados & Egresos Prestacionales & 60\% Egresos Prestacionales & Resultado & Utilización anual (\%) & Valor para acumulación (\%) & Acumulación a la Reserva\\

     \midrule
      \input{tablas/iess_ingresos_vs_egresos_ssc.tex}
     \bottomrule
   \end{tabular}
   }
   \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
   \endgroup
 \end{table}

 {\scriptsize
 \textbf{Nota Metodológica:} No se considera el 40\% de la Deuda de Gobierno, para el presente análisis se toma un supuesto solo del 60\% que le correspondería al IESS.
 }

 Al realizar una comparación entre las cuentas de ingresos por aportes sobre los egresos prestacionales correspondiente al 60\% de obligación del IESS, se observa que en todo el período los egresos no son superiores a los ingresos, por tanto no ha sido necesario recurrir ya sea al rendimiento o a la desinversión de la reserva, manteniendo en promedio un porcentaje de acumulación del 60\%.

 De tal manera que al año 2020 el Fondo de SSC mantiene un superávit de USD. 82,46 millones. Finalmente, se evidencia que la acumulación de la reserva se encuentra al 31 de diciembre del 2020 en USD. 1.104,39 millones.

 \section{Comparación de ingresos por aportes versus los gastos de administración del Fondo de SSC}

 Se presenta en la tabla \ref{tab:iess_ingresos_vs_gastos_ssc} la evolución de los ingresos por aportes versus los gastos de administración (contribución administradora) de este fondo a diciembre de cada año; el resultado corresponde a la diferencia de dichas cuentas.
 
 \begin{table}[H]
\begingroup\scriptsize\centering
\captionsetup{justification = centering}
 \setlength\extrarowheight{1pt}
 \setlength\aboverulesep{-0.5pt}
 \setlength\belowrulesep{0pt}
     \caption{\small{Evolución de ingresos por aportes versus los gastos de administración del Fondo del SSC}}
   \label{tab:iess_ingresos_vs_gastos_ssc}
   %\scalebox{0.8}{
   \fontsize{10}{12}\selectfont
   \begin{tabular}{r!{\color{white}\vrule}r!{\color{white}\vrule}r!{\color{white}\vrule}r!{\color{white}\vrule}r!{\color{white}\vrule}r!{\color{white}\vrule}} 
   \rowcolor{iess_green!60}
     \toprule
     \rowcolor{iess_green!60}
    \multirow{1}[0]{*}{Año} & Aportes de afiliados & Gastos de Administración  & Resultado & Utilización anual & Valor para acumulación \\
 
     \midrule
      \input{tablas/iess_ingresos_vs_gastos_ssc.tex}
     \bottomrule
   \end{tabular}
   %}
   \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
   \endgroup
 \end{table}
 
 
Al realizar una comparación entre los gastos de contribución a la administradora con los ingresos por aportes, se determina que en la mayoría del periodo con excepción del 2013 y 2014 no se cumple con lo establecido en la \legalcite{ResIESS_CD101} disposición tercera: “los gastos de administración de los seguros generales de Pensiones (I200), Riesgos de Trabajo (I230), Salud (J400) y los del Seguro Social Campesino (H800), no podrán exceder del cuatro por ciento (4\%) de los ingresos anuales de sus respectivos fondos presupuestarios”, ya que el porcentaje de utilización anual es del 7\% superando lo establecido en la resolución.

\section{Análisis de las Reservas Disponibles }

Del análisis se observa un crecimiento paulatino del patrimonio en el periodo 2010-2020 con excepción en los años 2016 y 2017 donde decrecen significativamente; la reserva al año 2020 alcanzó USD 1.776,43 millones.

\begin{table}[H]
 \begingroup\scriptsize\centering
\captionsetup{justification = centering}
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
    \caption{\small {Relación patrimonio gasto prestacional del Fondo del SSC}}
  \label{tab:iess_patrimonio_y_gasto_pres_ssc}
  %\scalebox{0.8}{
\fontsize{9}{9}\selectfont
  \begin{tabular}{r!{\color{white}\vrule}r!{\color{white}\vrule}r!{\color{white}\vrule}r!{\color{white}\vrule}}
  \rowcolor{iess_green!60}
    \toprule
    \rowcolor{iess_green!60}
   \multirow{1}[0]{*}{Año}& Egresos prestacionales & Patrimonio & Relación patrimonio /  Gastos \\

    \midrule
     \input{tablas/iess_patrimonio_y_gasto_pres_ssc.tex}
    \bottomrule
  \end{tabular}
 % }
  \caption*{ \scriptsize \textbf{Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\ \textbf{Elaborado:} DAIE}
  \endgroup
\end{table}

El indicador patrimonio/gasto revela la cantidad de dólares que tiene en el año de análisis, es decir cada dólar de obligación por gastos. Esta relación mantiene una tendencia decreciente en el periodo 2010 al 2020, con un porcentaje promedio del 9,40.

Finalmente al 31 de diciembre de 2020 termina con USD 10,55 disponibles por cada dólar de obligación; cabe mencionar que el año 2017 registró la mayor relación con USD 13,75 por cada dólar de obligación, mientras que el 2015 la más baja del periodo con USD 7,17.


%---------------------------------------------------------------------------------------------------
\section{Descripción del portafolio de inversiones}
\label{chp_infofinan:rentablidad}

El artículo 372 de la \legalcite{ConsEcu:2008} establece: ``Los fondos y reservas
del seguro universal obligatorio serán propios y distintos de los del fisco, y servirán para cumplir
de forma adecuada los fines de su creación y sus funciones. Ninguna institución del Estado podrá
intervenir o disponer de sus fondos y reservas, ni menoscabar su patrimonio. Los fondos
provisionales (sic) públicos y sus inversiones se canalizarán a través de una institución financiera
de propiedad del Instituto Ecuatoriano de Seguridad Social; su gestión se sujetará a los principios
de seguridad, solvencia, eficiencia, rentabilidad y al control del órgano competente''.

El artículo 54 de la Sección X: DEL BANCO DEL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL de la RESOLUCIÓN No. 385-2017-A CODIFICACIÓN DE RESOLUCIONES MONETARIAS, FINANCIERAS, DE VALORES Y SEGUROS de LA JUNTA DE POLÍTICA Y REGULACIÓN MONETARIA Y FINANCIERA, publicada en el Segundo Suplemento del Registro Oficial No.22 , de fecha 26 de Junio 2017, establece que se invertirán los valores del Fondo del \Sexpr{REP_seg} a mediano
plazo; es decir, a plazos de tres (3) a cinco (5) años, en inversiones: privativas (préstamos
prendarios y quirografarios), no privativas en renta fija (bonos, bonos locales, CETES
\footnote{Certificados de tesorería}, certificados de depósito, papel comercial, obligaciones,
titularizaciones y pólizas de acumulación) y no privativas en renta variable (fideicomisos
mercantiles: inversión, inmobiliarios y administración).

Para medir la rentabilidad de las inversiones, se utilizarán dos indicadores: el rendimiento
promedio ponderado y el rendimiento neto. El rendimiento promedio ponderado para cada instrumento
financiero, con pesos iguales a los saldos en valor nominal, se calcula según el artículo 5.4.1.3
del Capítulo III ``Manual operativo para valoración a precios de mercado de valores de contenido
crediticio y de participación y procedimiento'' del Título III ``De las operaciones del Instituto
Ecuatoriano de Seguridad Social, del Instituto de Seguridad Social de las Fuerzas Armadas, del
Instituto de Seguridad Social de la Policía Nacional, del Servicio de Cesantía de la Policía
Nacional'' del  Libro II ``Normas de control para las entidades del sistema de seguridad
social''\footnote{La normativa citada se encuentra derogada, pero se encontraba vigente en la
mayoría del período de valuación.}, en el cual manifiesta que la fórmula para calcular el
rendimiento efectivo promedio ponderado, $\overline{TIR}$, es:
\begin{equation}
\overline{TIR}=\frac{\sum^{K}_{1} TIR_{i}\cdot VP_{i}}{\sum^{k}_{1}VP_{i}},
\end{equation}

donde: $TIR_{i}$ es el rendimiento efectivo de la operación de contado $i$, $VP_{i}$ es el valor
nominal residual o valor parcial de la inversión y $k$ es el número de operaciones a tener en
cuenta.

El rendimiento neto de cada fondo se calcula según la metodología expuesta en el informe ``Cálculo
de rendimientos financieros de los Fondos Previsionales administrados por el Banco del Instituto
Ecuatoriano de Seguridad Social''. El rendimiento neto, $R_{i}$, del fondo $i$, se estiman a través
de la siguiente fórmula:
\begin{equation}
R_{i}=\frac{\left(I_{i}-Gop_{i}-GAdm_{i}\right)\cdot \left(12/j\right)}{\overline{FA_{i}}}, \qquad
para\; \; i=1,2,3,\ldots,9,
\end{equation}
donde: $I_{t}$ es el ingreso acumulado del fondo $i$, $Gop_{t}$ es el gasto operativo acumulado del
fondo $i$, $GAdm_{i}$ es el Gasto administrativo acumulado del fondo $i$ y $\overline{FA_{i}}$ es el
fondo administrativo promedio del fondo $i$.

$\overline{FA_{i}}$ hace referencia al promedio del saldo del fondo registrado el último día de cada
mes, desde el 31 de diciembre del año anterior hasta el último día del mes considerando para el
cálculo. Específicamente, la fórmula  de cálculo es la siguiente:
\begin{equation}
\overline{FA_{i}}=\frac{FA_{i,dic}+FA_{i,ene}+FA_{i,feb}+FA_{i,mar}+\cdots+FA_{i,actual}}{j+1},
\end{equation} donde: $j+1$ es el número total de observaciones para ser consideradas en el promedio móvil del
fondo administrado.

A partir de la información recopilada de los siguientes documentos: memorando Nro.
IESS-DNGF-2018-0859-M de 2 de octubre de 2018, oficio Nro. BIESS-OF-GGEN-0315-2019, de fecha 28 de
marzo de 2019, y oficio  Nro. BIESS-GGEN-2021-1165-OF, de fecha 08 de septiembre de 2021, se
presenta la siguiente información respecto a los fondos y reservas del \Sexpr{REP_seg}.

A continuación, se presenta la evolución histórica del valor nominal y su respectivo rendimiento del
portafolio de inversiones del \Sexpr{REP_seg}, durante el período 2011 a 2020 en la tabla
\ref{tab:iess_total_inv} y la figura \ref{fig:iess_evol_hist_inver_valor_nominal_rtr}.


\begin{figure}[H]
\centering
\caption{Evolución histórica del portafolio total de inversiones del \Sexpr{REP_seg} con su rendimiento durante el período 2011 a 2020}
\label{fig:iess_evol_hist_inver_valor_nominal_rtr}
\includegraphics[scale=0.7]{graficos/inv_total_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión del BIESS. \\
\textbf{Elaborado:} DAIE.}
\end{figure}

\begin{table}[H]
\begingroup\scriptsize\centering
\setlength\extrarowheight{3pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering, width=1\textwidth}
\caption{Evolución de los Fondos del \Sexpr{REP_seg} administrados por el BIESS}
\label{tab:iess_total_inv}
  {\fontsize{8}{8}\selectfont

  \arrayrulecolor{black}
  \begin{tabular}{R{0.8cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}
                  R{1.6cm}!{\color{white}\vrule}
                  R{1.6cm}!{\color{white}\vrule}
                  R{1.6cm}!{\color{white}\vrule}
                  R{1.6cm}}
\toprule \rowcolor{iess_green!60}
\parbox{0.8cm}{\centering Año }
& Inversiones (USD)
& Caja (USD)
& Fondo total administrado (USD)
& Rendimiento Promedio Ponderado (\%)
& Rendimiento Neto (\%)
& Rendimiento Neto Real (\%)
& Plazo Promedio Ponderado (días) \\
\arrayrulecolor{black}\midrule
\input{tablas/iess_total_inv.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión - BIESS y Dirección de Tesorería - BIESS. \\
\textbf{Elaborado:} DAIE.}
\endgroup
\end{table}


Los fondos administrados por el BIESS del \Sexpr{REP_seg} han tendido a crecer de USD 534.045.855,60 a USD 1.066.142.805,89, entre el año 2015 a 2020, lo que representa un crecimiento igual al 99,64\% en 5 años. El rendimiento neto de las inversiones de este seguro registró, en promedio, 8,47\% (período 2012 a 2020), con una baja volatilidad (1,11\% de desviación estándar); alcanzado su máximo en 2012 (10,84\%) y su mínimo en 2016 (7,14\%). En cambio, en valores, el saldo de las inversiones a diciembre promedió USD 633.029.592,37 durante los años 2011 a 2020.

Al 31 de diciembre de 2020, se registró, en valor nominal, USD 1.066.142.805,89 en los fondos administrados por el BIESSS del \Sexpr{REP_seg}, de los cuales USD 918.989.566,30 se encuentran invertidos en bonos del Estado, obligaciones, préstamos quirografarios y fidecomisos (ver tabla \ref{tab:iess_INV_Corte}) y USD 147.153.239,59 están en la caja para libre disponibilidad para el pago de prestaciones. El portafolio de inversiones registra un rendimiento neto igual 8,73\% a plazo promedio de 1.030 días.

En la tabla \ref{tab:iess_INV_Corte}, se presenta el portafolio de inversiones pertenecientes al \Sexpr{REP_seg}, a través del BIESS, mostrando su saldo remanente de la inversión en valor nominal, su rendimiento promedio ponderado y su rendimiento promedio ponderado real al 31 de diciembre de 2020.


\begin{table}[H]
\begingroup\scriptsize\centering
\setlength\extrarowheight{3pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{Portafolio de inversiones del Fondo del \Sexpr{REP_seg} administrados del BIESS a corte 31 de diciembre de 2020}
\label{tab:iess_INV_Corte}
{\fontsize{8}{8}\selectfont
\arrayrulecolor{black}
\begin{tabular}{R{5cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}
                  R{1.6cm}}
\toprule \rowcolor{iess_green!60}
Instrumento:
& Saldo Valor Nominal (USD)  
& Rendimiento Promedio Ponderado (\%)  
& Rendimiento Promedio Ponderado Real (\%) 
& Plazo Promedio Remanente (días)\\
\arrayrulecolor{black}\midrule
\input{tablas/iess_inv_corte.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión - BIESS y Dirección de Tesorería - BIESS. \\
\textbf{Elaborado:} DAIE.}
\endgroup
\end{table}

% --------------------------------------------------------------------------------------------------
\subsection{Rendimiento neto de las inversiones del fondo}

El Mgs. Diego Fernando Burneo Aguirre, Gerente General del BIESS, de la época, envió a través del Oficio Nro. BIESS-GGEN-2021-0152-OF, de fecha 08 de febrero de 2021 los resultados de la metodología: ``Cálculo de rendimientos financieros de los Fondos Previsionales administrados por el Banco del Instituto Ecuatoriano de Seguridad Social''.
Para el cálculo de los rendimientos netos, se utilizaron: los ingresos, gastos operativos y gastos administrativos, el fondo administrado promedio (desde diciembre del año anterior). Además, en la tabla \ref{tab:iess_rend_inv}, se presentan la tasa de rendimiento bruta antes de gastos y la tasa de rendimiento neta, la cual es el rendimiento después de gastos. Los ingresos se detallan más tarde en la tabla \ref{tab:iess_ingre_inv} y los egresos en la tabla \ref{tab:iess_gastos_inv}.

En 2020, los fondos administrados por el BIESS del \Sexpr{REP_seg} registraron ingresos por USD 93.033.262,64 y egresos operativos por USD 8.386.698,14, lo que representa un rendimiento bruto igual a 9,59\%, antes de egresos, y un rendimiento neto igual a 8,73\%, después de egresos. Cabe indicar que para el año 2020 el BIESS no ha incluido en los gastos administrativos en el cálculo de los rendimientos netos.

\begin{table}[H]
\begingroup\scriptsize\centering
\setlength\extrarowheight{3pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering, width=1\textwidth}
\caption{Evolución de los ingresos, gastos operativos, gastos administrativos, rendimiento bruto y
rendimiento neto del portafolio de inversiones del Fondo del \Sexpr{REP_seg}}
\label{tab:iess_rend_inv}
{\fontsize{9}{9}\selectfont
\arrayrulecolor{black}
\begin{tabular}{R{1.8cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}
                  R{1.8cm}!{\color{white}\vrule}
                  R{1.8cm}}
\toprule \rowcolor{iess_green!60}
Corte a:
& Ingresos (USD)  
& Gastos Operativos (USD)  
& Gastos Administrativos (USD)
& Fondo Administrado Promedio (USD)
& Rendimiento Bruto (\%)
& Rendimiento Neto (\%)\\
\arrayrulecolor{black}\midrule
\input{tablas/iess_rend_inv.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión - BIESS y Dirección de Tesorería - BIESS. \\
\textbf{Elaborado:} DAIE.}
\endgroup
\end{table}



En promedio, la diferencia entre rendimientos brutos y netos de este fondo es 0,95\%; es decir, los gastos (operativos y administrativos) producen una reducción del 0,95\% del rendimiento bruto y, además, presentan una baja volatilidad (desviación estándar igual a 2,50\%).

Los ingresos por inversiones del Fondo del \Sexpr{REP_seg}, presentados en la tabla \ref{tab:iess_ingre_inv}, fueron tomados de los estados de pérdidas y ganancias a corte diciembre de los respectivos años. Los ingresos financieros generados por las inversiones de este seguro generaron ingresos por USD 60.338.060,24 en promedio durante cada año entre 2012 y 2018, siendo el año 2018 con USD 76.146.502,37, el cual registra mayores ingresos; en cambio, solo obtuvieron beneficios 45.282.121,42 en el año 2016. En el año 2020, las inversiones en préstamos quirografarios generaron mayores ingresos por USD 51.252.059,92; y, en segundo lugar, los bonos del Estado con USD 22,331.482,99. En cambio las inversiones en renta fija del sector privado (obligaciones) solo generaron USD 52.337,57.


\girarpagina

\begin{table}[H]
\begingroup\scriptsize\centering
\setlength\extrarowheight{3pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{Evolución de los ingresos financieros generados por las inversiones del Fondo del \Sexpr{REP_seg}}
\label{tab:iess_ingre_inv}
{\fontsize{8}{8}\selectfont
\arrayrulecolor{black}
\begin{tabular}{R{4cm}!{\color{white}\vrule}
                  R{1.8cm}!{\color{white}\vrule}
                  R{1.8cm}!{\color{white}\vrule}
                  R{1.8cm}!{\color{white}\vrule}
                  R{1.8cm}!{\color{white}\vrule}
                  R{1.8cm}!{\color{white}\vrule}
                  R{1.8cm}!{\color{white}\vrule}
                  R{1.8cm}!{\color{white}\vrule}
                  R{1.8cm}!{\color{white}\vrule}
                  R{1.8cm}}
\toprule \rowcolor{iess_green!60}
Ingresos
& 2012
& 2013
& 2014
& 2015
& 2016
& 2017
& 2018
& 2019
& 2020\\
\arrayrulecolor{black}\midrule
\input{tablas/iess_ingre_inv.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión - BIESS y Dirección de Tesorería - BIESS. \\
\textbf{Elaborado:} DAIE.}
\endgroup
\end{table}

\begin{table}[H]
\begingroup\scriptsize\centering
\setlength\extrarowheight{3pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{Evolución de los gastos operativos producidos por las inversiones del Fondo del \Sexpr{REP_seg}}
\label{tab:iess_gastos_inv}
{\fontsize{7}{7}\selectfont
\arrayrulecolor{black}
\begin{tabular}{R{7.5cm}!{\color{white}\vrule}
                  R{1.4cm}!{\color{white}\vrule}
                  R{1.4cm}!{\color{white}\vrule}
                  R{1.4cm}!{\color{white}\vrule}
                  R{1.4cm}!{\color{white}\vrule}
                  R{1.4cm}!{\color{white}\vrule}
                  R{1.4cm}!{\color{white}\vrule}
                  R{1.4cm}!{\color{white}\vrule}
                  R{1.4cm}!{\color{white}\vrule}
                  R{1.4cm}}
\toprule \rowcolor{iess_green!60}
Gastos
& 2012
& 2013
& 2014
& 2015
& 2016
& 2017
& 2018
& 2019
& 2020\\
\arrayrulecolor{black}\midrule
\input{tablas/iess_gastos_inv.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión - BIESS y Dirección de Tesorería - BIESS. \\
\textbf{Elaborado:} DAIE.}
\endgroup
\end{table}

\regresargirar

Los gastos operativos de las inversiones del portafolio de inversiones del Fondo del \Sexpr{REP_seg} se detallan en la tabla \ref{tab:iess_gastos_inv}. Para el año 2020, se registraron USD 8.386.698,14 por gastos operativos del Fondo, de los cuales USD 4.464.017,50 (53,23\%) fueron por intereses acumulados en ejercicios anteriores; USD 1.587.650,34 (18,93\%) en provisiones de los créditos quirografarios y USD 1.140.429,73 (13,60\%). en valuaciones de inversiones en renta fija. Los gastos operativos promediaron USD 8.286.107,65 en el período 2012 a 2020, alcanzando su máximo en 2013 (USD 12.484.861,27) y su mínimo en 2017 (USD 1.737.623,76).

% --------------------------------------------------------------------------------------------------
\subsection{Inversiones privativas (préstamos)}
De acuerdo con la Sección X: DEL BANCO DEL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL de la Resolución No. 385-2017-A: CODIFICACIÓN DE RESOLUCIONES MONETARIAS, FINANCIERAS, DE VALORES Y SEGUROS DE LA JUNTA DE POLÍTICA Y REGULACIÓN MONETARIA Y FINANCIERA, publicada en el Segundo Suplemento del Registro Oficial No.22, de fecha 26 de Junio 2017, el Fondo del \Sexpr{REP_seg} se invertirá a mediano plazo (de más de tres (3) a cinco (5) años) y sus inversiones privativas abarcan: préstamos hipotecarios; préstamos quirografarios y préstamos prendarios a través de los servicios de los montes de piedad.

A pesar de que la normativa vigente, antes citada, el Fondo de este seguro solo dispone inversiones en créditos quirografarios (USD 452.002.382,53), con un rendimiento promedio ponderado igual a 13,01\% y a un plazo promedio de 1.190 días, al 31 de diciembre de 2020. En la tabla \ref{tab:iess_creditos_inv}, se muestra la evolución histórica de las inversiones en préstamos quirografarios en valor nominal con su respectivo rendimiento y plazo promedio ponderado durante el período 2012 a 2020.

\begin{table}[H]
\begingroup\scriptsize\centering
\setlength\extrarowheight{3pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{Evolución de las inversiones del Fondo del \Sexpr{REP_seg} en préstamos}
\label{tab:iess_creditos_inv}
{\fontsize{10}{12}\selectfont
\arrayrulecolor{black}
\begin{tabular}{R{0.8cm}!{\color{white}\vrule}
                  R{3cm}!{\color{white}\vrule}
                  R{3cm}!{\color{white}\vrule}
                  R{3cm}!{\color{white}\vrule}
                  R{1.6cm}}
\toprule \rowcolor{iess_green!60}
\parbox{0.8cm}{ Año }
& Saldo Valor Nominal (USD)  
& Rendimiento Promedio Ponderado (\%)  
& Rendimiento Promedio Ponderado Real (\%) 
& Plazo (días)\\
\arrayrulecolor{black}\midrule
\input{tablas/iess_creditos_inv.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión - BIESS y Dirección de Tesorería - BIESS. \\
\textbf{Elaborado:} DAIE.}
\endgroup
\end{table}


La cartera de los créditos quirografarios generó ingresos por USD 62.063.643,36 y egresos por provisiones solo por USD 1.587.650,34, debido a su baja cartera vencida de USD 1.418.892,81, durante el año 2020. Además, la cartera de créditos quirografarios aumentó de USD 375.168.830,18 a USD 452.002.382,53 entre 2019 y 2020, lo que representa un crecimiento igual a 20,48\%, durante el último año. En cambio, su tasa de rendimiento promedio ponderado se redujo de 13,12\% a 13,01\%, durante el mismo período de tiempo.
% --------------------------------------------------------------------------------------------------
\subsection{Inversiones no privativas con renta fija en el sector público}

De acuerdo con la Sección X: DEL BANCO DEL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL de la Resolución No. 385-2017-A: CODIFICACIÓN DE RESOLUCIONES MONETARIAS, FINANCIERAS, DE VALORES Y SEGUROS DE LA JUNTA DE POLÍTICA Y REGULACIÓN MONETARIA Y FINANCIERA, publicada en el Segundo Suplemento del Registro Oficial No.22, de fecha 26 de Junio 2017, el Fondo del \Sexpr{REP_seg} se invertirá a mediano plazo (de más de tres (3) a cinco (5) años) y sus inversiones no privativas en renta fija en el sector público abarcan: Bonos del Estado, Certificados de depósitos y Certificados de tesorería.

% --------------------------------------------------------------------------------------------------
\subsubsection{Inversiones en bonos del Estado}

El portafolio del Fondo del \Sexpr{REP_seg} registra inversiones en bonos del Estado por USD 372.587.637,56, con un rendimiento promedio ponderado igual a 7,16\% a un plazo promedio igual a 1.435 días, al corte de 31 de diciembre de 2020. Las inversiones en Bonos del Estado han crecido en 22,69\% respecto al año 2017 (USD 303.684.499,54). Por otro lado, la tasa de rendimiento promedio ponderado de las inversiones en Bonos del Estado registra 8,17\%, en promedio, durante el período 2011 a 2020; y con un plazo en promedio igual a 1.355,45 días, para el mismo período. En la tabla \ref{tab:iess_bonos_detalle_inv_ssc} se muestra la evolución histórica de las inversiones del \Sexpr{REP_seg} en bonos del Estado, en valor nominal (barras) a diciembre de cada año y sus tasas de rendimiento (líneas) durante el período 2011 a 2020.

\begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
{\fontsize{8}{8}\selectfont
\arrayrulecolor{black}
\begin{longtable}[H]{ R{2.3cm}!{\color{white}\vrule}
                      R{1.5cm}!{\color{white}\vrule}
                      R{1.8cm}!{\color{white}\vrule}
                      R{1.5cm}!{\color{white}\vrule}
                      R{1.5cm}!{\color{white}\vrule}
                      R{1.8cm}!{\color{white}\vrule}
                      R{3.6cm}}
\captionsetup{justification=centering}
\caption{Detalle de las inversiones del Fondo del \Sexpr{REP_seg} en bonos del Estado al 31 de diciembre de 2020} 
\label{tab:iess_bonos_detalle_inv_ssc} \\
\toprule \rowcolor{iess_green!60}
Emisor
& Valor Nominal de Compra (USD)
& Saldo Valor Nominal (USD)
& Tasa Cupón (\%)
& Plazo Permanente (días)
& Amortización
& Observación \\
\arrayrulecolor{black}
\midrule
\endfirsthead

\toprule\rowcolor{iess_green!60}
Emisor
& Valor Nominal de Compra (USD)
& Saldo Valor Nominal (USD)
& Tasa Cupón (\%)
& Plazo Permanente (días)
& Amortización
& Observación \\
\arrayrulecolor{black}
\midrule
\endhead

\bottomrule
\multicolumn{7}{r}{continúa...} \\
\endfoot
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión - BIESS y Balances Financieros del BIESS. \\
\textbf{Elaborado:} DAIE.}
\endlastfoot
\input{tablas/iess_bonos_detalle_inv.tex}
\end{longtable}
}
\endgroup



\paragraph{Recuperación de Bonos del Estado}

A la fecha de corte de este estudio, el Fondo del \Sexpr{REP_seg} dispone de USD 372.587.637,56 invertidos en Bonos del Estado, por los cuales se recibirán USD 71.903.659,96 por interés entre el año 2021 a 2027. A continuación, en la tabla \ref{tab:iess_resumen_recup_bonos_inv} se resumen la recuperación del capital e intereses por año.

% 
% {\fontsize{9}{10}\selectfont
% \begin{longtable}[H]{llccrr}
% \caption{Recuperación de las inversiones del Fondo del \Sexpr{REP_seg} en bonos del Estado al 31
% de diciembre de 2020} \\
% \label{tab:iess_recup_bonos_inv} \\
% \toprule
% \multicolumn{1}{l}{Referencia del} & 
% \multicolumn{1}{c}{Emisor} &
% \multicolumn{1}{c}{Fecha Cupón} &
% \multicolumn{1}{c}{Fecha Vencimiento} &
% \multicolumn{1}{c}{Recuperación del capital}  &  
% \multicolumn{1}{c}{Interés recibido}\\
% 
% \multicolumn{1}{c}{Título}  &
% &
% &
% &
% \multicolumn{1}{c}{(USD)}& 
% \multicolumn{1}{c}{(USD)}\\
% \midrule
% \endfirsthead
% 
% \toprule
% \multicolumn{1}{l}{Referencia del} & 
% \multicolumn{1}{c}{Emisor} &
% \multicolumn{1}{c}{Fecha Cupón} &
% \multicolumn{1}{c}{Fecha Vencimiento} &
% \multicolumn{1}{c}{Recuperación del capital}  &  
% \multicolumn{1}{c}{Interés recibido}\\
% 
% \multicolumn{1}{c}{Título}  &
% &
% &
% &
% \multicolumn{1}{c}{(USD)}& 
% \multicolumn{1}{c}{(USD)}\\
% 
% \midrule
% \endhead
% \bottomrule \multicolumn{6}{c}{continúa...} \\
% \endfoot
% %\bottomrule
% \caption*{\scriptsize Fuente: Subgerencia de Banca de Inversión del BIESS. \\
% Elaborado: DAIE.}
% \endlastfoot
% \input{tablas/iess_recup_bonos_inv.tex}
% \end{longtable}
% }

\begin{table}[H]
\begingroup\scriptsize\centering
\setlength\extrarowheight{3pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{Recuperación de las inversiones del Fondo del \Sexpr{REP_seg} en bonos del Estado al 31 de diciembre de 2020} 
\label{tab:iess_resumen_recup_bonos_inv} 
{\fontsize{7}{7}\selectfont
\arrayrulecolor{black}
\begin{tabular}{R{0.8cm}!{\color{white}\vrule}
                  R{3cm}!{\color{white}\vrule}
                  R{3cm}!{\color{white}\vrule}
                  R{3cm}}
\toprule \rowcolor{iess_green!60}
\parbox{0.8cm}{ Año }
& Saldo Valor Nominal (USD)  
& Rendimiento Promedio Ponderado (\%)
& Plazo (días)\\
\arrayrulecolor{black}\midrule
\input{tablas/iess_resumen_recup_bonos_inv.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión - BIESS \\
\textbf{Elaborado:} DAIE.}
\endgroup
\end{table}

% --------------------------------------------------------------------------------------------------
\subsection{Inversiones no privativas con renta fija en el sector privado}
   
% --------------------------------------------------------------------------------------------------
\subsubsection{Inversiones en Obligaciones en renta fija}

En la tabla \ref{tab:iess_obligaciones_hist_inv} se muestra la evolución histórica del
saldo remanente de las inversiones en obligaciones en renta fija (barras), en valor nominal, y sus
rendimientos (líneas) durante el período 2011 a 2020.
\begin{figure}[H]
\centering
\caption{Evolución histórica de las inversiones del \Sexpr{REP_seg} en Obligaciones y su rendimiento durante el período 2011 a 2020.}
\label{fig:iess_inversiones_obligaciones_rtr}
\includegraphics[width=0.60\textwidth]{graficos/iess_inv_obligaciones_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión del BIESS.
\\ \textbf{Elaborado: }DAIE.}
\end{figure}

\begin{table}[H]
\begingroup\scriptsize\centering
\setlength\extrarowheight{3pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{Evolución de las inversiones del Fondo del \Sexpr{REP_seg} en Obligaciones en renta fija}
\label{tab:iess_obligaciones_hist_inv}
{\fontsize{10}{12}\selectfont
\arrayrulecolor{black}
\begin{tabular}{R{0.8cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{3cm}!{\color{white}\vrule}
                  R{2.5cm}}
\toprule \rowcolor{iess_green!60}
Año
& Saldo Valor Nominal (USD)  
& Rendimiento Promedio Ponderado (\%)  
& Rendimiento Promedio Ponderado Real (\%) 
& Plazo (días)\\
\arrayrulecolor{black}\midrule
\input{tablas/iess_obligaciones_hist_inv.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión - BIESS  \\
\textbf{Elaborado:} DAIE.}
\endgroup
\end{table}



El saldo en valor nominal decreció de USD 13.111.109,98 a diciembre de 2013 a USD 1.107.776,50 en
diciembre de 2018, año en el cual obtuvo su mínimo valor invertido. Por último, la tasa de
rendimiento promedio ponderada decreció de 9,09\% en 2011 a 8,31\% en el año 2018. El portafolio de
inversiones en obligaciones en renta fija al corte (diciembre de 2020) se muestra el valor nominal
de compra de estos bonos corporativos, el nombre del emisor, el saldo remanente, la tasa de cupón
anual y el plazo remanente en días en la tabla \ref{tab:iess_oblig_detalle_inv}.


\begingroup\scriptsize\centering
\setlength\extrarowheight{1pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
{\fontsize{8}{9}\selectfont
\arrayrulecolor{black}
\begin{longtable}[H]{ R{7cm}!{\color{white}\vrule}
                      R{1.5cm}!{\color{white}\vrule}
                      R{1.8cm}!{\color{white}\vrule}
                      R{1cm}!{\color{white}\vrule}
                      R{1.5cm}!{\color{white}\vrule}
                      R{1.8cm}}
\captionsetup{justification=centering}
\caption{Detalle de las inversiones del Fondo del \Sexpr{REP_seg} en obligaciones en renta fija al 31
de diciembre de 2020}
\label{tab:iess_oblig_detalle_inv}\\
\toprule \rowcolor{iess_green!60}
Emisor
& Valor Nominal de Compra (USD)
& Saldo Valor Nominal (USD)
& Tasa Cupón (\%)
& Plazo Permanente (días)
& Amortización\\
\arrayrulecolor{black}
\midrule
\endfirsthead

\toprule\rowcolor{iess_green!60}
Emisor
& Valor Nominal de Compra (USD)
& Saldo Valor Nominal (USD)
& Tasa Cupón (\%)
& Plazo Permanente (días)
& Amortización\\
\arrayrulecolor{black}
\midrule
\endhead

\bottomrule
\multicolumn{6}{r}{continúa...} \\
\endfoot
\bottomrule
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión - BIESS \\
\textbf{Elaborado:} DAIE.}
\endlastfoot
\input tablas/iess_oblig_detalle_inv.tex
\end{longtable}
}
\endgroup


El portafolio de inversiones de este seguro solo se compone de bonos corporativos a renta fija de
dos empresas en USD 1.107.776,50, lo cual no es representativo para el tamaño del portafolio de
inversiones de este fondo; pero a la vez estas obligaciones tienen altos rendimientos y no están
sujetas a la volatilidad generada por la especulación del mercado de valores, como lo que sucede en
las inversiones de renta variable.

% --------------------------------------------------------------------------------------------------
\subsubsection{Inversiones en Titularizaciones}

La Titularización es un mecanismo de financiamiento que consiste en: transformar activos o bienes, actuales o futuros, en valores negociables en el Mercado de Valores, para obtener liquidez en condiciones competitivas de mercado, con la consecuente reducción de los costos financieros.

En la figura \ref{fig:iess_inversiones_titulos_financieros_rtr} y la tabla \ref{tab:iess_titularizaciones_hist_inv}, se muestra la evolución histórica del saldo (barras), en valor nominal, de las inversiones del Fondo del \Sexpr{REP_seg} en titularizaciones al 31 diciembre de cada año y su rendimiento promedio ponderado (líneas) durante el período 2011 a 2020.
\begin{figure}[H]
\centering
\caption{Evolución histórica de las inversiones del \Sexpr{REP_seg} en títulos financieros y su rendimiento durante el período 2011 a 2020}
\label{fig:iess_inversiones_titulos_financieros_rtr}
\includegraphics[width=0.60\textwidth]{graficos/iess_inv_titularizaciones_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión del BIESS.
\\ \textbf{Elaborado:} DAIE.}
\end{figure}


Las inversiones en titularizaciones decrecieron desde 2011 (USD 39.506.331,20) hasta USD 6.541.027,10 en 2014, para luego desaparecer durante los años 2015 a 2019. Al 31 de diciembre de 2020, se registró una inversión en Valores de Titularización en la Cartera de CARTIMEX por un valor de compra de USD  1.780.000,00, con saldo remanente por USD  970.100,00, a un plazo de 435 días, con tasa de rendimiento igual a 8,5\%.

\begin{table}[H]
\begingroup\scriptsize\centering
\setlength\extrarowheight{3pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{Evolución de las inversiones del Fondo del \Sexpr{REP_seg} en titularizaciones en renta fija}
\label{tab:iess_titularizaciones_hist_inv}
{\fontsize{9}{9}\selectfont
\arrayrulecolor{black}
\begin{tabular}{R{0.8cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{3cm}!{\color{white}\vrule}
                  R{2.5cm}}
\toprule \rowcolor{iess_green!60}
Año
& Saldo (USD)  
& Rendimiento Promedio Ponderado (\%)  
& Rendimiento Promedio Ponderado Real (\%) 
& Plazo (días)\\
\arrayrulecolor{black}\midrule
\input{tablas/iess_titularizaciones_hist_inv.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión - BIESS  \\
\textbf{Elaborado:} DAIE.}
\endgroup
\end{table}



% --------------------------------------------------------------------------------------------------
\subsection{Inversiones no privativas con renta variable}

La renta variable es un tipo de inversión formada por todos aquellos activos financieros en los que
la rentabilidad es incierta. Es decir, la rentabilidad no está garantizada ni la devolución del
capital invertido ni la rentabilidad del activo. En la renta variable, al contrario que en la renta
fija, no conocemos los flujos de caja que vamos a recibir por parte de la empresa. Incluso, puede
que la rentabilidad sea negativa.

Las inversiones no privativas en renta variable del Fondo del \Sexpr{REP_seg} pueden realizar las
siguientes operaciones en fideicomisos mercantiles de inversión, inmobiliarios y  administración de
acciones de cuotas  de  participación  en fondos de inversión.

% --------------------------------------------------------------------------------------------------
\subsubsection{Inversiones en fideicomisos y negocios fiduciarios}

% Se entiende por fideicomiso mercantil el contrato por el cual una o más personas llamadas
% constituyentes o fideicomitentes transfieren, de manera temporal e irrevocable, la propiedad de
% bienes muebles o inmuebles corporales o incorporales, que existen o se espera que existan, a un
% patrimonio autónomo, dotado de personalidad jurídica para que la sociedad administradora de fondos
% y fideicomisos, que es su fiduciaria y en tal calidad su representante legal, cumpla con las
% finalidades específicas instituidas en el contrato de constitución, bien en favor del propio
% constituyente o de un tercero llamado beneficiario.  En términos legales LA FIDUCIA MERCANTIL es
% definida como ``un negocio jurídico en virtud de la cual una persona, llamada fiduciante o
% fideicomiso, transmite uno o más bienes especificados a otra, llamado fiduciario, quien se obliga
% a administrarlos o enajenarlos para cumplir una finalidad determinada por el constituyente, en
% provecho de este o de un tercero llamado beneficiario o fideicomisario''.

En la figura \ref{fig:iess_inv_fidecomisos_ssc} y la tabla \ref{tab:iess_fidecomisos_hist_inv}, se
muestra la evolución histórica de las inversiones en fideicomisos y negocios fiduciarios, en valor
nominal, registrados en el portafolio de inversiones del Fondo del \Sexpr{REP_seg} y su rendimiento
promedio ponderado durante el período 2011 a 2020, a diciembre de cada año.

\begin{table}[H]
\begingroup\scriptsize\centering
\setlength\extrarowheight{3pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{Evolución de las inversiones del Fondo del \Sexpr{REP_seg} en fideicomisos y negocios fiduciarios}
\label{tab:iess_fidecomisos_hist_inv}
{\fontsize{9}{10}\selectfont
\arrayrulecolor{black}
\begin{tabular}{R{0.8cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{3.0cm}}
\toprule \rowcolor{iess_green!60}
Año
& Saldo Valor Nominal (USD)  
& Rendimiento Promedio Ponderado (\%)  
& Rendimiento Promedio Ponderado Real (\%) \\
\arrayrulecolor{black}\midrule
\input{tablas/iess_fidecomisos_hist_inv.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión - BIESS  \\
\textbf{Elaborado:} DAIE.}
\endgroup
\end{table}


\begin{figure}[H]
\centering
\caption{Evolución histórica del saldo remanente, en valor nominal, de las inversiones en fideicomisos y negocios fiduciarios del \Sexpr{REP_seg} y su rendimiento promedio ponderado}
\label{fig:iess_inv_fidecomisos_ssc}
\includegraphics[scale=0.75]{graficos/iess_inv_fidecomisos_ssc.png}
\caption*{\scriptsize \textbf{Fuente:} Subgerencia de Banca de Inversión - BIESS. \\
\textbf{Elaborado: }DAIE.}
\end{figure}

Las inversiones en fidecomisos representan USD 6.569.616,10 del portafolio de inversiones del Fondo del \Sexpr{REP_seg}, al 31 de diciembre de 2020. Para el mismo año, se registró una tasa de rendimiento promedio ponderado igual a 7,71\%. Solamente entre 2019 y 2020, se ha reducido en 48,00\% el valor nominal de las inversiones en fidecomisos y desde el año 2012, se ha reducido su saldo en 21,38\% por año, lo cual indica los claros esfuerzos del BIESS en deshacerse de estos tipos de inversiones, debido al alto número de fidecomisos paralizados.

% --------------------------------------------------------------------------------------------------
\subsection{Otras inversiones menores}
El portafolio del Fondo del \Sexpr{REP_seg} también posee otras inversiones, además de las expuestas
anteriormente que se enumeran a continuación:
\begin{enumerate}[label=\arabic*.,topsep=0pt,itemsep=1ex,parsep=1ex,partopsep=1ex]

\item Inversión en Papel Comercial en ENVASES DEL LITORAL S.A. por USD  500.000,00 a plazo de 4 días, al 31 de diciembre de
2020, con tasa cupón cero.

% \item Inversión en Valores de Titularización en la Cartera de CARTIMEX por un valor de compra de USD  1.780.000,00 
% , con saldo remanente por USD  970.100,00, a un plazo de 435 días, con tasa de rendimiento igual a 8,5\%, al 31 de diciembre de 2020.

\item Inversiones en Certificados de Tesorería (CETES) por USD 65.062.291,67 a un plazo de 22 días, con rendimiento igual al 1,50\%, al 31 de diciembre de 2020.

\end{enumerate}

%---------------------------------------------------------------------------------------------------
\section{Causas de desfinanciamiento}
\label{chp_infofinan:causasdesf}

En esta sección se presentan las principales causas de desfinanciamiento que sufrió el fondo desde el año 2012 hasta la fecha de corte del estudio, las cuales se describen a continuación:
\begin{enumerate}[itemsep=0mm, topsep=0pt]
\itemsep0em
\item La ausencia de la contribución del Estado al IESS por el financiamiento del 40\% de las pensiones y otras obligaciones que tiene el Estado con IESS por este seguro desde 2012 a 2020 es USD 536.623.678,28 (USD 423.144.977,05 capital y USD 113.478.701,23 lucro cesante).

\item Desinversiones realizadas desde junio de 2017 hasta la fecha corte del estudio (USD 276.800.000,00 ) a la fecha de corte no permitieron que el fondo reciba intereses por USD 163.713.771,56 (lucro cesante).
\end{enumerate}

En consecuencia, el impacto de estas causas de desfinanciamiento sobre el patrimonio de este fondo se resume en la tabla \ref{tab:impacto_patrimonio}:

\begin{table}[H]
\begingroup\scriptsize\centering
\setlength\extrarowheight{3pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{Impacto de la ausencia de la contribución del Estado y desinversiones}
\label{tab:impacto_patrimonio}
{\fontsize{10}{12}\selectfont
\arrayrulecolor{black}
\begin{tabular}{R{5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}}
\toprule \rowcolor{iess_green!60}
Concepto:
& Capital (USD)  
& Lucro Cesante (USD)  
& Total (USD) \\
\arrayrulecolor{black}\midrule
\input{tablas/iess_SSC_causas_desfinanciamiento_total.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize \textbf{Fuente:} DAIE y Balances Financieros del IESS. \\
\textbf{Elaborado:} DAIE.}
\endgroup
\end{table}

De no producirse los decrementos antes citados, el patrimonio al 31 de diciembre de 2020 debería incrementarse en USD 700.337.449,84. En las subsecciones \ref{chp_resultados:sin_contrib_estado} y \ref{tab:iess_desinvertido_anual}, se muestran a detalle los valores no percibidos por el Fondo del \Sexpr{REP_seg}.


\subsection{Deuda del Estado por falta del pago de sus obligaciones}
\label{chp_resultados:sin_contrib_estado}

Cabe mencionar que la deuda del gobierno está compuesta por la siguiente distribución:
\begin{itemize}
\setlength{\parskip}{0pt}
\setlength{\itemsep}{0pt plus 1pt}
\item 40\% Pensiones Invalidez
\item 40\% Pensiones Montepío
\item 40\% Pensiones Vejez
\item 0,30\% Contribución Seguro Social Campesino
\item Contribuciones Especiales
% \item Atención Médica a Jubilados
% \item Atención Médica Enfermedades Catastróficas
% \item Deuda Gobierno Consolidada
\end{itemize}

Por lo tanto, el crecimiento de la deuda del gobierno sigue en aumento, debido a la falta del pago por parte del Estado; el cual está suscrito en el ``Acta de consolidación provincial de la Contribución del Estado del 40\% para el pago de pensiones y otras obligaciones del Estado al Instituto Ecuatoriano de Seguridad Social IESS'', a través de la comisión Interinstitucional del Ministerio de Finanzas y el IESS, con fecha 23 de abril de 2012.

Para el registro de la Deuda del Estado de este Seguro Especializado, se cumple con la normativa y lineamientos emitidos por la Dirección Nacional de Gestión Financiera, dependencia que, a través de su proceso de Gestión Interna, la Subdirección Nacional de Supervisión de la Rentabilidad de los Fondos Previsionales, gestiona el cobro de la deuda del estado con el Ministerio de Finanzas.

\girarpagina

\begin{table}[H]
\begingroup\scriptsize\centering
\setlength\extrarowheight{3pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{Deuda del Gobierno de SSC}
\label{tab:iess_deuda_gob_ssc}
{\fontsize{10}{12}\selectfont
\arrayrulecolor{black}
\begin{tabular}{R{0.8cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}}
\toprule \rowcolor{iess_green!60}
Año
& 40 \% Pensiones Invalidez (USD)  
& 40 \% Pensiones Vejez (USD)   
& 0,30 \% Contribución SSC (USD)
& Contribuciones Especiales (USD)
& Total deuda (SSC)
& Tasa de rendimiento neto (\%)
& Lucro cesante (USD)
& Total deuda más lucro cesante (USD)\\
\arrayrulecolor{black}\midrule
\input{tablas/iess_SSC_deuda_estado_desf.tex}
\bottomrule 
\end{tabular}
}
\caption*{\scriptsize \textbf{Fuente:} Subdirección Nacional de Supervisión de la Rentabilidad de los Fondos Previsionales del IESS.\\
\textbf{Elaborado:} DAIE\\
\textbf{Nota:} No se consideran las atenciones médicas a jubilados y atenciones médicas de Enfermedades Catastróficas}
\endgroup
\end{table}


De los resultados presentados en la tabla \ref{tab:iess_deuda_gob_ssc}, se obtiene los montos adeudados por el Estado, por el período 2010 a 2020, que dejó de contribuir al \Sexpr{REP_seg} para el financiamiento de las prestaciones de este seguro.

Sin considerar las atenciones médicas a jubilados y atenciones médicas de Enfermedades Catastróficas, se estima que la deuda del Estado el Fondo del \Sexpr{REP_seg} es USD 423.144.977,05 de capital y USD 113.478.701,23 por rendimiento de estos valores, dando un total de USD 536.623.678,28. El cálculo se realiza aplicando la determinación de intereses en concordancia con el criterio de crecimiento de las reservas en los seguros, por el tiempo transcurrido desde 2012 a la fecha de corte, período en el cual los intereses se suman al capital al final de cada año y este forma un nuevo capital que sirve para determinar el nuevo valor del lucro cesante.


\regresargirar

% Para el registro de la Deuda del Estado de este Seguro Especializado, se cumple con la normativa y lineamientos emitidos por la Dirección Nacional de Gestión Financiera, dependencia que, a través de su proceso de Gestión Interna, la Subdirección Nacional de Supervisión de la Rentabilidad de los Fondos Previsionales, gestiona el cobro de la deuda del estado con el Ministerio de Finanzas.
% 
% De los resultados presentados en la tabla \ref{tab:iess_deuda_gob_ssc}, se obtiene los montos adeudados por el Estado, por el período 2010 a 2020, que dejó de contribuir al \Sexpr{REP_seg} para el financiamiento de las prestaciones de este seguro.

% Sin considerar las atenciones médicas a jubilados y atenciones médicas de Enfermedades Catastróficas, se estima que la deuda del Estado el Fondo del \Sexpr{REP_seg} es USD 423.144.977,05 de capital y USD 113.478.701,23 por rendimiento de estos valores, dando un total de USD 536.623.678,28. El cálculo se realiza aplicando la determinación de intereses en concordancia con el criterio de crecimiento de las reservas en los seguros, por el tiempo transcurrido desde 2012 a la fecha de corte, período en el cual los intereses se suman al capital al final de cada año y este forma un nuevo capital que sirve para determinar el nuevo valor del lucro cesante.



%---------------------------------------------------------------------------------------------------
\subsection{Desinversiones del portafolio de inversiones del Fondo del \Sexpr{REP_seg}}
\label{tab:iess_desinvertido_anual}

Para el cálculo del lucro cesante (ingresos financieros dejados de percibir por las desinversiones),
se emplearon las tasas de rendimiento neto según la metodología ``Cálculo de rendimientos
financieros de los Fondos Previsionales administrados por el Banco del Instituto Ecuatoriano de
Seguridad Social'' de la tabla \ref{tab:iess_rend_inv}. En primer lugar, se utiliza una tasa
equivalente mensual, puesto que las tasas de rendimiento netas $i_t$ son anuales al momento $t$ de
la inversión.
\begin{equation}
j_t = ( 1 + i_t )^{\frac{1}{12}} - 1
\end{equation}

Una vez obtenida la tasa de rendimiento equivalente mensual, se procede a calcular el lucro cesante,
suponiendo la capitalización mensual de los intereses a una tasa de rendimiento neta del
correspondiente año de la siguiente manera:
\begin{equation}
L_t = \left( \prod\limits_{k = 1}^{12} \left( 1 + j_{t + \frac{k}{12}} \right) - 1 \right) C_t
\end{equation}

Donde $L_t$ es el lucro cesante de la desinversión/inversión correspondiente tiempo $t$, medido en
años, $C_t$ es el capital desinvertido/invertido en el tiempo $t$; y $j_t$ es la  tasa de
rendimiento correspondiente al momento $t$. Las desinversiones del Fondo del \Sexpr{REP_seg} y el
cálculo de su lucro cesante, con la metodología expuesta anteriormente, se presentan en la tabla
\ref{tab:iess_RTR_desinversiones}.

\begin{table}[H]
\begingroup\scriptsize\centering
\setlength\extrarowheight{3pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{Monto desinvertido del Fondo del \Sexpr{REP_seg} y su lucro cesante}
\label{tab:iess_RTR_desinversiones} 
{\fontsize{10}{12}\selectfont
\arrayrulecolor{black}
\begin{tabular}{R{1.8cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}
                  R{1.5cm}!{\color{white}\vrule}
                  R{2cm}!{\color{white}\vrule}
                  R{2.5cm}}
\toprule \rowcolor{iess_green!60}
Fecha
& Capital desinvertido (USD)   
& Rentabilidad neta (\%)  
& Rentabilidad neta mensualizada (\%)
& Factor
& Lucro cesante (USD)
& Lucro cesante + capital desinvertido (USD)\\
\arrayrulecolor{black}\midrule
\input{tablas/iess_SSC_desinversiones.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize \textbf{Fuente:} Dirección de Tesorería-BIESS. \\
\textbf{Elaborado:} DAIE.}
\endgroup
\end{table}


Aplicando las suposiciones y metodología expuesta, se concluye que el monto desinvertido entre diciembre de 2013 a septiembre de 2020 es USD 276.800.000,00, por lo cual el IESS dejó de percibir USD 163.713.771,56 por lucro cesante por las desinversiones. En la siguiente tabla, se registra el capital desinvertido, lucro cesante y su total desinvertido entre los años 2013 y 2020 (ver tabla \ref{tab:iess_SSC_desinvertido_anual}).

\begin{table}[H]
\begingroup\scriptsize\centering
\setlength\extrarowheight{3pt}
\setlength\aboverulesep{-0.5pt}
\setlength\belowrulesep{0pt}
\captionsetup{justification=centering}
\caption{Capital desinvertido anual del Fondo del \Sexpr{REP_seg} y su lucro cesante}
\label{tab:iess_SSC_desinvertido_anual} 
{\fontsize{10}{12}\selectfont
\arrayrulecolor{black}
\begin{tabular}{R{2.3cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{2.5cm}!{\color{white}\vrule}
                  R{3cm}}
\toprule \rowcolor{iess_green!60}
Año
& Capital desinvertido (USD)
& Lucro cesante (USD)
& Lucro cesante + capital desinvertido (USD)\\
\arrayrulecolor{black}\midrule
\input{tablas/iess_SSC_desinversiones_anual.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize \textbf{Fuente:} Dirección de Tesorería-BIESS y DAIE \\
\textbf{Elaborado:} DAIE.}
\endgroup
\end{table}

Como se puede observar la dependencia de la contribución estatal es cada vez más representativa conforme avanza el horizonte de proyección; por tanto, la disminución o ausencia del pago de este rubro llevará al desfinanciamiento del Seguro Social Campesino.

Si el Seguro Social Campesino no registra contablemente la deuda por las atenciones médicas con el SGSIF y no adopta mecanismos de pago, esta deuda se incrementará afectando considerablemente a los dos fondos. De igual manera, se deben registrar adecuadamente las atenciones médicas a jubilados y enfermedades catastróficas. Otra posible causa de desfinanciamiento es no mantener niveles adecuados de rendimiento en inversiones del portafolio, el mismo que depende del comportamiento de la economía, la colocación y diversificación de las inversiones del portafolio. Los excedentes sobre el rendimiento esperado deben ser canalizados para mejorar servicios, beneficios y capitalizar aún más la reserva.
