message( paste( rep('-', 100 ), collapse = '' ) )
message( '\tGenerando tablas de parámetros escenarios' )

# Plantilla gráficos -------------------------------------------------------------------------------
source( 'R/des/511_tab_plantilla_modelos_des.R', encoding = 'UTF-8', echo = FALSE )

#Cargado Rdatas-------------------------------------------------------------------------------------
load( paste0( parametros$RData_seg, 'IESS_DES_alpha_modelo_beneficios.RData' ) )
load( paste0( parametros$RData_seg, 'IESS_DES_modelo_beneficios.RData' ) )

#Tabla de los coeficientes \alpha-------------------------------------------------------------------
aux<- mod_benficio_des
aux<-cbind(aux[1:5,],aux[6:10,])
aux<-aux[,-4]
aux<-select(aux,pago,mujer:=alpha,hombre:=alpha.1)
aux$pago<-c('$\\alpha_{1,g}$',
            '$\\alpha_{2,g}$',
            '$\\alpha_{3,g}$',
            '$\\alpha_{4,g}$',
            '$\\alpha_{5,g}$')
xtb_aux <- xtable( aux, digits = c( 0, 0, 4, 4) )

print( xtb_aux,
       file = paste0( parametros$resultado_tablas, 'iess_estimacion_pago_des' , '.tex' ),
       type = 'latex', 
       include.colnames = FALSE, include.rownames = FALSE, 
       format.args = list( decimal.mark = ',', big.mark = '.' ), 
       only.contents = TRUE, 
       hline.after = NULL,
       sanitize.text.function = function(x){x} )

#Tabla de los modelos de estimación del beneficio---------------------------------------------------

#Tabla del los modelos para hombres sin pagos indebidos---------------------------------------------
aux <- capture.output(stargazer(mod_p1_m,
          mod_p2_m,
          mod_p3_m,
          mod_p4_m,
          mod_p5_m,
          header=FALSE,
          se=list(NULL),
          dep.var.caption  = "Hombres",
          dep.var.labels.include = FALSE,
          column.labels=c("Pago 1","Pago 2","Pago 3","Pago 4","Pago 5"),
          covariate.labels = "70\\%\\;SBU",
          align=FALSE, 
          style = "all",
          decimal.mark = ",",
          digit.separator=".",
          nobs=FALSE,
          model.numbers=FALSE,
          df=FALSE,
          digits=5,
          digits.extra=3,
          keep.stat = c("ll"),
          table.layout ="-lc-t-s-a-",
          label = "tab:iess_mod_m_beneficios",
          title = "Estimaci\\'{o}n de los coeficientes $\\alpha_{i,2}$ del modelo de beneficios",
          #single.row=TRUE,
          notes.align = "l",
          #notes = "Nota:",
          #type = "text",
          add.lines=list(
                         c("Observaciones", 
                           format(nobs(mod_p1_m),nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(nobs(mod_p2_m),nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(nobs(mod_p3_m),nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(nobs(mod_p4_m),nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(nobs(mod_p5_m),nsmall =2,decimal.mark = ",",big.mark = ".")),
                         c("$AIC$",
                           format(AIC(mod_p1_m),nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(AIC(mod_p2_m),nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(AIC(mod_p3_m),nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(AIC(mod_p4_m),nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(AIC(mod_p5_m),nsmall =2,decimal.mark = ",",big.mark = ".")),
                         c("$R^{2}$",
                           format(summary(mod_p1_m)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(summary(mod_p2_m)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(summary(mod_p3_m)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(summary(mod_p4_m)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(summary(mod_p5_m)$r.squared,nsmall =2,decimal.mark = ",",big.mark = ".")),
                         c("$R^{2}$\\;ajustado",
                           format(summary(mod_p1_m)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(summary(mod_p2_m)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(summary(mod_p3_m)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(summary(mod_p4_m)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                           format(summary(mod_p5_m)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = ".")),
                         c("$F$ - estad\\'{i}stico",
                           paste0(format(anova(mod_p1_m)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                           paste0(format(anova(mod_p2_m)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                           paste0(format(anova(mod_p3_m)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                           paste0(format(anova(mod_p4_m)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                           paste0(format(anova(mod_p5_m)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"))
              )))
aux<-aux[c(3:(NROW(aux)-2))]
star_tex_write(aux,file = paste0( parametros$resultado_tablas, 'iess_mod_m_beneficios' , '.tex' ))

#Tabla del los modelos para mujeres sin pagos indebidos---------------------------------------------
aux <- capture.output(stargazer(mod_p1_f,
                mod_p2_f,
                mod_p3_f,
                mod_p4_f,
                mod_p5_f,
                header=FALSE,
                se=list(NULL),
                dep.var.caption  = "Mujeres",
                dep.var.labels.include = FALSE,
                column.labels=c("Pago 1","Pago 2","Pago 3","Pago 4","Pago 5"),
                covariate.labels = "70\\%\\;SBU",
                align=FALSE, 
                style = "all",
                decimal.mark = ",",
                digit.separator=".",
                nobs=FALSE,
                model.numbers=FALSE,
                df=FALSE,
                digits=5,
                digits.extra=3,
                keep.stat = c("ll"),
                table.layout ="-lc-t-s-a-",
                label = "tab:iess_mod_f_beneficios",
                title = "Estimaci\\'{o}n de los coeficientes $\\alpha_{i,1}$ del modelo de beneficios",
                #single.row=TRUE,
                notes.align = "l",
                #notes = "Nota:",
                #type = "text",
                add.lines=list(
                  c("Observaciones", 
                    format(nobs(mod_p1_f),nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(nobs(mod_p2_f),nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(nobs(mod_p3_f),nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(nobs(mod_p4_f),nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(nobs(mod_p5_f),nsmall =2,decimal.mark = ",",big.mark = ".")),
                  c("$AIC$", 
                    format(AIC(mod_p1_f),nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(AIC(mod_p2_f),nsmall =2,decimal.mark = ",",big.mark = "."), 
                    format(AIC(mod_p3_f),nsmall =2,decimal.mark = ",",big.mark = "."), 
                    format(AIC(mod_p4_f),nsmall =2,decimal.mark = ",",big.mark = "."), 
                    format(AIC(mod_p5_f),nsmall =2,decimal.mark = ",",big.mark = ".")),
                  c("$R^{2}$", 
                    format(summary(mod_p1_f)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_p2_f)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_p3_f)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_p4_f)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_p5_f)$r.squared,nsmall =2,decimal.mark = ",",big.mark = ".")),
                  c("$R^{2}$\\;ajustado", 
                    format(summary(mod_p1_f)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_p2_f)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_p3_f)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_p4_f)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_p5_f)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = ".")),
                  c("$F$ - estad\\'{i}stico", 
                    paste0(format(anova(mod_p1_f)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                    paste0(format(anova(mod_p2_f)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                    paste0(format(anova(mod_p3_f)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                    paste0(format(anova(mod_p4_f)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                    paste0(format(anova(mod_p5_f)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"))
                )))
aux<-aux[c(3:(NROW(aux)-2))]
star_tex_write(aux,file = paste0( parametros$resultado_tablas, 'iess_mod_f_beneficios' , '.tex' ))


#Tabla del los modelos para hombres con pagos indebidos---------------------------------------------
aux <- capture.output(stargazer(mod_ind_p1_m,
               mod_ind_p2_m,
               mod_ind_p3_m,
               mod_ind_p4_m,
               mod_ind_p5_m,
               header=FALSE,
               se=list(NULL),
               dep.var.caption  = "Hombres",
               dep.var.labels.include = FALSE,
               column.labels=c("Pago 1","Pago 2","Pago 3","Pago 4","Pago 5"),
               covariate.labels = "70\\%\\;SBU",
               align=FALSE, 
               style = "all",
               decimal.mark = ",",
               digit.separator=".",
               nobs=FALSE,
               model.numbers=FALSE,
               df=FALSE,
               digits=5,
               digits.extra=3,
               keep.stat = c("ll"),
               table.layout ="-lc-t-s-a-",
               label = "tab:iess_mod_m_beneficios_ind",
               title = "Estimaci\\'{o}n de los coeficientes $\\alpha_{i,2}$ del modelo de beneficios, con aporte patronal extempor\\'{a}neo",
               #single.row=TRUE,
               notes.align = "l",
               #notes = "Nota:",
               #type = "text",
               add.lines=list(
                 c("Observaciones", 
                   format(nobs(mod_ind_p1_m),nsmall =2,decimal.mark = ",",big.mark = "."),
                   format(nobs(mod_ind_p2_m),nsmall =2,decimal.mark = ",",big.mark = "."),
                   format(nobs(mod_ind_p3_m),nsmall =2,decimal.mark = ",",big.mark = "."),
                   format(nobs(mod_ind_p4_m),nsmall =2,decimal.mark = ",",big.mark = "."),
                   format(nobs(mod_ind_p5_m),nsmall =2,decimal.mark = ",",big.mark = ".")),
                 c("$AIC$", 
                   format(AIC(mod_ind_p1_m),nsmall =2,decimal.mark = ",",big.mark = "."),
                   format(AIC(mod_ind_p2_m),nsmall =2,decimal.mark = ",",big.mark = "."), 
                   format(AIC(mod_ind_p3_m),nsmall =2,decimal.mark = ",",big.mark = "."), 
                   format(AIC(mod_ind_p4_m),nsmall =2,decimal.mark = ",",big.mark = "."), 
                   format(AIC(mod_ind_p5_m),nsmall =2,decimal.mark = ",",big.mark = ".")),
                 c("$R^{2}$", 
                   format(summary(mod_ind_p1_m)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                   format(summary(mod_ind_p2_m)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                   format(summary(mod_ind_p3_m)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                   format(summary(mod_ind_p4_m)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                   format(summary(mod_ind_p5_m)$r.squared,nsmall =2,decimal.mark = ",",big.mark = ".")),
                 c("$R^{2}$\\;ajustado", 
                   format(summary(mod_ind_p1_m)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                   format(summary(mod_ind_p2_m)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                   format(summary(mod_ind_p3_m)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                   format(summary(mod_ind_p4_m)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                   format(summary(mod_ind_p5_m)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = ".")),
                 c("$F$ - estad\\'{i}stico", 
                   paste0(format(anova(mod_ind_p1_m)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                   paste0(format(anova(mod_ind_p2_m)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                   paste0(format(anova(mod_ind_p3_m)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                   paste0(format(anova(mod_ind_p4_m)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                   paste0(format(anova(mod_ind_p5_m)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"))
               )))
aux<-aux[c(3:(NROW(aux)-2))]
star_tex_write(aux,file = paste0( parametros$resultado_tablas, 'iess_mod_m_beneficios_ind' , '.tex' ))

#Tabla del los modelos para mujeres con pagos indebidos---------------------------------------------
aux <- capture.output(stargazer(mod_ind_p1_f,
                mod_ind_p2_f,
                mod_ind_p3_f,
                mod_ind_p4_f,
                mod_ind_p5_f,
                header=FALSE,
                se=list(NULL),
                dep.var.caption  = "Mujeres",
                dep.var.labels.include = FALSE,
                column.labels=c("Pago 1","Pago 2","Pago 3","Pago 4","Pago 5"),
                covariate.labels = "70\\%\\;SBU",
                align=FALSE, 
                style = "all",
                decimal.mark = ",",
                digit.separator=".",
                nobs=FALSE,
                model.numbers=FALSE,
                df=FALSE,
                digits=5,
                digits.extra=3,
                keep.stat = c("ll"),
                table.layout ="-lc-t-s-a-",
                label = "tab:iess_mod_f_beneficios_ind",
                title = "Estimaci\\'{o}n de los coeficientes $\\alpha_{i,1}$ del modelo de beneficios, con aporte patronal extempor\\'{a}neo",
                #single.row=TRUE,
                notes.align = "l",
                #notes = "Nota:",
                #type = "text",
                add.lines=list(
                  c("Observaciones", 
                    format(nobs(mod_ind_p1_f),nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(nobs(mod_ind_p2_f),nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(nobs(mod_ind_p3_f),nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(nobs(mod_ind_p4_f),nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(nobs(mod_ind_p5_f),nsmall =2,decimal.mark = ",",big.mark = ".")),
                  c("$AIC$", 
                    format(AIC(mod_ind_p1_f),nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(AIC(mod_ind_p2_f),nsmall =2,decimal.mark = ",",big.mark = "."), 
                    format(AIC(mod_ind_p3_f),nsmall =2,decimal.mark = ",",big.mark = "."), 
                    format(AIC(mod_ind_p4_f),nsmall =2,decimal.mark = ",",big.mark = "."), 
                    format(AIC(mod_ind_p5_f),nsmall =2,decimal.mark = ",",big.mark = ".")),
                  c("$R^{2}$", 
                    format(summary(mod_ind_p1_f)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_ind_p2_f)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_ind_p3_f)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_ind_p4_f)$r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_ind_p5_f)$r.squared,nsmall =2,decimal.mark = ",",big.mark = ".")),
                  c("$R^{2}$\\;ajustado", 
                    format(summary(mod_ind_p1_f)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_ind_p2_f)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_ind_p3_f)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_ind_p4_f)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = "."),
                    format(summary(mod_ind_p5_f)$adj.r.squared,nsmall =2,decimal.mark = ",",big.mark = ".")),
                  c("$F$ - estad\\'{i}stico", 
                    paste0(format(anova(mod_ind_p1_f)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                    paste0(format(anova(mod_ind_p2_f)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                    paste0(format(anova(mod_ind_p3_f)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                    paste0(format(anova(mod_ind_p4_f)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"),
                    paste0(format(anova(mod_ind_p5_f)$`F value`[1],nsmall =2,decimal.mark = ",",big.mark = "."),"$^{***}$"))
                )))
aux<-aux[c(3:(NROW(aux)-2))]
star_tex_write(aux,file = paste0( parametros$resultado_tablas, 'iess_mod_f_beneficios_ind' , '.tex' ))


#Tabla de los coeficeintes \alpha con pagos indebidos-----------------------------------------------


message( paste( rep('-', 100 ), collapse = '' ) )
rm( list = ls()[ !( ls() %in% c( 'parametros' ) ) ] )
gc()
