%---------------------------------------------------------------------------------------------------
\chapter{Análisis demográfico y epidemiológico}
\label{chp_demog}
%--------------------------------------------------------------------------------------------------
% Población Afiliada y Pensionistas del SGO

 A continuación presentamos un análisis tabular y gráfico de las principales variables demográficas y financieras de la población asegurada.

\section{Estructura demográfica de la población asegurada}

% %---------------------------------------------------------------------------------------------------
\subsection{Afiliados}
\label{chp_demog:afi}

%---------------------------------------------------------------------------------------------------
Para el presente estudio se considera el número de afiliados activos a diciembre de cada año; en la
tabla \ref{tab:iess_pob_afi_ini} y figura \ref{fig:iess_pob_afi_ini} se muestra a la población
afiliada en el período 2005 - 2020, observándose un crecimiento promedio del 5,99\% anual.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución de la población afiliada}
\label{tab:iess_pob_afi_ini}
{\fontsize{10}{12}\selectfont
\begin{tabular}{rrrrr}
\toprule
Año	& Afiliado Activos  & Afiliados Activos & Total Afiliados & Porcentaje \\
    & Masculinos        & Femeninos         &                 & Incremento \\
\midrule
\input{tablas/iess_pob_afi_ini.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Portal BI. Cubo Historia Laboral Activos. \\
{\bf Elaborado:} DAIE.}
\end{table}

A diciembre de 2020 existen 2.847.077 afiliados activos, que representa un crecimiento del 130,81\%
en comparación al año 2005. Entre el 2005 y el  2014 se observa un crecimiento sostenido de los afiliados. En los años 2015 y 2016 se evidencia un decremento del número de afiliados producto de la disminución de más del 50\% del precio del crudo, la apreciación del dólar y el terremoto de abril de 2016. Si bien la población afiliada se recuperó lentamente entre el año 2017 y 2019, sin embargo en el 2020 se observa nuevamente una caida importante del 8,51\% producto de la crisis sanitaria, económica y social producida por la pandemia COVID-19.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución de la población afiliada al SGO}
\label{fig:iess_pob_afi_ini}
\includegraphics[scale=0.8]{graficos/iess_pob_afi_ini.png}
\caption*{\scriptsize {\bf Fuente:} Portal BI. Cubo Historia Laboral Activos. \\
{\bf Elaborado:} DAIE.}
\end{figure}

En la figura \ref{fig:iess_pir_afiliados} se presenta la distribución por edad y sexo de población afiliada.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo de la población afiliada}
\label{fig:iess_pir_afiliados}
\includegraphics[scale=0.8]{graficos/iess_pir_afiliados.png}
\caption*{\scriptsize {\bf Fuente:} Portal BI. Cubo Historia Laboral Activos. \\
{\bf Elaborado:} DAIE.}
\end{figure}

Del total de afiliados a diciembre de 2020, el 42,7\% son mujeres y el 57,3\% son hombres. La edad
promedio de la población femenina es de 41,3 años, mientras que la  población masculina es de 39,7
años.

%---------------------------------------------------------------------------------------------------
% \section{Estructura demográfica de la población de beneficiarios}
% \label{chp_demog:pob_beneficiaria}
% 
% A continuación, se detalla la población beneficiaria por cada una de las prestaciones que otorga el
% Seguro IVM.

%---------------------------------------------------------------------------------------------------
\subsection{Jubilados de vejez del SGO}
\label{chp_demog:pens_vej}

La tabla \ref{tab:iess_pen_vejez_ini_ivm_unificado} presenta la evolución histórica del número de jubilados por vejez a diciembre de cada año.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica del número de jubilados por vejez del SGO}
\label{tab:iess_pen_vejez_ini_ivm_unificado}
%\scalebox{0.7}{
{\fontsize{10}{12}\selectfont
\begin{tabular}{*{7}{r}}
\toprule
Año	& Jubilados  & Porcentaje de        & Jubilados       & Porcentaje de   & Jubilados & Porcentaje de\\
    & de vejez   & crecimiento          & hombres         & crecimiento     & mujeres   & crecimiento\\
\midrule
\input{tablas/iess_pen_vejez_unificado.tex}
\bottomrule
\end{tabular}}
\caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
{\bf Elaborado:} DAIE.}
\end{table}

Se observa que en el año 2012 se entregaron beneficios a 215.010 jubilados por vejez, en contraste con las 409.016 personas a quienes se entregó esta prestación en el año 2020, con un crecimiento
promedio anual del 8,39\%.

% En la tabla \ref{tab:iess_pen_vejez_ini_h_ivm} se presenta la evolución histórica del número de jubilados hombres por vejez.
% 
% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Evolución histórica del número de jubilados hombres por vejez del SGO}
% \label{tab:iess_pen_vejez_ini_h_ivm}
% %\scalebox{0.7}{
% {\fontsize{10}{12}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Jubilados  & Porcentaje de        & Beneficio anual   & Porcentaje de   & Pensión  & Porcentaje de\\
%     & de vejez   & crecimiento  & pagado (USD)      & crecimiento & Promedio  & crecimiento\\
% \midrule
% \input{tablas/iess_pen_vejez_ini_h.tex}
% \bottomrule
% \end{tabular}}
% \caption*{\scriptsize {\bf Fuente:} Boletín Estadístico del Sistema de Pensiones. \\
% {\bf Elaborado:} DAIE.}
% \end{table}
% 
% En la tabla \ref{tab:iess_pen_vejez_ini_m_ivm} se presenta la evolución histórica del número de jubiladas mujeres por vejez.
% 
% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Evolución histórica del número de jubiladas mujeres por vejez del SGO}
% \label{tab:iess_pen_vejez_ini_m_ivm}
% %\scalebox{0.7}{
% {\fontsize{10}{12}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Jubilados  & Porcentaje de        & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
%     & de vejez   & crecimiento  & pagado (USD)      & crecimiento & Promedio  & crecimiento\\
% \midrule
% \input{tablas/iess_pen_vejez_ini_m.tex}
% \bottomrule
% \end{tabular}}
% \caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
% {\bf Elaborado:} DAIE.}
% \end{table}


El Crecimiento de la población jubilada por vejez se observa en la siguiente figura:

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Crecimiento de la población jubilada por vejez }
\label{fig:iess_pen_vejez_ini_ivm}
\includegraphics[scale=0.8]{graficos/iess_pen_vejez_ini.png}
\caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
{\bf Elaborado:} DAIE.}
\end{figure}

En la figura \ref{fig:iess_pir_jub_vejez} se muestra la distribución por edad y sexo de los jubilados por vejez:
\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo de los jubilados por vejez}
\label{fig:iess_pir_jub_vejez}
\includegraphics[scale=0.8]{graficos/iess_pir_jub_vejez.png}
\caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
{\bf Elaborado:} DAIE.}
\end{figure}

Del total de jubilados de vejez, el 42,94\% son mujeres y el 57,06\% son hombres. La edad promedio de
las mujeres es de 71,9 años, mientras que la de los hombres es de 72,4 años.

% Se procede a analizar la distribución por monto y sexo de las pensiones mensuales de los jubilados por vejez.
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{\small{Distribución por monto y sexo de las pensiones mensuales de los jubilados por vejez}}
% \label{fig:iess_pir_monto_jub_vejez}
% \includegraphics[scale=0.8]{graficos/iess_pir_monto_jub_vejez.png}
% \caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% El valor de la pensión mensual promedio de mujeres es de USD  586,17 y para los hombres  es de USD 664,93 a  diciembre de  2020, incluyendo los beneficios de decimotercera y decimocuarta pensión.

% La distribución de los jubilados de vejez por condición de elegibilidad desde el año 2012 a 2020 es
% la siguiente:
%
% Poner gráfica del Fabian
%
% Se observa que la tendencia de los jubilados por vejez con más de 40 años tiene una tendencia
% decreciente (del 15,3\% al 9,2\%), en contraste con la tendencia creciente de las concesiones a
% jubilados que cumplen las condiciones de 70 años de edad y 10 años de aporte (del 7,7\% al 10,4\%).
% Se evidencia que más del 57\% de la población aportó más de 30 años, situación que se ve reflejada
% en las tablas de actividad.

% %---------------------------------------------------------------------------------------------------
\subsection{Jubilados de invalidez del SGO}
\label{chp_demog:pens_inv}

La evolución histórica del número de jubilados por invalidez, tanto global como por sexo, a diciembre de cada año se presenta en las siguientes tablas:


\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica del número de jubilados por invalidez del SGO}
\label{tab:iess_pen_invalidez_ini}
{\fontsize{10}{11}\selectfont
\begin{tabular}{*{7}{r}}
\toprule
Año	& Jubilados      & Porcentaje de        & Jubilados       & Porcentaje de   & Jubilados & Porcentaje de\\
    & de invalidez   & crecimiento          & hombres         & crecimiento     & mujeres   & crecimiento\\
\midrule
\input{tablas/iess_pen_invalidez_unificado.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
{\bf Elaborado:} DAIE.}
\end{table}

% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Variación de la población jubilada y del beneficio anual pagado por invalidez}
% \label{tab:iess_pen_invalidez_ini}
% {\fontsize{10}{11}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Jubilados      & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
%     & de invalidez   & crecimiento  & pagado (USD)      & crecimiento & Promedio & crecimiento \\
% \midrule
% \input{tablas/iess_pen_invalidez_ini.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
% {\bf Elaborado:} DAIE.}
% \end{table}


% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Evolución histórica del número de jubilados hombres por invalidez del SGO}
% \label{tab:iess_pen_invalidez_ini_h}
% {\fontsize{10}{11}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Jubilados      & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
%     & de invalidez   & crecimiento  & pagado (USD)      & crecimiento & Promedio & crecimiento \\
% \midrule
% \input{tablas/iess_pen_invalidez_ini_h.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
% {\bf Elaborado:} DAIE.}
% \end{table}


% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Variación de la población de hombres jubilados por invalidez y del beneficio anual pagado}
% \label{tab:iess_pen_invalidez_ini_h}
% {\fontsize{10}{11}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Jubilados      & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
%     & de invalidez   & crecimiento  & pagado (USD)      & crecimiento & Promedio & crecimiento \\
% \midrule
% \input{tablas/iess_pen_invalidez_ini_h.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
% {\bf Elaborado:} DAIE.}
% \end{table}


% 
% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Variación de la población de mujeres jubiladas por invalidez y del beneficio anual pagado}
% \label{tab:iess_pen_invalidez_ini_m}
% {\fontsize{10}{11}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Jubilados      & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
%     & de invalidez   & crecimiento  & pagado (USD)      & crecimiento & Promedio & crecimiento \\
% \midrule
% \input{tablas/iess_pen_invalidez_ini_m.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
% {\bf Elaborado:} DAIE.}
% \end{table}

% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Evolución histórica del número de jubiladas mujeres por invalidez del SGO}
% \label{tab:iess_pen_invalidez_ini_m}
% {\fontsize{10}{11}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Jubilados      & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
%     & de invalidez   & crecimiento  & pagado (USD)      & crecimiento & Promedio & crecimiento \\
% \midrule
% \input{tablas/iess_pen_invalidez_ini_m.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
% {\bf Elaborado:} DAIE.}
% \end{table}



El crecimiento anual promedio desde el 2012 hasta diciembre de 2020 es del 7,43\%. Se observa que
en los últimos tres años se estabiliza el número de jubilados de invalidez alrededor de 30.000. En la  figura \ref{fig:iess_pen_invalidez_ini} se presenta el Crecimiento de la población jubilada por invalidez por sexo:

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Crecimiento de la población jubilada por invalidez}
\label{fig:iess_pen_invalidez_ini}
\includegraphics[scale=0.8]{graficos/iess_pen_invalidez_ini.png}
\caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
{\bf Elaborado:} DAIE.}
\end{figure}

La distribución por edad y sexo de los jubilados por invalidez se muestra en la figura \ref{fig:iess_pir_jub_invalidez}.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo de los jubilados por invalidez}
\label{fig:iess_pir_jub_invalidez}
\includegraphics[scale=0.8]{graficos/iess_pir_jub_invalidez.png}
\caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
{\bf Elaborado:} DAIE.}
\end{figure}

De los  29.119 jubilados por invalidez que existen a diciembre de 2020, el 46,22\% son mujeres y el
53,78\% son hombres. La edad promedio de las mujeres perteneciente a este grupo de beneficiarios es de
63,2 años y de 63,4 años para los hombres.

% La distribución por monto y sexo de las pensiones mensuales de los jubilados por invalidez se muestra en
% la figura \ref{fig:iess_pir_monto_jub_invalidez}:
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Distribución por monto y sexo de las pensiones mensuales de jubilados por invalidez}
% \label{fig:iess_pir_monto_jub_invalidez}
% \includegraphics[scale=0.8]{graficos/iess_pir_monto_jub_invalidez.png}
% \caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% A diciembre de 2020, la pensión mensual promedio por invalidez de las mujeres es de USD 485,25 y para los hombres de USD 469,67, incluyendo beneficios de decimotercera y decimocuarta pensión.

% Las condiciones de elegibilidad para la jubilación de invalidez, se muestra en la siguiente tabla:
% 
% Poner gráfica
% 
% Los jubilados por invalidez se concentran en la edad comprendida entre 45 y 60 años. La mayoría
% tiene menos de 10 años de aportes. Se observa una concentración de jubilados en el grupo de más de
% 60 años de edad y menos de 10 años de aportes. Llama la atención que existe un 3,86\% de jubilados
% de invalidez, cumpliendo los requisitos para la jubilación de vejez.

%---------------------------------------------------------------------------------------------------
\subsection{Jubilados especiales de vejez (por la Ley Orgánica de Discapacidades)}
\label{chp_demog:pens_disc}

La evolución histórica del número de pensionistas por jubilación especial de vejez (por la \legalcite{LeyDis})
a diciembre de cada año por sexo se presenta en las siguientes tablas:

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica de la población jubilada especial de vejez}
\label{tab:iess_pen_discapacidad_ini}
{\fontsize{10}{12}\selectfont
\begin{tabular}{*{7}{r}}
\toprule
Año	& Jubilados         & Porcentaje de        & Jubilados       & Porcentaje de   & Jubilados & Porcentaje de\\
    & de discapacidad   & crecimiento          & hombres         & crecimiento     & mujeres   & crecimiento\\
\midrule
\input{tablas/iess_pen_discapacidad_unificado.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
{\bf Elaborado:} DAIE.}
\end{table}


% 
% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Crecimiento de la población jubilada especial de vejez}
% \label{tab:iess_pen_discapacidad_ini}
% {\fontsize{10}{12}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Jubilados        & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
% & de discapacidad  & crecimiento  & pagado (USD)      & crecimiento & Promedio & crecimiento\\
% \midrule
% \input{tablas/iess_pen_discapacidad_ini.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
% {\bf Elaborado:} DAIE.}
% \end{table}
% 
% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Crecimiento de la población jubilada especial de vejez masculina}
% \label{tab:iess_pen_discapacidad_ini_h}
% {\fontsize{10}{12}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Jubilados        & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
% & de discapacidad  & crecimiento  & pagado (USD)      & crecimiento & Promedio & crecimiento\\
% \midrule
% \input{tablas/iess_pen_discapacidad_ini_h.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
% {\bf Elaborado:} DAIE.}
% \end{table}
% 
% 
% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Crecimiento de la población jubilada especial de vejez femenina}
% \label{tab:iess_pen_discapacidad_ini_m}
% {\fontsize{10}{12}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Jubilados        & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
% & de discapacidad  & crecimiento  & pagado (USD)      & crecimiento & Promedio & crecimiento\\
% \midrule
% \input{tablas/iess_pen_discapacidad_ini_m.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
% {\bf Elaborado:} DAIE.}
% \end{table}




\textbf{Nota}: Se registra a los jubilados especiales de vejez desde el año 2014, pues desde esta fecha se
inició la entrega de esta prestación.

En la figura \ref{fig:iess_pen_discapacidad_ini} se observa el crecimiento de la población jubilada especial de vejez:

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Crecimiento de la población jubilada especial de vejez}
\label{fig:iess_pen_discapacidad_ini}
\includegraphics[scale=0.8]{graficos/iess_pen_discapacidad_ini.png}
\caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
{\bf Elaborado:} DAIE.}
\end{figure}
Esta población creció en el período 2014 - 2020, al pasar de 170 beneficiarios en el año 2014 a
9.688 pensionistas en el 2020, que equivale al 100,14\%. La
distribución por edad y sexo de los jubilados especiales por vejez se muestra en la figura
\ref{fig:iess_pir_jub_discapacidad}.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo de los jubilados especiales por vejez }
\label{fig:iess_pir_jub_discapacidad}
\includegraphics[scale=0.8]{graficos/iess_pir_jub_discapacidad.png}
\caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
{\bf Elaborado:} DAIE.}
\end{figure}

De los 9.688 jubilados especiales por vejez existentes, el 38,14\% son mujeres y 61,86\% son
hombres. La edad promedio de las mujeres perteneciente a este grupo de beneficiarios es de 56 años y de 
56,2 años para los hombres.


% La distribución por sexo de las pensiones mensuales promedio de los jubilados especiales por vejez se
% muestra en la figura \ref{fig:iess_pir_monto_jub_discapacidad}.
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Distribución por sexo de las pensiones mensuales de los jubilados especiales por vejez}
% \label{fig:iess_pir_monto_jub_discapacidad}
% \includegraphics[scale=0.8]{graficos/iess_pir_monto_jub_discapacidad.png}
% \caption*{\scriptsize {\bf Fuente:} Boletín estadístico del Sistema de Pensiones. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% A diciembre de 2020, la pensión mensual promedio de los jubilados especiales por vejez de las mujeres es de USD 682,90 y de los hombres es de USD 722,20, incluyendo los beneficios de decimotercera y decimocuarta pensión.

A continuación se analiza la población beneficiaria con  prestaciones de montepío.


%---------------------------------------------------------------------------------------------------
\subsection{Pensionistas de viudedad del SGO}
\label{chp_demog:pens_viudedad}

La evolución histórica del número de pensionistas por viudedad a diciembre de cada año por sexo se presenta en las siguientes tablas:


\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica de la población pensionista por viudedad}
\label{tab:iess_pen_viudedad_ini}
{\fontsize{8}{10}\selectfont
\begin{tabular}{*{7}{r}}
\toprule
Año	& Jubilados         & Porcentaje de        & Jubilados       & Porcentaje de   & Jubilados & Porcentaje de\\
    & de viudedad   & crecimiento          & hombres         & crecimiento     & mujeres   & crecimiento\\
\midrule
\input{tablas/iess_pen_viudedad_unificado.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas. \\
{\bf Elaborado:} DAIE.}
\end{table}
% 
% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Crecimiento de la población pensionista por viudedad}
% \label{tab:iess_pen_viudedad_ini}
% {\fontsize{8}{10}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Pensionistas & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
%     & de viudedad  & crecimiento  & pagado (USD)      & crecimiento & Promedio & crecimiento\\
% \midrule
% \input{tablas/iess_pen_viudedad_ini.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas. \\
% {\bf Elaborado:} DAIE.}
% \end{table}
% 
% \vspace{-.5cm}
% 
% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Crecimiento de la población pensionista por viudedad masculina}
% \label{tab:iess_pen_viudedad_ini_h}
% {\fontsize{8}{10}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Pensionistas & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
%     & de viudedad  & crecimiento  & pagado (USD)      & crecimiento & Promedio & crecimiento\\
% \midrule
% \input{tablas/iess_pen_viudedad_ini_h.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas. \\
% {\bf Elaborado:} DAIE.}
% \end{table}
% 
% \vspace{-.5cm}
% 
% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Crecimiento de la población pensionista por viudedad femenina}
% \label{tab:iess_pen_viudedad_ini_m}
% {\fontsize{8}{10}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Pensionistas & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
%     & de viudedad  & crecimiento  & pagado (USD)      & crecimiento & Promedio & crecimiento\\
% \midrule
% \input{tablas/iess_pen_viudedad_ini_m.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas. \\
% {\bf Elaborado:} DAIE.}
% \end{table}

En la figura \ref{fig:iess_pen_viudedad_ini} se presenta el crecimiento de la población pensionista por viudedad:

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Crecimiento de la población pensionista por viudedad}
\label{fig:iess_pen_viudedad_ini}
\includegraphics[scale=0.8]{graficos/iess_pen_viudedad_ini.png}
\caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas. \\
{\bf Elaborado:} DAIE.}
\end{figure}

En el período 2012 - 2020, los pensionistas de viudedad crecieron de 63.002 a 97.807 beneficiarios, con un crecimiento promedio anual del 5,65\%.

La distribución por edad y sexo de los pensionistas por viudedad se muestra en la figura \ref{fig:iess_pir_pen_viudedad}.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo de pensionistas de viudedad}
\label{fig:iess_pir_pen_viudedad}
\includegraphics[scale=0.8]{graficos/iess_pir_pen_viudedad.png}
\caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas. \\
{\bf Elaborado:} DAIE.}
\end{figure}

De los  97.807 pensionistas por viudedad, el 91,27\% son mujeres y 8,73\% son hombres. El porcentaje de hombres pensionistas por viudedad es bajo, debido que a partir del año 2010 con la \legalcite{LeyRSS} se inicia la concesión de este beneficio en igualdad de condiciones.

La edad promedio de las mujeres es de 70,5 años mientras que la de los hombres es de 69,4 años.

% La distribución por sexo de las pensiones mensuales por viudedad se muestra en la figura
% \ref{fig:iess_pir_monto_pen_viudedad}.
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Distribución por sexo de las pensiones mensuales de los pensionistas por viudedad}
% \label{fig:iess_pir_monto_pen_viudedad}
% \includegraphics[scale=0.8]{graficos/iess_pir_monto_pen_viudedad.png}
% \caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% A diciembre de 2020, la pensión mensual promedio de las mujeres es de USD 366,31 y de los hombres es de USD 421,40, incluyendo los beneficios de decimotercera y decimocuarta pensión.

%---------------------------------------------------------------------------------------------------
\subsection{Pensionistas de orfandad del SGO}
\label{chp_demog:pens_orfandad}
La evolución histórica de número global y por sexo de pensionistas por orfandad a diciembre de cada año, se presenta en las siguientes tablas:


\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica de la población pensionista por orfandad}
\label{tab:iess_pen_orfandad_ini}
{\fontsize{10}{12}\selectfont
\begin{tabular}{*{7}{r}}
\toprule
Año	& Jubilados         & Porcentaje de        & Jubilados       & Porcentaje de   & Jubilados & Porcentaje de\\
    & de orfandad       & crecimiento          & hombres         & crecimiento     & mujeres   & crecimiento\\
\midrule
\input{tablas/iess_pen_orfandad_unificado.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas. \\
{\bf Elaborado:} DAIE.}
\end{table}

% 
% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Crecimiento de la población pensionista por orfandad}
% \label{tab:iess_pen_orfandad_ini}
% {\fontsize{10}{12}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Pensionistas & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
%     & de orfandad  & crecimiento  & pagado (USD)      & crecimiento & Promedio & crecimiento\\
% \midrule
% \input{tablas/iess_pen_orfandad_ini.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas. \\
% {\bf Elaborado:} DAIE.}
% \end{table}
% 
% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Crecimiento de la población pensionista por orfandad masculina}
% \label{tab:iess_pen_orfandad_ini_h}
% {\fontsize{9}{11}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Pensionistas & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de \\
%     & de orfandad  & crecimiento  & pagado (USD)      & crecimiento & Promedio          & crecimiento \\
% \midrule
% \input{tablas/iess_pen_orfandad_ini_h.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas. \\
% {\bf Elaborado:} DAIE.}
% \end{table}
% 
% \vspace{-.7cm}
% 
% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Crecimiento de la población pensionista por orfandad femenina}
% \label{tab:iess_pen_orfandad_ini_m}
% {\fontsize{9}{11}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Pensionistas & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
%     & de orfandad  & crecimiento  & pagado (USD)      & crecimiento & Promedio & crecimiento\\
% \midrule
% \input{tablas/iess_pen_orfandad_ini_m.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas. \\
% {\bf Elaborado:} DAIE.}
% \end{table}
% 
% \vspace{-.5cm}

% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Evolución histórica de la población masculina pensionista por orfandad}
% \label{tab:iess_pen_orfandad_ini_h}
% {\fontsize{9}{11}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Pensionistas & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de \\
%     & de orfandad  & crecimiento  & pagado (USD)      & crecimiento & Promedio          & crecimiento \\
% \midrule
% \input{tablas/iess_pen_orfandad_ini_h.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas. \\
% {\bf Elaborado:} DAIE.}
% \end{table}
% 
% \vspace{-.7cm}
% 
% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Evolución histórica de la población femenina pensionista por orfandad}
% \label{tab:iess_pen_orfandad_ini_m}
% {\fontsize{9}{11}\selectfont
% \begin{tabular}{*{7}{r}}
% \toprule
% Año	& Pensionistas & Porcentaje de      & Beneficio anual   & Porcentaje de   & Pensión & Porcentaje de\\
%     & de orfandad  & crecimiento  & pagado (USD)      & crecimiento & Promedio & crecimiento\\
% \midrule
% \input{tablas/iess_pen_orfandad_ini_m.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas. \\
% {\bf Elaborado:} DAIE.}
% \end{table}
% 
% \vspace{-.5cm}


Se observa que, comparado el año 2012 con el 2020, la población permaneció prácticamente constante. Esta población creció en el período 2012 - 2020, al pasar de 30.506 beneficiarios en el año 2012 a
32.817 en el 2020, con un crecimiento promedio anual del 0,92\%.

\vspace{-.5cm}

En la figura \ref{fig:iess_pen_orfandad_ini} se presenta el crecimiento de la población pensionista por orfandad:

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Crecimiento de la población pensionista por orfandad}
\label{fig:iess_pen_orfandad_ini}
\includegraphics[scale=0.8]{graficos/iess_pen_orfandad_ini.png}
\caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas.\\
{\bf Elaborado:} DAIE.}
\end{figure}

La distribución por edad y sexo de los pensionistas por orfandad se muestra en la figura
\ref{fig:iess_pir_pen_orfandad}.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo de pensionistas por orfandad}
\label{fig:iess_pir_pen_orfandad}
\includegraphics[scale=0.8]{graficos/iess_pir_pen_orfandad.png}
\caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas.\\
{\bf Elaborado:} DAIE.}
\end{figure}

De los 32.817 pensionistas por orfandad existentes, el 67,06\% son mujeres y 32,94\% son hombres. La
edad promedio de las mujeres es de 45,4 años mientras que la de los hombres es de 21 años. Se observa un importante número de pensionistas mujeres por orfandad con edades mayores a 18 años, debido a que antes de 1984 se entregaron pensiones vitalicias a las hijas solteras.

% La distribución por sexo de las pensiones mensuales de los pensionistas por orfandad se muestra en
% la figura \ref{fig:iess_pir_monto_pen_orfandad}:
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Distribución por sexo de las pensiones mensuales de los pensionistas por orfandad}
% \label{fig:iess_pir_monto_pen_orfandad}
% \includegraphics[scale=0.8]{graficos/iess_pir_monto_pen_orfandad.png}
% \caption*{\scriptsize {\bf Fuente:} Bases de nómina de pensionistas. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% A diciembre de 2020, la pensión mensual promedio de las mujeres es de USD 228,45; mientras que la de
% los hombres es de USD  126,29, incluyendo los beneficios de decimotercera y decimocuarta pensión.

%-------------------------------------------------------------------------------
\subsection{Menores de 18 años}

Actualmente, el universo de hijos menores de 18 años de afiliados al IESS es desconocido. El IESS, utilizando registros administrativos, ha estimado el número de hijos menores de 18 años. La tabla \ref{tab:iess_afi_est_ben_e} y la figura \ref{fig:iess_pob_hijos} muestran la evolución histórica del número estimado de hijos menores de 18 años de afiliados.

\begin{table}[H]
\centering
\caption{Evolución histórica de hijos menores de 18 años de afiliados}
\label{tab:iess_afi_est_ben_e}%
%\scalebox{0.8}{
%{\fontsize{10}{12}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{c*{6}{r}}
\toprule
Año & Menores de & Porcentaje de &  Hombres & Porcentaje de & Mujeres & Porcentaje de \\
    & 18 años    & crecimiento   &          & crecimiento   &         & crecimiento \\
\midrule
\input{tablas/iess_hijos_sgo.tex}
\bottomrule
\end{tabular} 
%}
\caption*{\scriptsize {\bf Fuente:} Dirección Nacional de Afiliación y Cobertura. \\{\bf Elaborado:} DAIE.}
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica de hijos menores de 18 años de afiliados}
\label{fig:iess_pob_hijos}
\includegraphics[scale=0.8]{graficos/iess_pob_hijos.png}
\caption*{\scriptsize {\bf Fuente:} Dirección Nacional de Afiliación y Cobertura.  \\
{\bf Elaborado:} DAIE.}
\end{figure}


La figura \ref{fig:iess_pir_hijos_18} muestra la distribución de edades por sexo de los hijos menores de 18 años para el año 2020.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo de los hijos menores de 18 años de afiliados}
\label{fig:iess_pir_hijos_18}
\includegraphics[scale=0.8]{graficos/iess_pir_hijos_18.png}
\caption*{\scriptsize {\bf Fuente:} Dirección Nacional de Afiliación y Cobertura.  \\
{\bf Elaborado:} DAIE.}
\end{figure}

% Quitar tabla \ref{tab:iess_afi_est_cony_p}
% 
% \begin{table}[H]
% \centering
% \caption{Estadísticas de la edad de cónyugues de afiliados}
% \label{tab:iess_afi_est_cony_e}%
% %\scalebox{0.8}{
% {\fontsize{10}{12}\selectfont
% %\scalebox{0.8}{
% %\resizebox{\columnwidth}{!}{%
% \begin{tabular}{*{8}{r}}
% \toprule
% Edad & MIN & Q25 & MED & MEDIA & DS & Q75 & MAX \\
% \midrule
% \input{tablas/iess_afi_est_cony_e.tex}
% \bottomrule
% \end{tabular} }
% \caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
% \end{table}
% 
% \begin{table}[H]
% \centering
% \caption{Cónyugues de afiliados por sexo}
% \label{tab:iess_afi_est_cony_p}%
% %\scalebox{0.8}{
% {\fontsize{10}{12}\selectfont
% %\scalebox{0.8}{
% %\resizebox{\columnwidth}{!}{%
% \begin{tabular}{*{2}{r}}
% \toprule
% Sexo & Porcentaje \\
% \midrule
% \input{tablas/iess_afi_est_cony_p.tex}
% \bottomrule
% \end{tabular} }
% \caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
% \end{table}

% ------------------------------------------------------------------------------
\section{Análisis de la población cotizante}

\subsection{Cotizantes por sexo, edad y tiempo de cotización}

% En este capítulo se presentan los principales datos sobre la población afiliada proporcionados por el IESS,
% referentes al último ejercicio para el que se disponía de datos, es decir, 2020. Se muestran datos sobre pensiones, cotizantes, afiliados activos e inactivos, entradas y salidas, primera y última fecha de cotización, y salarios.

En esta sección se presenta información principal sobre la población afiliada al IESS al 31 de diciembre del año 2020. Se muestran datos sobre afiliados, activos e inactivos, entradas y salidas, primera y última fecha de cotización; y, salarios.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Proporción de afiliados activos e inactivos de ambos sexos}
\label{fig:iess_act_inact}
\includegraphics[ scale = 0.6]{graficos/iess_act_inact.png}
\caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
{\bf Elaborado:} DAIE.}
\end{figure}

% En la figura \ref{fig:iess_act_inact} se observa que en el año base de 2020 se registraron 2,05 millones de cotizantes activos hombres (29,35\% del total) y 1,47 millones de cotizantes activos mujeres (21,12\% del total); 2,05 millones de hombres (29,46\% del total) y 1,4 millones (20,07\% del total) de mujeres son inactivos. En resumen, se registra un total de 6,9 millones de afiliados, de los cuales 50,47\% son activos y 49,53\% son inactivos; y 58,81\% de los cotizantes activos son hombres y 41,19\% son mujeres.

En la figura  \ref{fig:iess_act_inact} se presenta la composición de la población afiliada. Referente a los activos \footnote{Afiliados Activos:
Los afiliados que aportaron al IESS al menos una vez al año}, el $29,35\%$ son hombres, mientras el $21,12\%$ son mujeres. Por otra parte, los hombres inactivos\footnote{Afiliados Inactivos:
Los afiliados que aportaron al IESS, pero no se encuentran con aportes a fecha de corte del estudio.} representa un $29,46\%$ y las mujeres inactivas son el $20,07\%$ de la población total

% Afiliados Activos:
% Los afiliados que aportaron al IESS, y tienen aportes hasta la fecha de corte del estudio.
% 
% Afiliados Inactivos:
% Los afiliados que aportaron al IESS, pero no se encuentran con aportes a fecha de corte del estudio.

% ------------------------------------------------------------------------------
\subsection{Cotizantes activos}

% A continuación, en las figuras \ref{fig:iess_pastel_afi_cotiz_riesgo_mascul} y \ref{fig:iess_afi_cotiz_activ_riesgo_mascul} se muestran los grupos de cotizantes activos según la exposición al riesgo.
% 
% De la población masculina activa cotizante, el 63,07\% tiene requisitos cumplidos para invalidez y muerte, la población con requisitos no cumplidos representa el 33,14\%; mientras que, el 2,20\% cumplirá requisitos de vejez en 5 años y el 1,59\% cumplirá requisitos de vejez en un año o menos.
% 
% %en las gráficas \ref {fig:iess_cotizantes_activ_masculi_1} , \ref{fig:iess_cotizantes_mascul_2} , \ref{fig:iess_pastel_afi_cotiz_riesgo_mascul} y \ref{fig:iess_afi_cotiz_activ_riesgo_mascul} los datos de la población afiliada activa sexo masculino. 
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Afiliados activos por tipo de riesgo, sexo masculino}
% \label{fig:iess_pastel_afi_cotiz_riesgo_mascul}
% \includegraphics[ scale = 0.9 ]{graficos/iess_pastel_afi_cotiz_riesgo_mascul.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Afiliados activos por edad, número de años de cotizaciones y tipo de riesgo, sexo masculino}
% \label{fig:iess_afi_cotiz_activ_riesgo_mascul}
% \includegraphics[ scale = 0.5 ]{graficos/iess_afi_cotiz_riesgo_mascul.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% % De la población cotizante activa masculina, el $63,07\%$ tienen requisitos cumplidos para invalidez y muerte, la población con requisitos no cumplidos representan el $33,14\%$; en tanto que, el $2,20\%$ cumplirá requisitos de vejez en un año o menos y apenas el $1,59\%$ cumplirán requisitos de vejez en 5 años.
% 
% % % La población se divide en cuatro grupos de acuerdo con el tipo de riesgo:
% % % 
% % % \begin{itemize}
% % % \item Grupo 1, en lila, los afiliados que no cumplen los requisitos, por tanto, no elegibles a ninguna pensión;
% % % \item Grupo 2, en amarillo, los afiliados que tienen al menos cinco años de cotización, por tanto, elegibles para una pensión resultante de eventual invalidez o muerte;
% % % \item Grupo 3, en rojo, los afiliados que, en menos de cinco años, cumplirían con los criterios de edad y tiempo de contribución para recibir una pensión de vejez; y
% % % \item Grupo 4, en negro, los afiliados que ya tienen derecho a su pensión de vejez o lo tendrán en menos de un año.
% % % \end {itemize}
% % 
% % % GRAFICA 3-2

En la figura \ref{fig:iess_cotizantes_activ_unificado} se muestra la distribución de afiliados por número de años de cotizaciones, observándose mayor concentración de 0 a 10 años de cotizaciones.
% Así también, en la figura \ref{fig:iess_cotizantes_mascul_2} se presenta la distribución de los activos cotizantes masculinos por edad. Dicha población es joven y hay una concentración importante entre los 25 y 30 años. 

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Afiliados activos por número de años de cotizaciones y sexo}
\label{fig:iess_cotizantes_activ_unificado}
\includegraphics[ scale =0.8 ]{graficos/iess_cotizantes_activ_unificado.png}
\caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
{\bf Elaborado:} DAIE.}
\end{figure}


% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Afiliados activos por número de años de cotizaciones, sexo masculino}
% \label{fig:iess_cotizantes_activ_masculi_1}
% \includegraphics[ scale =0.8 ]{graficos/iess_cotizantes_activ_masculi_1.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Afiliados activos por edad, sexo masculino}
% \label{fig:iess_cotizantes_mascul_2}
% \includegraphics[ scale = 0.8 ]{graficos/iess_cotizantes_mascul_2.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%FEMENINO

% GRAFICA 3-3



% A continuación, en la figura \ref{fig:iess_pastel_afi_cotiz_riesgo_femen} se detallan los datos de la población afiliada activa del sexo femenino. 
% 
% De la población activa cotizante del sexo femenino, el 62,91\% tiene requisitos cumplidos para invalidez y muerte, la población con requisitos no cumplidos representa el 33\%; en tanto que, el 2,23\% cumplirá requisitos de vejez en un año o menos; y, apenas el 1,85\% cumplirá requisitos de vejez en 5 años.
% 
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Afiliados activos por tipo de riesgo, sexo femenino}
% \label{fig:iess_pastel_afi_cotiz_riesgo_femen}
% \includegraphics[ scale = 1 ]{graficos/iess_pastel_afi_cotiz_riesgo_femen.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Afiliados activos por edad, número de años de cotizaciones y tipo de riesgo, sexo femenino}
% \label{fig:iess_afi_cotiz_riesgo_femenin}
% \includegraphics[ scale = 0.5 ]{graficos/iess_afi_cotiz_riesgo_femenin.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}


% En la figura \ref{fig:iess_activ_cotiz_fem_1}  se muestra la distribución de afiliados por número de años de cotizaciones y se observa mayor concentración de 0 a 10 años.
En la figura \ref{fig:iess_activ_cotiz_sexo_unificado}  se presenta la distribución de los activos cotizantes  por edad y sexo. Dicha población es joven y hay una concentración importante entre los 25 y 30 años. 

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Afiliados activos por edad y sexo}
\label{fig:iess_activ_cotiz_sexo_unificado}
\includegraphics[ scale = 0.8 ]{graficos/iess_activ_cotiz_sexo_unificado.png}
\caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
{\bf Elaborado:} DAIE.}
\end{figure}


% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Afiliados activos por número de años de cotizaciones, sexo femenino}
% \label{fig:iess_activ_cotiz_fem_1}
% \includegraphics[ scale = 0.8 ]{graficos/iess_activ_cotiz_fem_1.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Afiliados activos por edad, sexo femenino}
% \label{fig:iess_activ_cotiz_fem_2}
% \includegraphics[ scale = 0.8 ]{graficos/iess_activ_cotiz_fem_2.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}



% % Se observa en las gráficas (superior izquierda) que, en el año base de 2018, entre los cotizantes hombres
% % activos, el 36,6\% pertenece al grupo 1 ―sin derecho a pensión alguna―; el 55,8\%, al grupo 2; el 4,8\%, al grupo 3; y una menor parte de 2,7\%, al grupo 4 ―afiliados que ya tienen derecho a solicitar la pensión de vejez―.
% % 
% % En la gráfica anterior (inferior izquierda) se presenta la distribución por edad de la población de activos
% % cotizantes para el año 2018. Se observa que la población de hombres es joven y que hay una concentración
% % importante entre los 25 y los 30 años de edad, que disminuye gradualmente hacia las edades más avanzadas.
% % 
% % También se aprecia (gráfica superior derecha) que la gran mayoría de los cotizantes tienen pocos años de
% % contribución. Del total de 2,2 millones de cotizantes activos hombres registrados en 2018, 1,5 millones (65,2\%) tenían entre 0 y 10 años de cotización.


%REVISAR PARA EXCLUIR LA EXPOSICIÓN AL RIESGO

\subsection{Cotizantes inactivos}

% A continuación, en las figuras \ref{fig:iess_pastel_afi_inac_cotiz_riesgo_mascul} y \ref{fig:iess_afi_cotiz_inac_riesgo_mascul} se muestran los grupos de cotizantes inactivos según la exposición al riesgo.
% 
% De la población cotizante inactiva masculina, el 79,02\% tiene requisitos no cumplidos, la población con requisitos cumplidos para invalidez y muerte representa el 19.28\%; mientras que, el 1,16\% cumplirá requisitos de vejez en en 5 años; y, el 0,54\% cumplirá requisitos de vejez en un año o menos.

% % GRAFICA 3-4

% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Afiliados inactivos por tipo de riesgo, sexo masculino}
% \label{fig:iess_pastel_afi_inac_cotiz_riesgo_mascul}
% \includegraphics[ scale = 1 ]{graficos/iess_pastel_afi_inac_cotiz_riesgo_mascul.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Afiliados inactivos por edad, número de años de cotizaciones y tipo de riesgo, sexo masculino}
% \label{fig:iess_afi_cotiz_inac_riesgo_mascul}
% \includegraphics[ scale = 0.5 ]{graficos/iess_afi_cotiz_inac_riesgo_mascul.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}

% De la población cotizante inactiva masculina, el 79,02\% tienen requisitos no cumplidos, la población con requisitos cumplidos para invalidez y muerte representan el 19.28\%; en tanto que, el 1,16\% cumplirá requisitos de vejez en en 5 años y el 0,54\% cumplirán requisitos de vejez en un año o menos.

En la figura \ref{fig:iess_inac_cotiz_anios_unificado} se muestra la distribución de los afiliados  por número de años de cotización, donde se observa gran concentración de el rango de 0 a 10 años. 
% Así también, en la figura \ref{fig:iess_inac_cotiz_masc_2} se presenta la distribución de los inactivos cotizantes del sexo masculino por edad. Dicha población es joven y hay una concentración importante entre los 25 y 30 años. Además, a la edad de 60 años se evidencia una importante cantidad de afiliados inactivos.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Afiliados inactivos  por número de años de cotizaciones y sexo }
\label{fig:iess_inac_cotiz_anios_unificado}
\includegraphics[ scale = 0.8 ]{graficos/iess_inac_cotiz_anios_unificado.png}
\caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
{\bf Elaborado:} DAIE.}
\end{figure}

% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Afiliados inactivos por edad, sexo masculino (miles)}
% \label{fig:iess_inac_cotiz_masc_2}
% \includegraphics[ scale = 0.8 ]{graficos/iess_inac_cotiz_masc_2.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}


% % Respecto al sexo femenino (gráfica superior izquierda), se observa que, en el mismo año, entre las cotizantes
% % mujeres activas, el 37,8\% pertenece al grupo 1; el 54,2\%, al grupo 2; el 5,5\%, al grupo 3; y el 2,4\%, al grupo 4.
% % 
% % En la gráfica anterior (inferior izquierda) se presenta la distribución por edad de la población de activos
% % cotizantes para 2018. Se observa que la población de mujeres es joven y que hay una concentración importante
% % entre los 25 y los 30 años de edad, que disminuye gradualmente hacia las edades más avanzadas.
% % 
% % Se observa también (gráfica superior derecha) que la gran mayoría de los cotizantes tienen pocos años de
% % contribución. Del total de 1,5 millones de cotizantes activas mujeres registradas en 2018, 1,1 millones (66,5\%) tenían entre 0 y 10 años de cotización.
% % A continuación, se presentan las gráficas correspondientes a la distribución por edad, sexo y tiempos cotizados
% % por tipo de riesgo.
% % 
% % GRAFICA 3-5
% A continuación, se detallan en las gráficas \ref {fig:iess_inac_cotiz_fem_1}, \ref{fig:iess_inac_cotiz_fem_2} , \ref{fig:iess_pastel_distri_inact_cotiz_riesgo_femen} y \ref{fig:iess_distri_inact_cotiz_riesgo_femen} los datos de la población afiliada activa sexo femenino. 

%A continuación, en la figura \ref{fig:iess_pastel_distri_inact_cotiz_riesgo_femen} se detallan los datos de la población afiliada inactiva del sexo femenino.

% De la población inactiva femenina, el 81,66\% tiene requisitos no cumplidos, la población con requisitos cumplidos para invalidez y muerte llega al 17,13\%; en tanto la población que cumple requisitos para vejez en 5 años representa el 0,83\%; y, la población que cumple requisitos para vejez en 1 año o menos es apenas el 0,38\%. 
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Afiliados inactivos por tipo de riesgo, sexo femenino}
% \label{fig:iess_pastel_distri_inact_cotiz_riesgo_femen}
% \includegraphics[ scale = 0.9 ]{graficos/iess_pastel_distri_inact_cotiz_riesgo_femen.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Afiliados inactivos por edad, número de años de cotizaciones y tipo de riesgo, sexo femenino}
% \label{fig:iess_distri_inact_cotiz_riesgo_femen}
% \includegraphics[ scale = 0.5 ]{graficos/iess_distri_inact_cotiz_riesgo_femen.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}

% De la población cotizante inactiva femenina, el 81,66\% tienen requisitos no cumplidos, la población con requisitos cumplidos para invalidez y muerte representan el 17,13\%; en tanto la población que cumple requisitos para vejez en 5 años representa el 0,83\% y la población que cumple requisitos para vejez en 1 año o menos representa el 0,38\%. 

% En la figura \ref{fig:iess_inac_cotiz_fem_1} se muestra la distribución de afiliados inactivos por número de años de cotizaciones y sexo, donde se observa mayor concentración en el rango de 0 a 10 años. 
En la figura \ref{fig:iess_inacti_sexo_unificado} se muestra la distribución de la población inactiva por sexo y edad. Dicha población es adulta y hay una concentración importante entre los 25 y 30 años. En ambos sexos se observa una alta cantidad de personas inactivas a la edad de 60 años.

% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Afiliados inactivos por número de años de cotizaciones, sexo femenino (miles)}
% \label{fig:iess_inac_cotiz_fem_1}
% \includegraphics[ scale = 0.8 ]{graficos/iess_inac_cotiz_fem_1.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Afiliados inactivos por edad y sexo}
\label{fig:iess_inacti_sexo_unificado}
\includegraphics[ scale = 0.8 ]{graficos/iess_inacti_sexo_unificado.png}
\caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
{\bf Elaborado:} DAIE.}
\end{figure}



%
% % GRAFICA 3-5

% La mayoría de los afiliados hombres inactivos (el 76,7\%) pertenecen al grupo 1, es decir, no elegible a una
% pensión; el 18,7\%, al grupo 2; el 3,8\%, al grupo 3; y el 0,7\%, al grupo 4. Pero entre las afiliadas inactivas
% mujeres, la mayoría (el 81,8\%) pertenece al grupo 1, es decir, no elegible a una pensión; el 15,8\%, al grupo 2; el 2,1\%, al grupo 3; y el 0,3\%, al grupo 4.

\subsection{Entradas al sistema}


Sobre la base de la información proporcionada por el IESS, se estimó la distribución de las tasas de entrada al sistema para el intervalo de 15 a 70 años de edad.
\vspace{-.4cm}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Tasas de entrada al sistema por edad como porcentaje del total de entradas por sexo}
\label{fig:iess_entr_sis}
\includegraphics[ scale = 0.7 ]{graficos/iess_entr_sis.png}
\caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
{\bf Elaborado:} DAIE.}
\end{figure}

\vspace{-.5cm}
En la figura \ref{fig:iess_entr_sis} podemos observar que tanto hombres como mujeres están entrando a edades jóvenes y que las tasas caen gradualmente hasta llegar a cero en los 70 años. Estas tasas alcanzan su máximo a la edad de 20 y 21 años para hombres y mujeres respectivamente.

\subsection{Salarios}

En esta sección se analizan los salarios promedio de los trabajadores cotizantes activos en el año 2020, diferenciados por sexo y edad.

En la figura \ref{fig:iess_pir_masa_salarial} se muestra la distribución por sexo del salario declarado de los afiliados a diciembre de 2020.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por sexo del salario declarado de los afiliados a diciembre de 2020}
\label{fig:iess_pir_masa_salarial}
\includegraphics[scale=.7]{graficos/iess_pir_masa_salarial.png}
\caption*{\scriptsize {\bf Fuente:} Base de datos de planillas. \\
{\bf Elaborado:} DAIE.}
\end{figure}

El promedio declarado por parte de las mujeres a diciembre 2020 es USD  742,93 y para los
hombres es de USD 772,29.El promedio total es de USD 756,48.

En la tabla \ref{tab:iess_afi_tiempo_aportacion} se presenta la cantidad de afiliados activos a la fecha corte de este estudio, clasificados por edad, tiempo de aportes en años y el valor promedio del sueldo sobre el que se aporta. En esta matriz se detectan afiliados con edades superiores a los 90 años y se observa que el 28,5\% de la población afiliada tiene entre 0 y 5 años aportados; más del 50\% de la población afiliada está comprendida entre 26 y 45 años de edad; y, que las personas que más
años aportados tienen les corresponden los salarios promedios más altos. La población entre 41 y 45 años tiene el promedio de sueldos más altos (USD 870,12 en promedio de sueldos).

De acuerdo con la información proporcionada por el IESS, la distribución de los salarios promedio es la que se presenta a continuación.

\vspace{-.4cm}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Promedios de los salarios observados (mensuales) de 15 a 70 años, por sexo, 2020}
\label{fig:iess_salarios}
\includegraphics[ scale = 0.7]{graficos/iess_salarios.png}
\caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
{\bf Elaborado:} DAIE.}
\end{figure}

En el año 2020, el salario promedio mínimo observado para los hombres fue USD 349,10 a la edad de 17 y  el máximo fue USD 909,42 en los 50 años. Para el sexo femenino, el salario promedio mínimo observado  toma el valor de USD 360,45 a los 17 años y el máximo fue de USD 857,91 a los 37 años. La diferencia salarial entre ambos sexos se acentúa a partir de los 28 años; como se observa en la figura \ref{fig:iess_salarios}, a los 67 años, el salario promedio femenino corresponde solamente al 73,6\% del salario masculino. Una posible causa de la caída observada en los salarios femeninos se debe a que las mujeres pasan a dedicarse a actividades relacionadas con su capacidad reproductiva y, en consecuencia, dedican menos tiempo al trabajo remunerado.

% \subsection{Pensionistas}
% 
% En la figura \ref{fig:iess_tipo_pension_ambsex} se observa que, al 31 de diciembre del año 2020, de la población pensionista, el 70,71\% corresponde a vejez, el 16,91\% a viudez, mientras que, el 6,71\% a invalidez; y, apenas el 5,67\% a orfandad.
% 
% % GRAFICO 3-8
% %AMBOS SEXOS ---------------------------------------------------------------
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Número de pensionistas de ambos sexos por tipo de pensión, 2020}
% \label{fig:iess_tipo_pension_ambsex}
% \includegraphics[ scale = 1]{graficos/iess_tipo_pension_ambsex.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% A continuación, en la figura \ref{fig:iess_tipo_pensi_masc} se muestra que, para el caso del sexo masculino, el 85,06\% son pensionistas por vejez, el 3,11\% por viudez, el 7,89\% por invalidez y apenas el 3,94\% corresponde a orfandad.
% 
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Número de pensionistas de sexo masculino por tipo de pensión, 2020}
% \label{fig:iess_tipo_pensi_masc}
% \includegraphics[ scale = 1 ]{graficos/iess_tipo_pension_fem.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% Para el caso del sexo femenino, en la figura \ref{fig:iess_tipo_pension_fem}, el 57,76\% son pensionistas por vejez, el 29,36\% por viudez, el 5,64\% por invalidez y apenas el 7,24\% son por orfandad.
% 
% 
% 
% \begin{figure}[H]
% \centering
% % <<<<<<< HEAD
% % \captionsetup{justification=centering}
% % \caption{Número de pensionistas de sexo femenino por tipo de pensión, 2020}
% % \label{fig:iess_tipo_pension_fem}
% % =======
% \captionsetup{justification=centering}
% \caption{Número de pensionistas de sexo femenino por tipo de pensión, 2020}
% \label{fig:iess_tipo_pension_fem}
% %>>>>>>> 55bdf112e8a46729421de995eef43a9c2496e25a
% \includegraphics[ scale = 1]{graficos/iess_tipo_pension_masc.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% 
% A continuación, en la tabla \ref{tab:iess_edad_promedio_ivm}, se muestran las edades promedios de pensionistas por tipo de pensión y sexo. La edad promedio por tipo de pensión es semejante en la mayoría de los casos, excepto para orfandad, puesto que la edad para hombres y mujeres es de 21,03 y 45,44 años respectivamente. El primer caso se debe a que el montepío pasa a beneficiar a los hombres viudos solo desde el año  2012, con condición de elegibilidad relativamente más restricta; y, en el segundo caso, a que en el año  1982 se suprimió el derecho a montepío
% de las hijas solteras mayores de edad.
% % TABLA 3-1
% \vspace{-.5cm}
% 
% \begin{table}[H]
% \captionsetup{justification=centering}
%   \begin{center} % centering{}
%   \caption{Edad promedio de pensionistas por tipo de pensión y sexo, 2020}
%   \label{tab:iess_edad_promedio_ivm}
%   {\fontsize{9}{10} \selectfont
%   \begin{tabular}{rrrr} %r right
%     \toprule
%     Pensión	& Masculino	& Femenino & Total \\
%     \midrule
%     \input{tablas/iess_edad_promedio_ivm.tex}
%     \bottomrule
%   \end{tabular}
%   }
%   \caption*{ \scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
%   {\bf Elaborado:} DAIE.}
%   \end{center}
% \end{table}
% 
% \vspace{-1.3cm}
% 
% En la figura \ref{fig:iess_pension_sex} se observan el números de pensionistas por tipo de pensión, edad y sexo. El número de pensionistas por vejez alcanza su máximo a los 68 años para hombres y 66 para mujeres; la invalidez, a los 62 y 61 años, respectivamente; la viudez, a los 66 y 81 años; y la orfandad, a los 17 años para ambos sexos.
% \vspace{-.4cm}
% % GRAFICO 3-9
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Número de pensionistas por tipo de pensión, edad y sexo, 2020, miles de personas}
% \label{fig:iess_pension_sex}
% \includegraphics[ scale = 0.7 ]{graficos/iess_pension_sex.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% 
% 
% \subsection{Beneficios y gastos}
% 
% En la figura \ref{fig:iess_benef_pensi_sexo_ambsex} se observa que, del gasto total en beneficios para ambos sexos, el 82,1\% se destinó al pago de pensiones por vejez, el 9,53\% al pago de pensiones por viudedad, seguido del 6,65\% para cancelar los beneficios por invalidez y apenas el 1,72\% para fue para pago de pensiones por orfandad. 
% % GRAFICO 3-10
% \vspace{-0.5cm}
% %AMBOS SEXOS
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Gastos en beneficios por tipo de pensión ambos sexos, 2020 (millones USD)}
% \label{fig:iess_benef_pensi_sexo_ambsex}
% \includegraphics[ scale = 0.7]{graficos/iess_benef_pensi_sexo_ambsex.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% \vspace{-.5cm}
% 
% Para el caso femenino, en la figura \ref{fig:iess_benef_pensi_sexo_femen} se muestra que, del gasto total, el 72,13\%  corresponde a pensiones de vejez, seguido por viudez que representa el 18,85\%, invalidez el 6,29\%; y, orfandad el 2,73\%. Para el sexo masculino, en la figura \ref{fig:iess_benef_pensi_sexo_mascul} se observa que las pensiones de vejez representan el 90,81\% , seguidas por viudez que representan 6,96\%, invalidez el 1,39\% y orfandad el 0,85\%. 
% \vspace{-.5cm}
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Gastos en beneficios por tipo de pensión femenino, 2020 (millones USD)}
% \label{fig:iess_benef_pensi_sexo_femen}
% \includegraphics[ scale = 0.8]{graficos/iess_benef_pensi_sexo_mascul.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Gastos en beneficios por tipo de pensión masculino, 2020 (millones USD)}
% \label{fig:iess_benef_pensi_sexo_mascul}
% \includegraphics[ scale = 0.8]{graficos/iess_benef_pensi_sexo_femen.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% \vspace{-.8cm}
% 
% En las figuras \ref{fig:iess_val_prom_benef_vej_inv_viu_orf}  se aprecia que, en el caso de vejez, pese a la misma tendencia de disminución,
% las pensiones femeninas siempre siguen debajo de las masculinas en cuanto a valor. Asimismo, hay una
% coincidencia en las edades iniciales de pensiones de vejez y una caída abrupta en los valores de pensiones de invalidez para ambos sexos. Estos dos factores podrían estar relacionados.
% 
% \vspace{-.6cm}
% % GRAFICO 3-11
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Valores promedios de beneficios por tipo de pensión, sexo y edad, 2020 (USD)}
% \label{fig:iess_val_prom_benef_vej_inv_viu_orf}
% \includegraphics[ scale = .65]{graficos/iess_val_prom_benef_vej_inv_viu_orf.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% 
% En la figura  \ref{fig:iess_benef_prom_sex} se observa que las pensiones de vejez e invalidez superan al SBUM, mientras que los beneficios de
% viudez y orfandad están por debajo, aunque a menudo la familia recibe ambas pensiones (viudez y orfandad),
% con lo cual se supera el umbral mencionado. La pensión de vejez llega casi al salario promedio de 770,74 en el
% caso de los hombres y el mismo caso de las mujeres, que reciben un salario promedio de 742,93, inferior al de los hombres.
% 
% 
% % GRAFICO 3-12
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Valores promedios de beneficios por tipo de pensión, sexo y edad, 2020 (USD)}
% \label{fig:iess_benef_prom_sex}
% \includegraphics[ scale = 1]{graficos/iess_benef_prom_sex.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}

\begin{landscape}
\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Población afiliada al IESS por rangos de edad, número de aportaciones y sueldo promedio a diciembre de 2020}
\label{tab:iess_afi_tiempo_aportacion}
\scalebox{0.6}{
\begin{tabular}{r|crrrrrrrrrr|c}
\toprule
\multicolumn{1}{c|}{\multirow{2}[4]{*}{Edad}} & \multicolumn{11}{p{20em}|}{Tiempo de afiliación} & \multicolumn{1}{c}{\multirow{2}[4]{*}{Total}} \\
\cmidrule{2-12} & [0 , 5] & [6 , 10] & [11 , 15] & [16 , 20] & [21 , 25] & [26 ,30] & [31 , 35] & [36 , 40] & [41 , 45]  & [46 , 50]& \text{$>50$} &  \\
\midrule
\input{tablas/iess_afi_tiempo_aportacion.tex}
\bottomrule
\end{tabular}
}

\caption*{\scriptsize {\bf Fuente:} Base de datos de planillas. \\
{\bf Elaborado:} DAIE.}
\end{table}
\vspace{-1cm}

%{\small La matriz precedente detalla la cantidad de afiliados activos a la fecha corte de este estudio,
%clasificados por edad, tiempo de aportes en años y el valor promedio del sueldo sobre el que se aporta.
%En esta matriz se detectan afiliados con edades superiores a los 90 años.}

%{\scriptsize Además se observa que el 28,5\% de la población afiliada tiene entre 0 y 5 años aportados, que más del 50\% de la población afiliada está comprendida entre 26 y 45 años de edad; y,  que las personas que más
%años aportados tienen les corresponden los salarios promedios más altos
%La población entre 41 y 45 años tiene el promedio de sueldos más altos (USD 870,12 en promedio de sueldos).}
\end{landscape}


%-------------------------------------------------------------------- Tiempo de aportación afiliados hombres
\begin{landscape}
\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Población de hombres afiliados al IESS por rangos de edad, número de aportaciones y sueldo promedio a diciembre de 2020}
\label{tab:iess_afi_tiempo_aportacion_h}
\scalebox{0.6}{
\begin{tabular}{r|crrrrrrrrrr|c}
\toprule
\multicolumn{1}{c|}{\multirow{2}[4]{*}{Edad}} & \multicolumn{11}{p{20em}|}{Tiempo de afiliación} & \multicolumn{1}{c}{\multirow{2}[4]{*}{Total}} \\
\cmidrule{2-12} & [0 , 5] & [6 , 10] & [11 , 15] & [16 , 20] & [21 , 25] & [26 ,30] & [31 , 35] & [36 , 40] & [41 , 45]  & [46 , 50]& \text{$>50$} &  \\
\midrule
\input{tablas/iess_afi_tiempo_aportacion_h.tex}
\bottomrule
\end{tabular}
}

\caption*{\scriptsize {\bf Fuente:} Base de datos de planillas. \\
{\bf Elaborado:} DAIE.}
\end{table}
\vspace{-1cm}
\end{landscape}

%-------------------------------------------------------------------- Tiempo de aportación afiliadas mujeres
\begin{landscape}
\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Población de mujeres afiliadas al IESS por rangos de edad, número de aportaciones y sueldo promedio a diciembre de 2020}
\label{tab:iess_afi_tiempo_aportacion_m}
\scalebox{0.6}{
\begin{tabular}{r|crrrrrrrrrr|c}
\toprule
\multicolumn{1}{c|}{\multirow{2}[4]{*}{Edad}} & \multicolumn{11}{p{20em}|}{Tiempo de afiliación} & \multicolumn{1}{c}{\multirow{2}[4]{*}{Total}} \\
\cmidrule{2-12} & [0 , 5] & [6 , 10] & [11 , 15] & [16 , 20] & [21 , 25] & [26 ,30] & [31 , 35] & [36 , 40] & [41 , 45]  & [46 , 50]& \text{$>50$} &  \\
\midrule
\input{tablas/iess_afi_tiempo_aportacion_m.tex}
\bottomrule
\end{tabular}
}

\caption*{\scriptsize {\bf Fuente:} Base de datos de planillas. \\
{\bf Elaborado:} DAIE.}
\end{table}
\vspace{-1cm}
\end{landscape}

\subsection{Masa salarial}
\label{chp_masa:salarial}

En la tabla \ref{tab:iess_masa_salarial_ini} y figura \ref{fig:iess_masa_salarial_ini} se presenta
la evolución anual de la masa salarial y la correspondiente al mes de diciembre para el período 2005
al 2020.

\begin{landscape}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución de la masa salarial (Período 2005 – 2020)}
\label{tab:iess_masa_salarial_ini}
\scalebox{0.8}{
\begin{tabular}{*{9}{r}}
\toprule
Año	& Masa salarial anual & Masa salarial anual & Masa salarial anual & Masa salarial      & Masa salarial      & Masa salarial      & Crecimiento de la           & Porcentaje de\\  
    & (USD) Masculino     & (USD) Femenino      & (USD)               & de diciembre (USD) & de diciembre (USD) & de diciembre (USD) & masa salarial anual (USD)   & crecimiento\\
     &     &      &                                                   & Masculino          & Femenino &        &      &     \\
\midrule
\input{tablas/iess_masa_salarial_ini.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Base de datos de planillas. \\
{\bf Elaborado:} DAIE.}
\end{table}

\end{landscape}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Masa salarial anual en el período 2005 – 2020 }
\label{fig:iess_masa_salarial_ini}
\includegraphics[scale=0.7]{graficos/iess_masa_salarial_ini.png}
\caption*{\scriptsize {\bf Fuente:} Base de datos de planillas. \\
{\bf Elaborado:} DAIE.}
\end{figure}

Para el año 2020, la masa salarial tiene un valor de USD  25.688.790.710,51, que
representa un crecimiento del 526,29\% en comparación al año 2005.

Se observa un rápido crecimiento de la masa salarial en el período 2005 al 2015, con una tasa promedio anual del 20,50\%. En el año 2016 se evidencia una disminución de la masa salarial producto de la caída de más del 50\% del precio del petróleo en el 2015 y del terremoto de abril de 2016. Si bien la masa salarial se recuperó lentamente entre el año 2017 y 2019; sin embargo en el 2020 se observa nuevamente un decremento importante del 7,33\% debido a la crisis sanitaria, económica y social producida por la pandemia COVID-19, que incrementó la tasa de desempleo en el país provocando una enorme cantidad de desafiliaciones.

%---------------------------------------------------------------------------------------------------
% Estísticas generales -----------------------------------------------------------------------------
% --------------------------------------------------------------------------------------------------
\section{Estadísticas generales para atenciones, beneficios y estadía}
\label{chp_demog:eg}
A continuación se presentan tablas que reflejan estadísticas descriptivas de la base de datos que
contiene la información del seguro de Salud del IESS.

La tabla \ref{tab:iess_ben_anio} refleja el número total de atenciones y valor en dólares de los
beneficios pagados por las mismas para cada año de la base de datos histórica.

% --------------------------------------------------------------------------------------------------
\begin{table}[H]
\centering
\caption{Número de atenciones y beneficios por año}
\label{tab:iess_ben_anio}%
%\scalebox{0.8}{
{\fontsize{10}{12}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{*{3}{r}}
\toprule
Año & Número de  & Total \\
    & atenciones & beneficio (USD) \\
\midrule
\input{tablas/iess_ben_anio.tex}
\bottomrule
\end{tabular} }
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\end{table}

La tabla \ref{tab:iess_ben_est_anio_X} nos muestra la estadística de los beneficios en dólares prestados
a los afiliados de seguro social. Se observa que en promedio se pagó más en los años 2013 y 2014. 
Mientras que los pagos máximos se dieron en los años 2015 y 2016.

% --------------------------------------------------------------------------------------------------
\begin{table}[H]
\centering
\caption{Estadísticas del beneficio en dólares por año, enfermedad y servicio}
\label{tab:iess_ben_est_anio_X}%
%\scalebox{0.8}{
{\fontsize{9}{11}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{*{6}{r}}
\toprule
Año & Enfermedad & Servicio & MED & MEDIA & DS \\
\midrule
\input{tablas/iess_ben_est_anio_X.tex}
\bottomrule
\end{tabular} }
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\end{table}

La tabla \ref{tab:iess_ben_est_anio_D} nos presenta la estadística en días del tiempo de estadía 
hospitalario para cada año de la base de datos. Notándose que la mediana es más alto para enfermedades
catastróficas. Así mismo la tabla \ref{tab:iess_ben_est_icd_D} refleja la estadística
del tiempo de estadía por enfermedad, donde la mediana y percentiles son más altos para Neoplasmas.
% --------------------------------------------------------------------------------------------------
\begin{table}[H]
\centering
\caption{Estadísticas del tiempo de estadía en días (Hospitalario) por año, enfermedad y servicio}
\label{tab:iess_ben_est_anio_D}%
%\scalebox{0.8}{
{\fontsize{9}{11}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{*{6}{r}}
\toprule
Año & Enfermedad & Servicio & Q25 & MED & Q75 \\
\midrule
\input{tablas/iess_ben_est_anio_D.tex}
\bottomrule
\end{tabular} }
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\end{table}

% --------------------------------------------------------------------------------------------------
\begin{landscape}
\vspace*{\fill}
\begin{table}[H]
\centering
\caption{Estadísticas del tiempo de estadía en días (Hospitalario) por enfermedad}
\label{tab:iess_ben_est_icd_D}%
%\scalebox{0.8}{
{\fontsize{10}{12}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{L{10cm}*{3}{R{1cm}}}
\toprule
Enfermedad & Q25 & MED & Q75 \\
\midrule
\input{tablas/iess_ben_est_icd_D.tex}
\bottomrule
\end{tabular} }
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\end{table}
\vspace*{\fill}
\end{landscape}

La tabla \ref{tab:iess_ben_est_u_D} nos presenta la estadística en días del tiempo de estadía
hospitalario de cada grupo de edad, para la clasificación Catastrófico y Enfermedad de la base de datos.
Ambos grupos registran una mediana alta en los pacientes con más de 60 años.
% --------------------------------------------------------------------------------------------------
\begin{table}[H]
\centering
\caption{Estadísticas del tiempo de estadía en días (Hospitalario) por gravedad y grupo de edad}
\label{tab:iess_ben_est_u_D}%
%\scalebox{0.8}{
{\fontsize{10}{12}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{l*{5}{r}}
\toprule
Enfermedad & Grupo & Q25 & MED & Q75 \\
\midrule
\input{tablas/iess_ben_est_u_D.tex}
\bottomrule
\end{tabular} }
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\end{table}

La tabla \ref{tab:iess_ben_est_icd_X} refleja estadísticas del beneficio en dólares por enfermedad.
La mediana más alta corresponde al grupo de enfermedades: Ciertas condiciones originadas en el período
perinatal.

% --------------------------------------------------------------------------------------------------
\begin{landscape}
\vspace*{\fill}
\begin{table}[H]
\centering
\caption{Estadísticas del beneficio en dólares por enfermedad}
\label{tab:iess_ben_est_icd_X}%
%\scalebox{0.8}{
{\fontsize{10}{12}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{L{10cm}*{3}{R{1.2cm}}}
\toprule
Enfermedad & MED & MEDIA & DS \\
\midrule
\input{tablas/iess_ben_est_icd_X.tex}
\bottomrule
\end{tabular} }
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\end{table}
\vspace*{\fill}
\end{landscape}

% --------------------------------------------------------------------------------------------------
\begin{table}[H]
\centering
\caption{Estadísticas del beneficio en dólares por grupo de edad}
\label{tab:iess_ben_est_u_X}%
%\scalebox{0.8}{
{\fontsize{10}{12}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{*{5}{r}}
\toprule
Tipo & Grupo & MED & MEDIA & DS \\
\midrule
\input{tablas/iess_ben_est_u_X.tex}
\bottomrule
\end{tabular} }
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\end{table}

La tabla \ref{tab:iess_ben_est_ser_X} presenta las estadísticas del beneficio en dólares por tipo de
servicio. Siendo el servicio hospitalario (HO) el que presenta un promedio muy alto si lo comparamos
con consulta externa (CE) y emergencias (EM).
% --------------------------------------------------------------------------------------------------
\begin{table}[H]
\centering
\caption{Estadísticas de beneficios por servicio}
\label{tab:iess_ben_est_ser_X}%
%\scalebox{0.8}{
{\fontsize{10}{12}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{*{4}{r}}
\toprule
Servicio & MED & MEDIA & DS \\
\midrule
\input{tablas/iess_ben_est_ser_X.tex}
\bottomrule
\end{tabular} }
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\end{table}

La tabla \ref{tab:iess_ben_est_cap_X} presenta las estadísticas del beneficio en dólares por capítulo,
siendo los capítulos 2, 15 y 16 los que presentan una mediana más alta en comparación al resto.
% --------------------------------------------------------------------------------------------------
\begin{table}[H]
\centering
\caption{Estadísticas de beneficios por capítulo}
\label{tab:iess_ben_est_cap_X}%
%\scalebox{0.8}{
{\fontsize{10}{12}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{*{4}{r}}
\toprule
Servicio & MED & MEDIA & DS \\
\midrule
\input{tablas/iess_ben_est_cap_X.tex}
\bottomrule
\end{tabular} }
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\end{table}

En las tablas \ref{tab:iess_ben_enf}, \ref{tab:iess_ben_sex_ser}, \ref{tab:iess_ben_ser},
\ref{tab:iess_ben_sexo_anio} y \ref{tab:iess_ben_icd_N} se presentan porcentajes de atenciones,
estadía y beneficios.
% --------------------------------------------------------------------------------------------------
\begin{table}[H]
\centering
\caption{Atenciones, estadía y beneficios por año y gravedad}
\label{tab:iess_ben_enf}%
%\scalebox{0.8}{
{\fontsize{10}{12}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{*{5}{r}}
\toprule
Año   & Enfermedad & Atenciones    & Estadía      & Beneficios       \\
      &            & (porcentaje)  & (porcentaje) & (porcentaje)\\
\midrule
\input{tablas/iess_ben_enf.tex}
\bottomrule
\end{tabular} }
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\end{table}

% --------------------------------------------------------------------------------------------------
\begin{table}[H]
\centering
\caption{Atenciones, estadía y beneficios por sexo y tipo de servicio}
\label{tab:iess_ben_sex_ser}%
%\scalebox{0.8}{
{\fontsize{10}{12}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{*{5}{r}}
\toprule
Sexo & Tipo     & Atenciones    & Estadía      & Beneficios       \\
     & servicio & (porcentaje)  & (porcentaje) & (porcentaje)\\
\midrule
\input{tablas/iess_ben_sex_ser.tex}
\bottomrule
\end{tabular} }
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\end{table}

% --------------------------------------------------------------------------------------------------
\begin{table}[H]
\centering
\caption{Atenciones, estadía y beneficios por año y tipo de servicio}
\label{tab:iess_ben_ser}%
%\scalebox{0.8}{
{\fontsize{10}{12}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{*{5}{r}}
\toprule
Año   & Tipo     & Atenciones    & Estadía      & Beneficios       \\
      & servicio & (porcentaje)  & (porcentaje) & (porcentaje)\\
\midrule
\input{tablas/iess_ben_ser.tex}
\bottomrule
\end{tabular} }
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\end{table}

% --------------------------------------------------------------------------------------------------
\begin{table}[H]
\centering
\caption{Atenciones, estadía y beneficios por año y sexo}
\label{tab:iess_ben_sexo_anio}%
%\scalebox{0.8}{
{\fontsize{10}{12}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{*{5}{r}}
\toprule
Año   & Sexo & Atenciones    & Estadía      & Beneficios       \\
      &      & (porcentaje)  & (porcentaje) & (porcentaje)\\
\midrule
\input{tablas/iess_ben_sexo_anio.tex}
\bottomrule
\end{tabular} }
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\end{table}

% --------------------------------------------------------------------------------------------------
\begin{landscape}
\vspace*{\fill}
\begin{table}[H]
\centering
\caption{Atenciones, estadía y beneficios por enfermedad}
\label{tab:iess_ben_icd_N}%
%\scalebox{0.8}{
{\fontsize{10}{12}\selectfont
%\scalebox{0.8}{
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{L{10cm}*{3}{R{2cm}}}
\toprule
Enfermedad & Atenciones    & Estadía      & Beneficios       \\
           & (porcentaje)  & (porcentaje) & (porcentaje)\\
\midrule
\input{tablas/iess_ben_icd_N.tex}
\bottomrule
\end{tabular} }
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\end{table}
\vspace*{\fill}
\end{landscape}

Las tablas \ref{tab:iess_ben_icd_u_n_c} y \ref{tab:iess_ben_icd_u_x_c} presentan el número de
atenciones en miles y el beneficio pagado en millones por las mismas, información organizada por
grupo de edad para la clasificación enfermedades catastróficas.

Las tablas \ref{tab:iess_ben_icd_u_n_e} y \ref{tab:iess_ben_icd_u_x_e} presentan el número de
atenciones en miles y el beneficio pagado en millones por las mismas, información organizada por
grupo de edad para la clasificación enfermedades no catastróficas.
% --------------------------------------------------------------------------------------------------
\begin{landscape}
\vspace*{\fill}
\begin{table}[H]
%\small
\centering
\caption{Número de atenciones en miles (2013-2018) - Catastróficas}
\begin{tabular}{L{10cm}*{6}{R{1.1cm}}}
\toprule
& \multicolumn{6}{c}{Grupo de edad} \\
Descripción &  $[0,5)$ & $[5,20)$ & $[20,40)$ & $[40,60)$ & $[60,110]$ & TOTAL \\
\midrule
    \input{tablas/iess_ben_icd_u_n_c.tex}
\bottomrule
\end{tabular}
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\label{tab:iess_ben_icd_u_n_c}
\end{table}
\vspace*{\fill}
\end{landscape}

% --------------------------------------------------------------------------------------------------
\begin{landscape}
\vspace*{\fill}
\begin{table}[H]
%\small
\centering
\caption{Número de atenciones en miles (2013-2018) - No catastróficas}
\scalebox{0.65}{%
\begin{tabular}{L{10cm}*{17}{R{1.2cm}}}
\toprule
& \multicolumn{17}{c}{Grupo de edad} \\
Descripción & $[0,1)$ & $[1,5)$ & $[5,10)$ & $[10,15)$ & $[15,20)$ & $[20,25)$ & $[25,30)$ & $[30,35)$ & $[35,40)$ & $[40,45)$ & $[45,50)$ & $[50,55)$ & $[55,60)$ & $[60,70)$ & $[70,80)$ & $[80,110]$ & TOTAL  \\
\midrule
    \input{tablas/iess_ben_icd_u_n_e.tex}
\bottomrule
\end{tabular}}
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\label{tab:iess_ben_icd_u_n_e}
\end{table}
\vspace*{\fill}
\end{landscape}

% --------------------------------------------------------------------------------------------------
\begin{landscape}
\vspace*{\fill}
\begin{table}[H]
%\small
\centering
\caption{Beneficios en millones de dólares (2013-2018) - Catastróficas}
\begin{tabular}{L{10cm}*{6}{R{1.1cm}}}
\toprule
& \multicolumn{6}{c}{Grupo de edad} \\
Descripción &  $[0,5)$ & $[5,20)$ & $[20,40)$ & $[40,60)$ & $[60,110]$ & TOTAL \\
\midrule
    \input{tablas/iess_ben_icd_u_x_c.tex}
\bottomrule
\end{tabular}
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\label{tab:iess_ben_icd_u_x_c}
\end{table}
\vspace*{\fill}
\end{landscape}

% % --------------------------------------------------------------------------------------------------
\begin{landscape}
\vspace*{\fill}
\begin{table}[H]
%\small
\centering
\caption{Beneficios en millones de dólares (2013-2018) - No catastróficas}
\scalebox{0.65}{%
\begin{tabular}{L{10cm}*{17}{R{1.2cm}}}
\toprule
& \multicolumn{17}{c}{Grupo de edad} \\
Descripción & $[0,1)$ & $[1,5)$ & $[5,10)$ & $[10,15)$ & $[15,20)$ & $[20,25)$ & $[25,30)$ & $[30,35)$ & $[35,40)$ & $[40,45)$ & $[45,50)$ & $[50,55)$ & $[55,60)$ & $[60,70)$ & $[70,80)$ & $[80,110]$ & TOTAL  \\
\midrule
    \input{tablas/iess_ben_icd_u_x_e.tex}
\bottomrule
\end{tabular}}
\caption*{\scriptsize Fuente: Dirección General de Salud Individual y Familiar. \\Elaborado: DAIE.}
\label{tab:iess_ben_icd_u_x_e}
\end{table}
\vspace*{\fill}
\end{landscape}

% Estimaciones -------------------------------------------------------------------------------------
% No castastróficas consulta externa
\section{Análisis epidemiológico}

%---------------------------------------------------------------------------------------------------
\subsection{Estimación de parámetros: consulta externa para enfermedades no catastróficas}

{\fontsize{8}{10}\selectfont
\begin{longtable}[H]{*{4}{l}*{3}{R{2cm}}}
\caption{Estimación de parámetros: consulta externa para enfermedades no catastróficas}\\
\label{tab:est_sal_sev} \\

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Capítulo} & \textbf{CIE} & \textbf{Probabilidad} &
\textbf{Duración} & \textbf{Severidad} \\
$g$ & $u$ & & $l$ & $1000\ p^{i,g,u}_{j,k,l}$ & $\tau^{i,g,u}_{j,k,l}$ & $\mu^{i,g,u}_{j,k,l}$ \\
\midrule
\endfirsthead

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Capítulo} & \textbf{CIE} & \textbf{Probabilidad} &
\textbf{Duración} & \textbf{Severidad} \\
$g$ & $u$ & & $l$ & $1000\ p^{i,g,u}_{j,k,l}$ & $\tau^{i,g,u}_{j,k,l}$ & $\mu^{i,g,u}_{j,k,l}$ \\
\midrule
\endhead

\bottomrule
\multicolumn{7}{r}{continúa...} \\
\endfoot

\bottomrule
\endlastfoot

\input{tablas/iess_est_sev_no_cat_ce.tex}

\end{longtable}
}

% No castastróficas emergencia ---------------------------------------------------------------------
\clearpage
\subsection{Estimación de parámetros: emergencia externa para enfermedades no catastróficas}

{\fontsize{8}{10}\selectfont
\begin{longtable}[H]{*{4}{l}*{3}{R{2cm}}}
\caption{Estimación de parámetros: emergencia para enfermedades no catastróficas}\\
\label{tab:est_sal_sev} \\

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Capítulo} & \textbf{CIE} & \textbf{Probabilidad} &
\textbf{Duración} & \textbf{Severidad} \\
$g$ & $u$ & & $l$ & $1000\ p^{i,g,u}_{j,k,l}$ & $\tau^{i,g,u}_{j,k,l}$ & $\mu^{i,g,u}_{j,k,l}$ \\
\midrule
\endfirsthead

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Capítulo} & \textbf{CIE} & \textbf{Probabilidad} &
\textbf{Duración} & \textbf{Severidad} \\
$g$ & $u$ & & $l$ & $1000\ p^{i,g,u}_{j,k,l}$ & $\tau^{i,g,u}_{j,k,l}$ & $\mu^{i,g,u}_{j,k,l}$ \\
\midrule
\endhead

\bottomrule
\multicolumn{7}{r}{continúa...} \\
\endfoot

\bottomrule
\endlastfoot

\input{tablas/iess_est_sev_no_cat_em.tex}

\end{longtable}
}

% No castastróficas hospitalización ----------------------------------------------------------------
\clearpage
\subsection{Estimación de parámetros: hospitalización para enfermedades no catastróficas}

{\fontsize{8}{10}\selectfont
\begin{longtable}[H]{*{4}{l}*{3}{R{2cm}}}
\caption{Estimación de parámetros: hospitalización para enfermedades no catastróficas}\\
\label{tab:est_sal_sev} \\

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Capítulo} & \textbf{CIE} & \textbf{Probabilidad} &
\textbf{Duración} & \textbf{Severidad} \\
$g$ & $u$ & & $l$ & $1000\ p^{i,g,u}_{j,k,l}$ & $\tau^{i,g,u}_{j,k,l}$ & $\mu^{i,g,u}_{j,k,l}$ \\
\midrule
\endfirsthead

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Capítulo} & \textbf{CIE} & \textbf{Probabilidad} &
\textbf{Duración} & \textbf{Severidad} \\
$g$ & $u$ & & $l$ & $1000\ p^{i,g,u}_{j,k,l}$ & $\tau^{i,g,u}_{j,k,l}$ & $\mu^{i,g,u}_{j,k,l}$ \\
\midrule
\endhead

\bottomrule
\multicolumn{7}{r}{continúa...} \\
\endfoot

\bottomrule
\endlastfoot

\input{tablas/iess_est_sev_no_cat_ho.tex}

\end{longtable}
}

% Castastróficas consulta externa ------------------------------------------------------------------
\clearpage
\subsection{Estimación de parámetros: consulta externa para enfermedades catastróficas}

{\fontsize{8}{10}\selectfont
\begin{longtable}[H]{*{4}{l}*{3}{R{2cm}}}
\caption{Estimación de parámetros: consulta externa para enfermedades catastróficas}\\
\label{tab:est_sal_sev} \\

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Capítulo} & \textbf{CIE} & \textbf{Probabilidad} &
\textbf{Duración} & \textbf{Severidad} \\
$g$ & $u$ & & $l$ & $1000\ p^{i,g,u}_{j,k,l}$ & $\tau^{i,g,u}_{j,k,l}$ & $\mu^{i,g,u}_{j,k,l}$ \\
\midrule
\endfirsthead

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Capítulo} & \textbf{CIE} & \textbf{Probabilidad} &
\textbf{Duración} & \textbf{Severidad} \\
$g$ & $u$ & & $l$ & $1000\ p^{i,g,u}_{j,k,l}$ & $\tau^{i,g,u}_{j,k,l}$ & $\mu^{i,g,u}_{j,k,l}$ \\
\midrule
\endhead

\bottomrule
\multicolumn{7}{r}{continúa...} \\
\endfoot

\bottomrule
\endlastfoot

\input{tablas/iess_est_sev_cat_ce.tex}

\end{longtable}
}

% Castastróficas emergencia ------------------------------------------------------------------------
\clearpage
\subsection{Estimación de parámetros: emergencia para enfermedades catastróficas}

{\fontsize{8}{10}\selectfont
\begin{longtable}[H]{*{4}{l}*{3}{R{2cm}}}
\caption{Estimación de parámetros: emergencia para enfermedades catastróficas}\\
\label{tab:est_sal_sev} \\

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Capítulo} & \textbf{CIE} & \textbf{Probabilidad} &
\textbf{Duración} & \textbf{Severidad} \\
$g$ & $u$ & & $l$ & $1000\ p^{i,g,u}_{j,k,l}$ & $\tau^{i,g,u}_{j,k,l}$ & $\mu^{i,g,u}_{j,k,l}$ \\
\midrule
\endfirsthead

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Capítulo} & \textbf{CIE} & \textbf{Probabilidad} &
\textbf{Duración} & \textbf{Severidad} \\
$g$ & $u$ & & $l$ & $1000\ p^{i,g,u}_{j,k,l}$ & $\tau^{i,g,u}_{j,k,l}$ & $\mu^{i,g,u}_{j,k,l}$ \\
\midrule
\endhead

\bottomrule
\multicolumn{7}{r}{continúa...} \\
\endfoot

\bottomrule
\endlastfoot

\input{tablas/iess_est_sev_cat_em.tex}

\end{longtable}
}

% Castastróficas hospitalización -------------------------------------------------------------------
\clearpage
\subsection{Estimación de parámetros: hospitalización para enfermedades catastróficas}

{\fontsize{8}{10}\selectfont
\begin{longtable}[H]{*{4}{l}*{3}{R{2cm}}}
\caption{Estimación de parámetros: hospitalización para enfermedades catastróficas}\\
\label{tab:est_sal_sev} \\

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Capítulo} & \textbf{CIE} & \textbf{Probabilidad} &
\textbf{Duración} & \textbf{Severidad} \\
$g$ & $u$ & & $l$ & $1000\ p^{i,g,u}_{j,k,l}$ & $\tau^{i,g,u}_{j,k,l}$ & $\mu^{i,g,u}_{j,k,l}$ \\
\midrule
\endfirsthead

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Capítulo} & \textbf{CIE} & \textbf{Probabilidad} &
\textbf{Duración} & \textbf{Severidad} \\
$g$ & $u$ & & $l$ & $1000\ p^{i,g,u}_{j,k,l}$ & $\tau^{i,g,u}_{j,k,l}$ & $\mu^{i,g,u}_{j,k,l}$ \\
\midrule
\endhead

\bottomrule
\multicolumn{7}{r}{continúa...} \\
\endfoot

\bottomrule
\endlastfoot

\input{tablas/iess_est_sev_cat_ho.tex}

\end{longtable}
}

% Frecuencia ---------------------------------------------------------------------------------------
\clearpage
\subsection{Estimación de la frecuencia para enfermedades no catastróficas}

Se considera que la frecuencia de atenciones médicas sigue un proceso de conteo tipo Poisson que
depende del tamaño de la población cubierta, gravedad de la atención, sexo y edad; pero no depende
del tipo de servicio médico realizado y de la enfermedad en cuestión.
\begin{equation}
N_{t,i,g,u} \rightsquigarrow PPois\left( \lambda_{i,g,u} l_{t,g,u} \right)
\end{equation}

Así como se lo detalla en \textcite{MathStaStoPro:2012}, el estimador por verosimilitud del proceso
de Poisson está dado por:
\begin{equation}
\hat{\lambda}_{i,g,u} = \frac{n_{T,i,g,u}}{ER_{T,i,g,u}\, l_{t,g,u}}
\end{equation}

{\fontsize{8}{10}\selectfont
\begin{longtable}[h]{*{3}{l}r}
\caption{Estimación de la frecuencia para enfermedades no catastróficas}\\
\label{tab:est_sal_fre_no_cat} \\
\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Gravedad} & \textbf{Frecuencia} \\
$g$ & $u$ & $j$ & $\lambda^{i,g,u}_{j,k,l}$ \\
\midrule
\endfirsthead

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Gravedad} & \textbf{Frecuencia} \\
$g$ & $u$ & $j$ & $\lambda^{i,g,u}_{j,k,l}$ \\
\midrule
\endhead

\bottomrule
\multicolumn{4}{r}{continúa...} \\
\endfoot

\bottomrule
\endlastfoot

\input{tablas/iess_est_fre_no_cat.tex}

\end{longtable}
}

% \begin{landscape}
% \begin{figure}[h]
% \caption{Estimación de $\lambda$ para mujeres}
% \centering
% \includegraphics[scale=1.0]{graficos/iess_lambda_nocatas_f.png}
% \caption*{\scriptsize  Elaborado: DAIE.}
% \end{figure}
% 
% \begin{figure}[h]
% \caption{Estimación de $\lambda$ para hombres}
% \centering
% \includegraphics[scale=1.0]{graficos/iess_lambda_nocatas_m.png}
% \caption*{\scriptsize  Elaborado: DAIE.}
% \end{figure}
% \end{landscape}

%---------------------------------------------------------------------------------------------------
\subsection{Estimación de la frecuencia para enfermedades catastróficas}

{\fontsize{8}{10}\selectfont
\begin{longtable}[H]{*{3}{l}r}
\caption{Estimación de la frecuencia para enfermedades catastróficas}\\
\label{tab:est_sal_fre_cat} \\

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Gravedad} & \textbf{Frecuencia} \\
$g$ & $u$ & $j$ & $\lambda^{i,g,u}_{j,k,l}$ \\
\midrule
\endfirsthead

\toprule
\textbf{Sexo} & \textbf{Edad} & \textbf{Gravedad} & \textbf{Frecuencia} \\
$g$ & $u$ & $j$ & $\lambda^{i,g,u}_{j,k,l}$ \\
\midrule
\endhead

\bottomrule
\multicolumn{4}{r}{continúa...} \\
\endfoot

\bottomrule
\endlastfoot

\input{tablas/iess_est_fre_cat.tex}

\end{longtable}
}

% \begin{landscape}
% \begin{figure}[H]
% \caption{Estimación de $\lambda$ para enfermedades catastróficas}
% \centering
% \includegraphics[scale=1.0]{graficos/iess_lambda_catas.png}
% \caption*{\scriptsize  Elaborado: DAIE.}
% \end{figure}
% \end{landscape}

%---------------------------------------------------------------------------------------------------
\section{Infraestructura sanitaria del SGSIF}
\label{chap_perfil:infraestructura}
De acuerdo al marco jurídico vigente los servicios de salud del Instituto Ecuatoriano de Seguridad
Social (IESS) forman parte del sistema de salud ecuatoriano. El Seguro General de Salud Individual y
Familiar es uno de los seguros especializados del Instituto Ecuatoriano de Seguridad Social. Protege
al asegurado y su familia en las contingencias de enfermedad y maternidad. Los asegurados son
beneficiarios de acciones integrales de fomento y promoción de la salud, prevención, diagnóstico y
tratamiento de enfermedades no profesionales, recuperación y rehabilitación de la salud individual.
El afiliado y afiliada  tienen derecho a:
\begin{itemize}
\item Asistencia médica integral,
\item Exámenes de diagnósticos,
\item Atención médica clínica,
\item Asistencia quirúrgica,
\item Rehabilitación,
\item Dotación de implementos farmacéuticos,
\item Subsidio monetario cuando la enfermedad produce incapacidad en el trabajo.
\end{itemize}
Mediante las unidades médicas, el Seguro General de Salud Individual y Familiar (SGSIF) provee
atención integral de salud a los afiliados y beneficiarios del IESS en las áreas de consulta
externa, emergencia y hospitalización \cite{normas_manuales} (vea la tabla
\ref{tab:iess_unidades_medicas_sal}).

{\fontsize{8}{10}\selectfont
%\scalebox{0.4}{
\begin{longtable}[H]{crlcc}
  \caption{Unidades médicas del IESS}\\
  \label{tab:iess_unidades_medicas_sal}\\
  \toprule
  No. & Nivel & Unidad médica & Provincia & Ciudad\\
  \midrule
  \endfirsthead

  \toprule
  No. & Nivel & Unidad médica & Provincia & Ciudad\\
  \midrule
  \endhead

  \bottomrule
  \multicolumn{5}{r}{continúa...} \\
  \endfoot

  \bottomrule
  \caption*{\scriptsize  Elaborado: DAIE.}
  \endlastfoot
  \multicolumn{5}{c}{\textbf{REGIONAL SGSIF 1: Esmeraldas, Pichincha y Santo Domingo de los Tsáchilas}} \\
    \midrule
    1     & III   & Hospital Carlos Andrade Marín & Pichincha & Quito \\
    2     & II    & Hospital San Francisco de Quito & Pichincha & Quito \\
    3     & II    & Hospital IESS Quito Sur & Pichincha & Quito \\
    4     & II    & Hospital de Esmeraldas & Esmeraldas & Esmeraldas \\
    5     &       & CAA Central Quito & Pichincha & Quito \\
    6     &       & CAA Chimbacalle & Pichincha & Quito \\
    7     &       & CAA Cotocollao & Pichincha & Quito \\
    8     &       & CAA El Batán & Pichincha & Quito \\
    9     &       & CAA Santo Domingo & Santo Domingo de los Tsáchilas & Santo Domingo de los Colorados \\
    10    &       & CAA San Juan & Pichincha & Quito \\
    11    &       & UAA Amaguaña & Pichincha & Amaguaña \\
    12    &       & UAA Cayambe & Pichincha & Cayambe \\
    13    &       & UAA La Ecuatoriana & Pichincha & Quito \\
    14    &       & UAA Sur Occidental & Pichincha & Quito \\
    15    &       & UAA Sangolquí & Pichincha & Sangolquí \\
    16    &       & UAA Tabacundo & Pichincha & Tabacundo \\
    17    &       & UAA San Lorenzo & Esmeraldas & San Lorenzo \\
    18    &       & UAA Machachi & Pichincha & Machachi \\
    \midrule
    \multicolumn{5}{c}{\textbf{REGIONAL SGSIF 2: Galápagos, Guayas, Los Ríos, Sta. Elena}} \\
    \midrule
    19    & III   & Hospital Teodoro Maldonado Carbo & Guayas & Guayaquil \\
    20    & II    & Hospital los Ceibos & Guayas & Guayaquil \\
    21    & II    & Hospital de Babahoyo & Los Ríos & Babahoyo \\
    22    & I     & Hospital de Durán & Guayas & Durán \\
    23    & I     & Hospital de Milagro (Dr. Federico Bolaños Moreira) & Guayas & Milagro \\
    24    & I     & Hospital de Ancón & Santa Elena & Ancón \\
    25    &       & CAA Central Guayaquil 6 & Guayas & Guayaquil \\
    26    &       & Hospital del Día (Dr. Efrén Jurado López) & Guayas & Guayaquil \\
    27    &       & CAA La Libertad 29 & Santa Elena & Santa Elena \\
    28    &       & CAA Letamendi Guayaquil 24 & Guayas & Guayaquil \\
    29    &       & CAA Norte Tarqui Guayaquil & Guayas & Guayaquil \\
    30    &       & CAA Quevedo 40 & Los Ríos & Quevedo \\
    31    &       & CAA Sur Valdivia Guayaquil & Guayas & Guayaquil \\
    32    &       & UAA Balzar & Guayas & Balzar \\
    33    &       & UAA Bucay & Guayas & Bucay \\
    34    &       & UAA Daule & Guayas & Daule \\
    35    &       & UAA El Empalme & Guayas & El Empalme \\
    36    &       & UAA Naranjal & Guayas & Naranjal \\
    37    &       & UAA San Cristóbal - Pto. Baquerizo & Galápagos & Puerto Baquerizo Moreno \\
    38    &       & UAA Santa Cruz - Pto. Ayora & Galápagos & Puerto Ayora \\
    39    &       & UAA Ventanas & Los Ríos & Ventanas \\
    40    &       & UAA Vinces & Los Ríos & Vinces \\
    \midrule
    \multicolumn{5}{c}{\textbf{REGIONAL SGSIF 3: Azuay, Cañar, Morona Santiago}} \\
    \midrule
    41    & III   & Hospital José Carrasco Arteaga & Azuay & Cuenca \\
    42    &       & CAA H.D. La Troncal & Cañar & Azogues \\
    43    &       & CAA Central Cuenca & Azuay & Cuenca \\
    44    &       & CAA H.D. de Azogues & Cañar & Azogues \\
    45    &       & UAA de Cañar & Cañar & Azogues \\
    46    & I     & CAA H.D. de Macas & Morona Santiago & Macas \\
    47    &       & UAA Sucúa & Morona Santiago & Sucúa \\
    48    &       & UAA Gualaquiza & Morona Santiago & Gualaquiza \\
    \midrule
    \multicolumn{5}{c}{\textbf{REGIONAL SGSIF 4: Cotopaxi, Napo, Pastaza, Tungurahua}} \\
    \midrule
    49    & II    & Hospital de Ambato & Tungurahua & Ambato \\
    50    & II    & Hospital de Latacunga & Cotopaxi & Latacunga \\
    51    & I     & Hospital de Puyo & Pastaza & Puyo \\
    52    &       & UAA Baños & Tungurahua & Baños \\
    53    &       & UAA Píllaro & Tungurahua & Píllaro \\
    54    &       & CAA H.D. Tena & Napo  & Tena \\
    \midrule
    \multicolumn{5}{c}{\textbf{REGIONAL SGSIF 5: Bolívar, Chimborazo}} \\
    \midrule
    55    & II    & Hospital de Riobamba & Chimborazo & Riobamba \\
    56    & I     & Hospital de Guaranda & Bolívar & Guaranda \\
    57    &       & CAA Alausí & Chimborazo & Alausí \\
    58    &       & UAA Chunchi & Chimborazo & Chunchi \\
    59    &       & UAA Parque Industrial & Chimborazo & Riobamba \\
    60    &       & UAA San Miguel de Bolívar & Bolívar & San Miguel \\
    \midrule
    \multicolumn{5}{c}{\textbf{REGIONAL SGSIF 6: Manabí}} \\
    \midrule
    61    & II    & Hospital de Portoviejo & Manabí & Portoviejo \\
    62    & II    & Hospital de Manta & Manabí & Manta \\
    63    & I     & Hospital de Chone & Manabí & Chone \\
    64    &       & CAA Bahía de Caráquez & Manabí & Bahía de Caraquez \\
    65    &       & CAA Jipijapa & Manabí & jipijapa \\
    66    &       & UAA Calceta & Manabí & Calceta \\
    67    &       & UAA El Carmen & Manabí & El Carmen \\
    68    &       & UAA Los Esteros Manta & Manabí & Manta \\
    69    &       & UAA Paján & Manabí & Paján \\
    70    &       & UAA Portoviejo & Manabí & Portoviejo \\
    \midrule
    \multicolumn{5}{c}{\textbf{REGIONAL SGSIF 7: Loja, Zamora Chinchipe}} \\
    \midrule
    71    & II    & Hospital Manual Ignacio Monteros & Loja  & Loja \\
    72    &       & CAA H.D. Central Loja & Loja  & Loja \\
    73    &       & CAA H.D. Zamora & Zamora Chinchipe & Zamora \\
    74    &       & UAA Cariamanga & Loja  & Cariamanga \\
    75    &       & UAA Celica & Loja  & Celica \\
    76    &       & UAA Macará & Loja  & Macará \\
    77    &       & UAA Paltas & Loja  & Catacocha \\
    78    &       & UAA Catamayo & Loja  & Catamayo \\
    79    &       & UAA Zumba & Zamora Chinchipe & Zumba \\
    \midrule
    \multicolumn{5}{c}{\textbf{REGIONAL SGSIF 8: Carchi, Imbabura, Orellana, Sucumbíos}} \\
    \midrule
    80    & II    & Hospital de Ibarra & Imbabura & Ibarra \\
    81    &       & CAA Nueva Loja & Sucumbíos & Nueva Loja (Lago Agrio) \\
    82    &       & CAA Otavalo & Imbabura & Otavalo \\
    83    &       & CAA Tulcán & Carchi & Tulcán \\
    84    &       & UAA Atuntaqui & Imbabura & Atuntaqui \\
    85    &       & UAA Cotacachi & Imbabura & Cotacachi \\
    86    &       & UAA El Ángel & Carchi & El Ángel \\
    87    &       & UAA El Coca & Orellana & El Coca \\
    88    &       & UAA San Gabriel & Carchi & San Gabriel \\
    \midrule
    \multicolumn{5}{c}{\textbf{REGIONAL SGSIF 9: El Oro}} \\
    \midrule
    89    & II    & Hospital de Machala & El Oro & Machala \\
    90    &       & CAA de Piñas & El Oro & Piñas \\
    91    &       & UAA de Pasaje & El Oro & Pasaje \\
    92    &       & UAA Huaquillas & El Oro & Piñas \\
    93    &       & UAA de Portovelo & El Oro & Portovelo \\
    94    &       & UAA de Santa Rosa & El Oro & Santa Rosa \\
    95    &       & UAA de Zaruma & El Oro & Zaruma \\

  \end{longtable}
}

Unidad de Atención Ambulatoria \hspace{2cm} UAA\\
Centro de Atención Ambulatoria \hspace{5cm} CAA\\
Centro de Atención Ambulatoria y Hospital del Día \hspace{1.8cm} CAA H.D.\\
Hospital I \hspace{8.9cm} Nivel I\\
Hospital II \hspace{8.8cm} Nivel II\\
Hospital III \hspace{8.7cm} Nivel III

Pretendemos analizar la distribución y los determinantes de estados o eventos relacionados con la
salud y expresar la carga de enfermedad de la población afiliada.  Para lograr este objetivo
identificamos las características esenciales de salud en términos de morbilidad, mortalidad e
indicadores de salud asociados a la ocurrencia de eventos y su impacto \cite{Who_adjust_life_year}.

% %---------------------------------------------------------------------------------------------------
% \chapter[Proyecciones demográficas]{Proyecciones demográficas}
% \label{chp_proy_demog_finan}
% %--------------------------------------------------------------------------------------------------
% % 
% \section{Supuestos demográficos}
%  
%  Se propone incrementar la tasa de cobertura de manera progresiva desde el año 2021 a 2060, hasta alcanzar un máximo de \Sexpr{REP$max_tasa_cob}\% respecto de la PEA en el año 2060. Con este supuesto sobre la tasa de cobertura se obtiene un crecimiento del \Sexpr{REP$media_crecimiento_afi_act}\% del número de afiliados de ambos sexos al Seguro General Obligatorio en el horizonte de proyección.
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Supuesto: tasa de cobertura sobre la fuerza laboral (PEA), ambos sexos, 2020 en adelante}
% \label{fig:iess_tcv}
% \includegraphics[ scale = 0.8 ]{graficos/iess_tcv.png}
% \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% % 
% % %--------------------------------------------------------------------------------------------------
% \section{Proyecciones demográficas}
% % 
% % La carga pensional se proyecta de \Sexpr{REP$cap_2021} en el año 2021 y baja paulatinamente durante el período de proyección, ubicándose en \Sexpr{REP$cap_2060} para el año 2060. Los resultados se pueden observar en la figura \ref{fig:iess_carga_pen}.
% % % 
% % \begin{figure}[H]
% % \centering
% % \captionsetup{justification=centering}
% % \caption{Evolución de la carga pensional}
% % \label{fig:iess_carga_pen}
% % \includegraphics[ scale = 0.9 ]{graficos/iess_carga_pen.png}
% % \caption*{\scriptsize {\bf Fuente:} Elaborada con datos administrativos del IESS. \\
% % {\bf Elaborado:} DAIE.}
% % \end{figure}
% % \vspace*{-0.5cm}
% %
% 
% En las figuras \ref{fig:iess_act_inac_f}, \ref{fig:iess_act_inac_m} y \ref{fig:iess_fuerzat_m_f} se muestra las proyecciones de los afiliados activos e inactivos, por sexo, para el período 2021 a 2060. Se observa que el número de activos de sexo femenino es superior a los afiliados inactivos; para el sexo masculino, en los primeros años de proyección es mayor el número de afiliados inactivos. En el año 2020, la proporción de afiliados activos fue de \Sexpr{REP$pcjact_2020}\% y la de inactivos, fue de \Sexpr{REP$pcjinact_2020}\%. Para el año 2060 se proyecta una proporción de \Sexpr{REP$pcjact_2060} para activos y \Sexpr{REP$pcjinact_2060} para inactivos.
% 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Número proyectado de cotizantes activos e inactivos, por año, sexo femenino, en millones de personas}
% \label{fig:iess_act_inac_f}
% \includegraphics[ scale = 0.85 ]{graficos/iess_act_inac_f.png}
% \caption*{\scriptsize {\bf Fuente:} Proyecciones. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% % 
% \vspace*{-0.7cm}
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Número proyectado de cotizantes activos e inactivos, por año, sexo masculino, en millones de personas}
% \label{fig:iess_act_inac_m}
% \includegraphics[ scale = 0.85 ]{graficos/iess_act_inac_m.png}
% \caption*{\scriptsize {\bf Fuente:} Proyecciones. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% % 
% La evolución, en el período de análisis, de la fuerza de trabajo y el total de afiliados activos para ambos sexos se muestra en la figura \ref{fig:iess_fuerzat_m_f}; se puede observar un crecimiento constante de las proyecciones. La fuerza de trabajo en el año 2020 fue de \Sexpr{REP$FL_2020}, mientras que el total de cotizantes activos fueron \Sexpr{REP$AFI_2020}, que representa el \Sexpr{REP$FL_AFI_2020}\%; en el año 2060 se estima \Sexpr{REP$FL_2060}
% personas en la fuerza de trabajo y \Sexpr{REP$AFI_2060} cotizantes activos, los cuales representan el \Sexpr{REP$FL_AFI_2060}\%.
% % 
% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Proyección de la fuerza de trabajo y del total de cotizantes activos por año, ambos sexos, en millones de personas}
% \label{fig:iess_fuerzat_m_f}
% \includegraphics[ scale = 0.80 ]{graficos/iess_fuerzat_m_f.png}
% \caption*{\scriptsize {\bf Fuente:} Proyecciones. \\
% {\bf Elaborado:} DAIE.}
% \end{figure}
% 
% % \vspace*{-0.5cm}
% % En la figura \ref{fig:iess_pen_jv} se observa la proyección del número de pensionistas de vejez, de ambos sexos, para el período 2021 a 2060; se observa un incremento gradual en el horizonte de proyección. El número de mujeres pensionistas de vejez, proyectadas para el periodo 2021 es de \Sexpr{REP$jv_f}, y el número de hombres es de \Sexpr{REP$jv_m}; el número de mujeres aumenta a \Sexpr{REP$jv_f_2060} en el año 2060 y el de hombres a \Sexpr{REP$jv_m_2060}.
% % % 
% % \begin{figure}[H]
% % \centering
% % \captionsetup{justification=centering}
% % \caption{Proyección: evolución del número de pensionistas de vejez, por año, ambos sexos, en miles de personas}
% % \label{fig:iess_pen_jv}
% % \includegraphics[ scale = 0.7 ]{graficos/iess_pen_jv.png}
% % \caption*{\scriptsize {\bf Fuente:} Proyecciones. \\
% % {\bf Elaborado:} DAIE.}
% % \end{figure}
% % 
% % \vspace{-.7cm}
% % 
% % En la gráfica \ref{fig:iess_pen_inv} se muestra la evolución (2012-2060) del número de pensionistas por invalidez-discapacidad (ambos sexos, incluidas las proyecciones), y se percibe un aumento constante desde 2012 hasta el 2020; asimismo, se observa que el número de pensiones de los hombres supera al de las mujeres en 2020. Para las mujeres, fueron registradas \Sexpr{REP$dis_f_2010} pensiones en 2010, \Sexpr{REP$dis_f_2020} en 2020 y \Sexpr{REP$dis_f_2060} en 2060. Para los hombres, \Sexpr{REP$dis_m_2010} en 2010, \Sexpr{REP$dis_m_2020} en 2020 y \Sexpr{REP$dis_m_2060} en 2060.
% % \vspace{-0.5cm}
% % % 
% % \begin{figure}[H]
% % \centering
% % \captionsetup{justification=centering}
% % \caption{Proyección: evolución del número de pensionistas de invalidez, por año, ambos sexos, en miles de personas}
% % \label{fig:iess_pen_inv}
% % \includegraphics[ scale = 0.7 ]{graficos/iess_pob_dis.png}
% % \caption*{\scriptsize {\bf Fuente:} Proyecciones. \\
% % {\bf Elaborado:} DAIE.}
% % \end{figure}
% % 
% % \vspace*{-0.7cm}
% % En el caso de las pensiones de viudez, el número de mujeres (\Sexpr{REP$viu_f_2012} en 2012; \Sexpr{REP$viu_f_2020} en 2020 y \Sexpr{REP$viu_f_2060} en 2060) sigue siendo bastante más alto que el correspondiente a los hombres (\Sexpr{REP$viu_m_2012} en 2012, \Sexpr{REP$viu_m_2020} en 2020 y \Sexpr{REP$viu_m_2060} en 2060) durante todo el período de proyección, como muestra la gráfica \ref{fig:iess_pob_viu}.
% % 
% % \begin{figure}[H]
% % \centering
% % \captionsetup{justification=centering}
% % \caption{Proyección: evolución del número de pensionistas de viudez, por año, ambos sexos, en miles de personas}
% % \label{fig:iess_pob_viu}
% % \includegraphics[ scale = 0.8 ]{graficos/iess_pob_viu.png}
% % \caption*{\scriptsize {\bf Fuente:} Proyecciones. \\
% % {\bf Elaborado:} DAIE.}
% % \end{figure}
% % % 
% % La gráfica \ref{fig:iess_pob_orf} muestra la evolución del número de pensiones de orfandad. El número de pensionistas en 2012 fue \Sexpr{REP$orf_m_2012} hombres y \Sexpr{REP$orf_f_2012} mujeres; y en 2020, \Sexpr{REP$orf_m_2020} hombres y \Sexpr{REP$orf_f_2020} mujeres. Ese número tiende a converger hacia el final del período de proyección (2060), año para el cual se prevén \Sexpr{REP$orf_m_2060} hombres y \Sexpr{REP$orf_f_2060} mujeres.
% % % 
% % % 
% % \begin{figure}[H]
% % \centering
% % \captionsetup{justification=centering}
% % \caption{Proyección: evolución del número de pensionistas de orfandad, por año, ambos sexos, en miles de personas}
% % \label{fig:iess_pob_orf}
% % \includegraphics[ scale = 0.8 ]{graficos/iess_pob_orf.png}
% % \caption*{\scriptsize {\bf Fuente:} Proyecciones. \\
% % {\bf Elaborado:} DAIE.}
% % \end{figure}
% % \vspace*{-0.7cm}
% % En la gráfica \ref{fig:iess_nuevos_pensi} se muestra la evolución del número de nuevos pensionistas por tipo. Se observa que las pensiones de vejez representan alrededor del 61\% al inicio del período, porcentaje que crece hasta 85\% al final de la proyección.
% % % 
% % \begin{figure}[H]
% % \centering
% % \captionsetup{justification=centering}
% % \caption{Proyección: nuevos pensionistas por tipo, ambos sexos, miles de personas}
% % \label{fig:iess_nuevos_pensi}
% % \includegraphics[ scale = 0.8 ]{graficos/iess_nuevos_pensi.png}
% % \caption*{\scriptsize {\bf Fuente:} Proyecciones. \\
% % {\bf Elaborado:} DAIE.}
% % \end{figure}
% % % 
% % En el período de proyección, el número de hombres pensionistas como proporción de la población total de 60 años o más supera ligeramente a las mujeres (gráfica \ref{fig:iess_pob_cob}).
% % % 
% % \begin{figure}[H]
% % \centering
% % \captionsetup{justification=centering}
% % \caption{Proyección: pensiones de vejez:tasa de cobertura (60 años o más), por año, ambos sexos}
% % \label{fig:iess_pob_cob}
% % \includegraphics[ scale = 0.8 ]{graficos/iess_pob_cob.png}
% % \caption*{\scriptsize {\bf Fuente:} Proyecciones. \\
% % {\bf Elaborado:} DAIE.}
% % \end{figure}
% 
% % La siguiente tabla demuestra la evolución de la población afiliada, por consiguiente, de la masa
% % salarial, desde el año 2005 hasta el 2018 desde el año 2005 hasta el 2018.
% % \begin{table}[H]
% % \centering
% % \caption{Evolución de afiliados contributivos y masa salarial}
% % \label{tab:iess_afi_ms_sal}%
% % %\scalebox{0.8}{
% % {\fontsize{10}{12}\selectfont
% % %\scalebox{0.8}{
% % %\resizebox{\columnwidth}{!}{%
% % \begin{tabular}{*{7}{r}}
% % \toprule
% % Año   & Afiliados &Variación        & Porcentaje de  &    Masa   & Porcentaje de & Porcentaje de\\
% %       &           &   de afiliados  &  Crecimiento   & salarial  & Crecimiento   & Crecimiento  \\
% % \midrule
% % \input{tablas/iess_afi_ms_sal.tex}
% % \bottomrule
% % \end{tabular} }
% % \caption*{\scriptsize Fuente:  \\Elaborado: DAIE.}
% % \end{table}
% 
% 
% % \begin{figure}[H]
% % \centering
% % \caption{ Egresos hospitalarios de  las unidades médicas del IESS según la provincia de residencia
% % del paciente}
% % \label{tab:iess_map_egresos_hospitalarios_sal}
% % \includegraphics[scale=1.0]{graficos/iess_map_egresos_hospitalarios_sal.png}
% % \caption*{\scriptsize Elaborado: DAIE.}
% % \end{figure}
% %
% % \begin{figure}[H]
% % \centering
% % \caption{Egresos hospitalarios según la provincia de ubicación de la unidad médica del IESS}
% % \label{tab:iess_map_egresos_ubicacion_sal}
% % \includegraphics[scale=1.0]{graficos/iess_map_egresos_ubicacion_sal.png}
% % \caption*{\scriptsize Elaborado: DAIE.}
% % \end{figure}
% %
% % \begin{figure}[H]
% % \centering
% % \caption{Mortalidad hospitalaria promedio para el período 2012-2018 por provincia de ubicación del
% % establecimiento}
% % \label{tab:iess_map_morbilidad_sal}
% % \includegraphics[scale=1.0]{graficos/iess_map_morbilidad_sal.png}
% % \caption*{\scriptsize Elaborado: DAIE.}
% % \end{figure}
% %
