%---------------------------------------------------------------------------------------------------
\chapter[Análisis de la información financiera y contable con sus tendencias]{Análisis de la
información financiera y contable con sus tendencias}
\label{chp_infofinan}

En este capítulo se presenta un análisis de las principales cuentas del balance al último ejercicio económico: total de activos, reservas, ingresos por aportes, otros ingresos, egresos por pago de beneficios y prestaciones, otros egresos, entre otros.

Cabe mencionar que los balances del IESS en el período 2010 al 2020 han sufrido cambios en los códigos de cuentas, creación de cuentas, signo negativo para la representación del pasivo, patrimonio e ingresos; por tanto los balances financieros no son consistentes y comparables. Sin embargo, por razones técnicas y de análisis se estandarizó la data con números absolutos para todo el capítulo.

% Activos contables --------------------------------------------------------------------------------
\section{Total de activos contables}
\label{chp_infofinan:activos}

A continuación, en la tabla \ref{tab:iess_activo_ivm} y figura \ref{fig:iess_activo_ivm} se presenta la evolución del activo contable del fondo del IVM para el período 2010 al 2020.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución del Activo del Fondo de IVM a 31 de diciembre de cada año (En millones de dólares)}
\label{tab:iess_activo_ivm}
{%\fontsize{9}{10} 
\selectfont
\begin{tabular}{cccc}
\toprule
    Año	& Activo  & Incremento & Incremento  \\
        &         &    anual   & porcentual anual \\
  \midrule
  \input{tablas/iess_activo_ivm.tex}
  \bottomrule
  
\multicolumn{4}{c}{\begin{tabular}[c]{@{}c@{}}{\bf Fuente:} Balance General Consolidado por \\Fondos Administrados de los Fondos Especializados-DNGF.\end{tabular}} \\
\multicolumn{4}{c}{\textbf{Elaborado:} DAIE.}

\end{tabular}
}
\end{table}


\begin{figure}[H]
\centering 
\captionsetup{justification=centering}
\caption{Evolución del Activo del Fondo de IVM a 31 de diciembre de cada año (En millones de dólares)}
\label{fig:iess_activo_ivm}
\includegraphics[scale=1]{graficos/iess_activo_ivm.png}
\caption*{\scriptsize {\bf Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
  {\bf Elaborado:} DAIE.}

\end{figure}

Se observa que los activos entre el año 2020 con respecto al 2010 mantuvo una tasa de crecimiento de 75,95\%, pasando de USD. 4.743,41 millones a USD. 8.345,91 millones; es decir se incrementó en un 5,81\% en promedio (geométrico) anual.

El año 2019 represento la tasa de crecimiento más alta del período con el 27,47\%, con una diferencia de USD. 1.847,81 respecto al año anterior debido a la cuenta “Fondos Disponibles”; mientras que la variación negativa más significativa corresponde al año 2018 con una tasa de -14,48\%, misma que pasó de USD. 7.866,17 millones a USD. 6.726,77 millones.

En el anexo \ref{chap_activos_contables} se presenta los componentes del activo, el análisis horizontal y vertical del activo.

\subsection{Inversiones}
\label{chp_infofinan:inversiones}

La cuenta más representativa del activo son las inversiones, misma que representa en promedio el 76,79\% del total de los activos en el período analizado. Estos recursos son administrados por el BIESS cuyo análisis se presenta en la sección \ref{chp_infofinan:rentablidad}.

\subsection{Cuentas por cobrar}
\label{chp_infofinan:cta_x_cobrar}

De acuerdo a la recomendación No. 4 literal a del Informe No. DNA7-0036-2018 del Examen Especial “A la preparación, ejecución, aprobación y aplicación de los estudios actuariales en el Instituto Ecuatoriano de Seguridad Social IESS y entidades relacionadas”, por el período comprendido entre el 1 de enero de 2012 y el 31 de diciembre de 2017, se procede analizar las cuentas por cobrar.

Debido a la optimización generada en el Plan de Cuentas, para el presente análisis se unificó los valores de “Deuda de Gobierno” de los años 2010 a 2012 como parte de “Cuentas por Cobrar” toda vez que a partir del año 2013 fueron agrupadas; es así que en la tabla \ref{tab:iess_cuentas_cobrar_ivm} y en la figura \ref{fig:iess_cuentas_cobrar_ivm} se presenta la evolución del período 2010 al 2020.

\begin{table}[H]
  \centering 
  \captionsetup{justification=centering}
  \caption{Cuentas por cobrar del Fondo de IVM a 31 de diciembre de cada año}
  \label{tab:iess_cuentas_cobrar_ivm}
  {\fontsize{9}{10} 
  \selectfont
  \begin{tabular}{rrrr}
    \toprule
    Año	& Cuentas por & Incremento anual & Incremento  \\
        & cobrar      &                  & porcentual anual \\
    \midrule
    \input{tablas/iess_cuentas_cobrar_ivm.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{\scriptsize {\bf Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
  {\bf Elaborado:} DAIE.}
 
\end{table}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Cuentas por cobrar del Fondo de IVM a 31 de diciembre de cada año (En millones de dólares)}
\label{fig:iess_cuentas_cobrar_ivm}
\includegraphics[scale=.8]{graficos/iess_cuentas_cobrar_ivm.png}
\caption*{\scriptsize {\bf Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
  {\bf Elaborado:} DAIE.}

\end{figure}



Se observa que las “Cuentas por Cobrar” correspondientes al 2020 con respecto al 2010 incrementaron en un 69,21\%, es decir crecieron en promedio (geométrico) anual en 5,40\%; siendo el año 2019 el punto más alto con un crecimiento de USD. 1.381,62 millones respecto al año anterior, debido al aumento de USD. 1.374.747.331,38 por concepto de la subcuenta “Deuda de Gobierno”. Caso contrario sucede en el año 2012 con la tasa de decrecimiento más significativa del período en -57,09\%, pasando de USD. 1.926,61 millones a USD. 826,65 millones.

Así, tenemos que el 62,07\% representa la Deuda de Gobierno por 40\% del total de las cuentas por cobrar al 31 de diciembre de 2020.


\subsubsection{Deuda de Gobierno}

Debido a la importancia de la cuenta “Deuda de Gobierno” y considerando que la DAIE no cuenta con la desagregación de los asientos contables de las cuentas establecidas en los balances financieros, con fecha 26 de julio del 2021 el Actuario solicitó a la Subdirección Nacional Financiera del Sistema de Pensiones (SDNFSP) se asigne una delegado técnico, el cual trabaje en conjunto con la DAIE.

Ante lo expuesto, en reuniones mantenidas entre la SDNFSP y la DAIE se solicitó se remita el valor y porcentaje correspondiente al 40\% de la Deuda que el Gobierno mantiene con el Fondo de pensiones; información que fue entregada por correo institucional con fecha 02 de agosto del 2021 a la DAIE, misma que se detalla a continuación.\footnote{Los valores expuestos en el documento han sido remitidos por la unidad de negocio, misma que manifestaron que la Deuda de Gobierno considera solo el capital mas no los intereses (no se conoce el modo ni el plazo de pago). Mientras que la deuda que mantenía el Estado los años anteriores al 2012 sí consideró el capital más los intereses, la cual se le conoce como deuda consolidada, existiendo convenio de pago para la misma que se ha dado cumplimiento, por tal motivo no se considera en el documento.}



%---------------------------- inicio tabla
\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Detalle de las cuentas por cobrar correspondiente al 40\% de la Deuda de Gobierno correspondiente al período 2012-2020}
\scalebox{0.8}{
\begin{tabular}{rrrr}
\hline
Código                     & Cuenta Contable                              & \multicolumn{2}{c}{2012 - 2020 }         \\ \hline
\multirow{4}{*}{715050131} & \multirow{4}{*}{40\% Pens. Invalidez}        & Deuda de Gobierno  & USD 256.254.622,31   \\
                           &                                              & Valores Cancelados & USD 208.947.154,94   \\
                           &                                              & Diferencia         & USD 47.307.467,37    \\
                           &                                              & \% cumplimiento    & 81,54\%            \\ \hline
\multirow{4}{*}{715050132} & \multirow{4}{*}{40\% Pens. Vejez}            & Deuda de Gobierno  & USD 4.339.463.307,09 \\
                           &                                              & Valores Cancelados & USD 3.461.906.826,06 \\
                           &                                              & Diferencia         & USD 877.556.481,03   \\
                           &                                              & \% cumplimiento    & 79,78\%            \\ \hline
\multirow{4}{*}{715050133} & \multirow{4}{*}{40\% Pens. Montepio}         & Deuda de Gobierno  & USD 667.832.219,86   \\
                           &                                              & Valores Cancelados & USD 517.494.332,16   \\
                           &                                              & Diferencia         & USD 150.337.887,70   \\
                           &                                              & \% cumplimiento    & 77,49\%            \\ \hline
\multirow{4}{*}{715050134} & \multirow{4}{*}{40\% De 10Ma. 3Era. Pensión} & Deuda de Gobierno & USD 418.242.381,59 \\
                           &                                              & Valores Cancelados & USD 297.095.696,92   \\
                           &                                              & Diferencia         & USD 121.146.684,67   \\
                           &                                              & \% cumplimiento    & 71,03\%            \\ \hline
\multirow{4}{*}{715050135} & \multirow{4}{*}{40\% De 10Ma. 4Ta. Pensión}  & Deuda de Gobierno  & USD 301.866.397,91   \\
                           &                                              & Valores Cancelados & USD 246.808.320,70   \\
                           &                                              & Diferencia         & USD 55.058.077,21    \\
                           &                                              & \% cumplimiento    & 81,76\%            \\ \hline
\multirow{4}{*}{715050186} & \multirow{4}{*}{40\% Pens. Ley Discapacidad} & Deuda de Gobierno  & USD 58.721.852,65    \\
                           &                                              & Valores Cancelados & USD 544.282,35       \\
                           &                                              & Diferencia         & USD 58.177.570,30    \\
                           &                                              & \% cumplimiento    & 0,93\%             \\ \hline
\multicolumn{4}{c}{{\bf Fuente:} Subdirección   Nacional Financiera del Sistema de Pensiones.}                            \\
\multicolumn{4}{c}{{\bf Elaborado:} DAIE.}
\end{tabular}
}
\label{tab:iess_deuda_gobierno_ivm}
\end{table}




%---------------------------- fin tabla
Como se evidencia en la tabla \ref{tab:iess_resumen_deuda} la deuda de gobierno se encuentra conformada por seis cuentas que hace referencia al 40\% por pensiones de invalidez, vejez, montepío, décima tercera y cuarta pensión y ley de discapacidad; los valores y porcentajes presentados corresponden al período comprendido entre el año 2012 al 2020.

\begin{table}[H]
\centering 
\captionsetup{justification=centering}
\caption{Resumen 40\% Deuda de Gobierno período 2012 – 2020}
\label{tab:iess_resumen_deuda}
\begin{tabular}{r r}
\toprule
Ítem & USD\\
\midrule
Deuda de Gobierno &  6.042.380.781,41\\
Valores Cancelados& 4.732.796.613,13\\
Diferencia        & 1.309.584.168,28\\
\% Cumplimiento (40\%)& 31,33\%\\
\% Faltante (40\%)    & 8,67\%\\
\bottomrule
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Subdirección Nacional Financiera del Sistema de Pensiones. \\
{\bf Elaborado:} DAIE.}

\end{table}

Como se observa en el resumen en el período analizado la deuda de gobierno (40\%) representaba USD. 6.042,38 millones, mientras que los valores cancelados fueron por  USD. 4.732,79 millones, es decir, se adeuda aún USD. 1.309,58 millones.


%-----------------------------------------------------------------------------------------------
\section{Total de pasivos contables}
\label{chp_infofinan:activos}

En la tabla \ref{tab:iess_pasivo_ivm} y figura \ref{fig:iess_pasivo_ivm} se presenta la evolución del pasivo contable del fondo del IVM por el período 2010 al 2020.

\begin{table}[H]
\centering 
\captionsetup{justification=centering}
 \caption{Pasivo del Fondo de IVM al 31 de diciembre de cada año}
  \label{tab:iess_pasivo_ivm}

 {\selectfont
 \begin{tabular}{rrrr}
 \toprule
 Año	& Pasivo & Incremento anual & Incremento \\
 &        &                  & porcentaje anual \\
 \midrule
 \input{tablas/iess_pasivo_ivm.tex}
  \bottomrule
  \end{tabular}
 }
 \caption*{\scriptsize {\bf Fuente:} Balance General Consolidado por Fondos Administrados
 de los  Fondos Especializados-DNGF. \\
 {\bf Elaborado:} DAIE.}
 \end{table}


 \begin{figure}[H]
\centering 
\captionsetup{justification=centering}
\caption{Pasivo del Fondo de IVM al 31 de diciembre de cada año (En millones de dólares)}
 \label{fig:iess_pasivo_ivm}
 \includegraphics[scale=1]{graficos/iess_pasivo_ivm.png}

 \caption*{\scriptsize {\bf Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\{\bf Elaborado:} DAIE.}

 \end{figure}

 Se observa que los pasivos correspondientes al 2020 con respecto al 2010 decrecieron en un -43,25\%, pasando de USD. 826,86 millones a USD. 469,25 millones; es decir, el decremento promedio (geométrico) anual fue del -5,51\%. Desde el 2010 hasta el 2015 se observa un decrecimiento del pasivo; sin embargo a partir del 2016 inicia un crecimiento paulatino, siendo el pico más alto en el año 2019 con una tasa de crecimiento del 505,30\% respecto al año anterior, lo que representó USD. 927,59 millones de diferencia, debido al incremento en la subcuenta “proveedores públicos por pagar”  por un valor de USD. 297,42 millones.

Cabe mencionar que en el año 2020 se evidencia una tasa de variación negativa del -57,77\%, misma que paso de USD. 1.111,15 millones a USD. 469,25 millones; aquello debido a la disminución de la subcuenta “Proveedores” en USD. 309.479.852,11.


En el anexo \ref{chap_pasivos_contables} se presenta los componentes del pasivo, el análisis horizontal y vertical del pasivo.

%---------------------------------------------------------------
\subsection{Cuentas por pagar}
\label{chp_infofinan:cta_x_pagar}

Observando lo determinado en la recomendación No. 4 literal a del Informe No. DNA7-0036-2018 del Examen Especial “A la preparación, ejecución, aprobación y aplicación de los estudios actuariales en el Instituto Ecuatoriano de Seguridad Social IESS y entidades relacionadas”, por el período comprendido entre el 1 de enero de 2012 y el 31 de diciembre de 2017, se procede analizar las cuentas por pagar.

A continuación, en la tabla \ref{tab:iess_cuentas_pagar_ivm} y la figura \ref{fig:iess_cuentas_pagar_ivm} se presenta la evolución de las cuentas por pagar del fondo del IVM por el período 2010 al 2020.

% Cuentas por pagar -------------------------------------------------------------------------------
\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Cuentas por pagar del fondo de IVM a 31 de diciembre de cada año}
 \label{tab:iess_cuentas_pagar_ivm}
{\selectfont
\begin{tabular}{rrrr}
\toprule
 Año	& Cuentas por & Incremento anual & Incremento  \\
 & pagar       &                  & porcentual anual \\
\midrule
\input{tablas/iess_cuentas_pagar_ivm.tex}
\bottomrule
\end{tabular}
}
 \caption*{\scriptsize {\bf Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
{\bf Elaborado:} DAIE.}

\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Cuentas por pagar del Fondo de IVM a 31 de diciembre de cada año (En millones de dólares)}
\label{fig:iess_cuentas_pagar_ivm}
\includegraphics[scale=1]{graficos/iess_cuentas_pagar_ivm.png}
\caption*{\scriptsize {\bf Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
  {\bf Elaborado:} DAIE.}

\end{figure}

Debido que los balances del IESS en el período 2010-2020 han sufrido cambios en el Plan de Cuentas, es necesario aclarar que para el análisis de las cuentas por pagar la DAIE unificó las partidas. Por cuanto a partir del año 2012 al 2014 se encuentra registrada como “Cuenta por Pagar”, y a partir del año 2015 al 2020 se remplaza por “Pasivos Corrientes”.

Se observa que las “cuentas por pagar” correspondientes al año 2020 con respecto al 2010 decrecieron en -97,12\% en el período analizado, es decir un decremento promedio (geométrico) anual de -29,87\%. Los valores (\$) más altos se efectúan en los años 2011 y 2019 con una tasa de variación del 69,32\% y 7210,63\% respectivamente, siendo el 2019 el más significativo debido a la creación de la subcuenta “Proveedores Públicos Por Pagar”\footnote{Denominada anteriormente “Cuentas por Pagar”, misma que es una subcuenta de los pasivos no corrientes, aquello debido al cambio en el plan de cuentas.} por un valor de USD. 297,42 millones; así como el incremento de USD. 9,33 millones en “Cuentas Por Pagar Sistemas Esp” respecto al año anterior.

Sin embargo, en el año 2020 se evidencia un fuerte decrecimiento del -97,83\% con una diferencia del USD. 296.361.653,29 respecto al año 2019, esto debido a la liquidación de la subcuenta “Proveedores Públicos Por Pagar”; así como la disminución de valores por pago de subcuentas “Beneficiarios Por Pagar” y “Retenciones SRI”.

\section{Patrimonio}
\label{chp_infofinan:patrimonio}

La tabla \ref{tab:iess_patrimonio_ivm} y figura \ref{fig:iess_patrimonio_ivm}, muestra la evolución del patrimonio del fondo de IVM para el período 2010 al 2020.

\begin{table}[H]
  \centering 
  \captionsetup{justification=centering}
  \caption{Patrimonio del \Sexpr{REP_seg} al 31 de diciembre de cada año}
  \label{tab:iess_patrimonio_ivm}
  {\selectfont
  \begin{tabular}{rrrr}
    \toprule
    Año	& Patrimonio	& Incremento anual	& Incremento  \\
        &             &                   & porcentual anual \\
    \midrule
    \input{tablas/iess_patrimonio_ivm.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{\scriptsize {\bf Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
  {\bf Elaborado:} DAIE.}
 
\end{table}

\begin{figure}[H]
\centering 
\captionsetup{justification=centering}
\caption{Patrimonio del Fondo de IVM al 31 de diciembre de cada año (En millones de dólares)}
\label{fig:iess_patrimonio_ivm}
\includegraphics[scale=1]{graficos/iess_patrimonio_ivm.png}
 \caption*{\scriptsize {\bf Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
  {\bf Elaborado:} DAIE.}
\end{figure}


El Patrimonio de IVM mantuvo una tasa de crecimiento del 101,11\% entre el año 2010 al 2020, pasando de USD. 3.916,54 millones a USD. 7.876,66 millones; es decir anualmente crece en promedio (geométrico) en 7,24\%.  Se observa que desde el año 2010 al 2015 el patrimonio ha ido incrementando paulatinamente en promedio (geométrico) anual en 19,54\%; sin embargo a partir del año 2016 se evidencia  disminución de la cuenta año a año hasta el 2018, evidenciando la tasa de decrecimiento más significativa en el 2018 con el -14,24\% una diferencia de USD. 1.086,76 millones respecto al año anterior debido a la Resolución No C.D. 501 de 13 de noviembre de 2015, reformada por la Resolución C.D. 515 de 30 de marzo de 2016, en la que modifica las tasas de cotización; así como la eliminación de la contribución del 40\% del Estado para el pago de las pensiones.



Entre el 2019 y 2020 existe un crecimiento porcentual anual del 14,06\% y del 5,54\% respectivamente, considerado el más alto en el 2019 respecto al año anterior con una diferencia de USD. 920.227.626,27.

En el anexo \ref{chap_patrimonio} se presenta los componentes del patrimonio del Fondo de IVM, el análisis horizontal y vertical del patrimonio.

\section{Ingresos}
\label{chap_ingresos}

En la tabla \ref{tab:iess_ingresos_ivm} y figura \ref{fig:iess_ingresos_ivm}, se presenta la evolución del ingreso del fondo de IVM para el período 2010-2020.


\begin{table}[H]
  \centering
  \captionsetup{justification=centering}
  \caption{Evolución histórica de los Ingresos del Fondo del Seguro de IVM al 31 de diciembre de cada año}
  \label{tab:iess_ingresos_ivm}
  {\selectfont
  \begin{tabular}{rrrr}
    \toprule
    Año  &  Ingresos  & Incremento & Incremento Porcentual \\
         &            & Anual      & Anual                  \\
    \midrule
    \input{tablas/iess_ingresos_ivm.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{\scriptsize {\bf Fuente:} Balance de Resultados Consolidados por Fondos Administrados de los Fondos Especializados - DNGF. \\
  {\bf Elaborado:} DAIE.}
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución del Ingreso del Fondo de IVM al 31 de diciembre de cada año (En millones de dólares)}
\label{fig:iess_ingresos_ivm}
\includegraphics[scale=1]{graficos/iess_ingresos_ivm.png}
 \caption*{\scriptsize {\bf Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
  {\bf Elaborado:} DAIE.}

\end{figure}

El crecimiento de los ingresos del Fondo fue cambiante durante el período analizado, con una tasa de crecimiento del 135,71\%, pasando de USD. 2.090,73 millones en el 2010 a USD. 4.928,14 millones en el 2020; es decir mantuvo un incremento anual promedio (geométrico) de 8,95\%. El mayor incremento interanual se dio en el 2019 con una tasa del 79,52\%, generando una  diferencia de USD. 2.284,63 millones respecto al 2018, debido al incremento en “Ingresos de Operación” en la que se encuentran subcuentas como aportes de afiliados y patronos, contribuciones de estado y otros ingresos de la seguridad social, intereses y multas; mientras que el 2016 registra el mayor decrecimiento con -34,20\%, lo que representa una disminución de USD. 1.168,89 millones respecto al año anterior.

En el anexo \ref{chap_ingresos} se presenta los componentes del patrimonio del Fondo de IVM, el análisis horizontal y vertical de los ingresos.

\section{Egresos Prestacionales y Gastos de Administración}
En la tabla  \ref{tab:iess_egresos_prestacionales_ivm} y figura \ref{fig:iess_egresos_prestacionales_ivm} se presenta la evolución histórica de los egresos prestacionales del Fondo del Seguro de IVM a 31 de diciembre de cada año.

\begin{table}[H]
  \centering
  \captionsetup{justification=centering}
  \caption{Evolución histórica de los egresos prestacionales del Fondo del Seguro de IVM al 31 de diciembre de cada año
   (En millones de dólares)}
  \label{tab:iess_egresos_prestacionales_ivm}
  {\fontsize{10}{11} 
  \selectfont
  \begin{tabular}{*{4}{r}}
    \toprule
    Año  & Egresos       & Incremento & Variación \\
         & prestacionales & anual      & anual    \\
    \midrule
    \input{tablas/iess_egresos_prestacionales_ivm.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{\scriptsize {\bf Fuente:} Balance de Resultados Consolidados por Fondos Administrados de los Fondos Especializados - DNGF. \\
  {\bf Elaborado:} DAIE.}
  
\end{table}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica de los egresos prestacionales del Fondo de IVM al 31 de diciembre de cada año (En millones de dólares)}
\label{fig:iess_egresos_prestacionales_ivm}
\includegraphics[scale=0.8]{graficos/iess_egresos_prestacionales_ivm.png}
 \caption*{\scriptsize {\bf Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
  E{\bf Elaborado:} DAIE.}
\end{figure}

Los egresos prestacionales se encuentran compuesto por pensiones de invalidez, vejez, montepío, auxilios de funerales y ayuda mortuoria; es así que entre el año 2010 al 2020 los egresos mantuvieron una tasa de crecimiento del 258,71\% pasando de USD. 1.268,29 millones a USD. 4.549,57 millones, incrementando en promedio (geométrico) anual 13,63\%.
Desde el 2010 al 2013 se observa un crecimiento acelerado con un incremento interanual promedio (geométrico) de 17,37\%.

A partir del año 2014 el incremento del egreso prestacional se ha moderado, a tal punto que en el año 2020 registró una de las tasas de crecimiento más bajas del período del 7,78\%; cabe mencionar que en el período analizado el egreso no presenta variaciones negativas.

En la tabla \ref{tab:iess_gastos_administracion_ivm} y figura \ref{fig:iess_gastos_administracion_ivm} se presenta la evolución histórica de los gasto de administración (contribución) del Fondo del Seguro de IVM a 31 de diciembre de cada año.


\begin{table}[H]
  \centering
  \captionsetup{justification=centering}
  \caption{Evolución histórica de los gastos de administración de IVM al 31 de diciembre de cada año (En millones de dólares)}
  \label{tab:iess_gastos_administracion_ivm}
  {\fontsize{10}{11} 
  \selectfont
  \begin{tabular}{*{4}{r}}
    \toprule
    Año  &  Gastos de  & Incremento & Variación \\
         &  Administración & anual   & anual                  \\
    \midrule
    \input{tablas/iess_gastos_administracion_ivm.tex}
    \bottomrule
  \end{tabular}
  }
  \caption*{\scriptsize {\bf Fuente:} Balance de Resultados Consolidados por Fondos Administrados de los Fondos Especializados - DNGF. \\
  {\bf Elaborado:} DAIE.}
  
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica de los gastos de administración de IVM al 31 de diciembre de cada año (En millones de dólares)}
\label{fig:iess_gastos_administracion_ivm}
\includegraphics[scale=0.8]{graficos/iess_gastos_administracion_ivm.png}
 \caption*{\scriptsize {\bf Fuente:} Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
  {\bf Elaborado:} DAIE.}

\end{figure}

Los gastos de administración corresponde a la contribución a la administradora, es así que entre el año 2010 al 2020 los gastos mantuvieron una tasa de crecimiento del 69,07\% pasando de USD. 57,77 millones a USD. 97,67 millones, incrementando en promedio (geométrico) anual 5,39\%. El comportamiento de la cuenta es variables en el tiempo, manteniendo variaciones positivas como negativas.

El incremento más significativo  del período analizado se evidencia en el año 2019 con una variación positiva de 30,43\%, pasando de  USD. 81,42 millones en el 2018 a USD. 106,19 millones en el 2019, debido al incremento de aportes; mientras que el decrecimiento más significativo se  evidencia  en el año 2016 con el -43,80\%, pasando de USD. 96,88 millones a USD. 54,44 millones.

\subsection{Ingresos por aportes versus egresos prestacionales}

Se presenta en la \ref{tab:iess_ing_vs_egre_pres_ivm} la evolución de los ingresos por aportes (personal y patronal) de los afiliados activos versus los egresos pensionales de este fondo por cada año. El resultado corresponde a la diferencia entre los aportes de los afiliados y los egresos pensionales.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución de ingresos por aportes vs los egresos prestacionales del Fondo del IVM}
\label{tab:iess_ing_vs_egre_pres_ivm}
{\fontsize{9}{10}\selectfont
\begin{tabular}{r r r r r r r r}
\toprule
Año & Aportes de & Egresos        & 60\% Egresos   & Resultado & Utilización & Acumulación a la\\
    & afiliados  & prestacionales & prestacionales &           &  anual      & reserva         \\
\midrule
\input{tablas/iess_ing_vs_egre_pres_ivm.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Balance de Resultados Consolidados por Fondos Administrados de los Fondos Especializados - DNGF. \\
{\bf Elaborado:} DAIE.}

\end{table}


{\scriptsize Nota:No se toma en cuenta el 40\% Deuda de Gobierno, para el análisis se considera un supuesto solo del 60\% que le corresponde al IESS.}


Al realizar una comparación entre las cuentas de ingresos por aportes sobre los egresos prestacionales correspondiente al 60\% de obligación del IESS, se observa que a partir del año 2016 los egresos son superiores a los ingresos, por lo que fue necesario recurrir ya sea al rendimiento o a la desinversión de la reserva para cubrir dicha brecha.

De tal manera que al año 2020 el Fondo de IVM mantiene un déficit de USD. 263,69 millones; es decir, los egresos prestacionales superaron en 10,69\% a los ingresos por aportes. Finalmente, se evidencia que la acumulación de la reserva se encuentra al 31 de diciembre del 2020 en USD. 3.589,60 millones.

\subsection{Comparación de ingresos por aportes versus lo gastos de administración del Fondo de IVM}

Se presenta en la tabla \ref{tab:iess_ing_vs_gas_adm_ivm} la evolución de los ingresos por aportes versus los gastos de administración de este fondo a diciembre de cada año; el resultado corresponde a la diferencia de dichas cuentas.

\begin{table}[H]
\captionsetup{justification=centering}
\begin{center}
\caption{Evolución de ingresos por aportes vs los gastos de administración del Fondo del IVM}
\label{tab:iess_ing_vs_gas_adm_ivm}
{\selectfont
\begin{tabular}{r r r r r r }
\toprule
Año & Aportes de & Gastos de       & Resultado  & Utilización \\
    & afiliados  & administración  &            & anual        \\
\midrule
\input{tablas/iess_ing_vs_gas_adm_ivm.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Balance de Resultados Consolidados por Fondos Administrados de los Fondos Especializados - DNGF. \\
{\bf Elaborado:} DAIE.}
\end{center}
\end{table}

Al realizar una comparación entre los gastos de contribución a la administradora con los ingresos por aportes, se determina que desde el año 2011 al 2020 se cumple con lo establecido en la Resolución No. C.D. 101 artículo 5 en el que establece: “los fondos para gasto de administración del Seguro General de Pensiones estarán constituidos por (...),  hasta la participación del cuatro por ciento(4\%) en la recaudación de los aportes (personales y patronales) de los afiliados y/o jubilados a los seguros de pensiones (...)”.

Sin embargo, se observa que en los años 2010 y 2011 la tasa de utilización anual es del 4,75\% y 4,35\% respectivamente, incumpliendo con lo establecido en artículo 27 de la Ley de Seguridad Social.

\subsection{Análisis de las Reservas Disponibles }

Del análisis se observa un crecimiento paulatino del patrimonio entre el 2010 al 2015, mientras que desde el 2016 al 2020 dicha cuenta disminuye paulatinamente, la reserva al año 2020 alcanzó USD 7.876,66 millones.


\begin{table}[H]
\captionsetup{justification=centering}
\begin{center}
\caption{Relación patrimonio gasto prestacional del Fondo del IVM}
\label{tab:iess_reservas_IVM.tex}
{\selectfont
\begin{tabular}{r r r r  }
\toprule
Año & Egresos & Patrimonio    & Relación   \\
    & prestacionales &        & patrimonio/gasto\\
\midrule
\input{tablas/iess_reservas_IVM.tex}
\bottomrule
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Balance de Resultados Consolidados por Fondos Administrados de los Fondos Especializados - DNGF. \\
{\bf Elaborado:} DAIE.}
\end{center}
\end{table}

El indicador $patrimonio/gasto$ revela la cantidad de dólares que tiene en el año de análisis, es decir, por cada dólar de obligación por gastos. Esta relación mantiene una tendencia decreciente en el período 2010 al 2020, con un porcentaje promedio del 2,77.

Finalmente, al 31 de diciembre de 2020 termina con USD. 1,73 disponibles por cada dólar de obligación; cabe mencionar que el año 2013 registró la mayor relación con USD. 3,67 por cada dólar de obligación.




% \section{Gastos}
% \label{chp_infofinan:gastos}
%
% En la tabla \ref{tab:iess_gastos_ivm} y figura \ref{fig:iess_egresos_ivm} se presenta la evolución histórica de los gastos del
% Fondo del Seguro de IVM a 31 de diciembre de cada año.
%
% \begin{table}[H]
%   \begin{center}
%   \caption{Evolución histórica de los gastos del Fondo del Seguro de IVM al 31 de diciembre de cada año}
%   \label{tab:iess_gastos_ivm}
%   {\fontsize{8}{10}\selectfont
%   \begin{tabular}{*{4}{r}}
%     \toprule
%     AÑO  &  Gastos  & Incremento & Incremento Porcentual \\
%          &          & anual      & Anual                  \\
%     \midrule
%     \input{tablas/iess_gastos_ivm.tex}
%     \bottomrule
%   \end{tabular}
%   }
%   \caption*{\scriptsize Fuente: Balance de Resultados Consolidados por Fondos Administrados de los Fondos Especializados - DNGF. \\
%   Elaborado: DAIE.}
%   \end{center}
% \end{table}
%
% \begin{figure}[H]
% \begin{center}
% \caption{Evolución del Gasto del Fondo de IVM al 31 de diciembre de cada año (En millones de dólares)}
% \label{fig:iess_egresos_ivm}
% \includegraphics[scale=1]{graficos/iess_egresos_ivm.png}
%  \caption*{\scriptsize Fuente: Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
%   Elaborado: DAIE.}
% \end{center}
% \end{figure}
%
% Entre el año 2020 al 2010 existe una tasa de crecimiento significativa del 251,33\%, pasando de USD. 1.333,41 millones a USD. 4.684,68 millones; es decir los gastos incrementaron en promedio (geométrico) anual en 13,39\%. Desde el 2010 al 2013 se observa un crecimiento acelerado de los gastos del IVM, con un incremento interanual promedio de 16,97\%.
%
% A partir del año 2014 el incremento del gasto se ha moderado, a tal punto que en el año 2020 registró una de las tasas de crecimiento más bajas del período del 8,17\%; cabe mencionar que en el período analizado el gasto no presenta variaciones negativas.
%
% En el anexo \ref{chap_gastos} se presenta los componentes del patrimonio del Fondo de IVM, el análisis horizontal y vertical de los gastos.


%---------------------------------------------------------------------------------------
% \section{Comparación de ingresos por aportes y gastos de administración del Fondo de IVM}
% \label{chp_infofinan:iess_ingrvscontrib_ivm}
%
% Se presenta en la tabla \ref{tab:iess_ingrvscontrib_ivm} la evolución de los ingresos por aportes versus la contribución para gastos de administración de este fondo a diciembre de cada año.
%
% El resultado corresponde a la diferencia de aportes personales y patronales menos la contribución para Gastos de Administración
%
%
% \begin{table}[H]
%   \begin{center}
%   \caption{Evolución de ingresos por aportes vs los gastos pensionales del Fondo del IVM}
%   \label{tab:iess_ingrvscontrib_ivm}
%   {\fontsize{8}{10}\selectfont
%   \begin{tabular}{c*{5}{r}}
%   \toprule
%   Año & Ingresos      & Contribución para & Resultado & Utilización & Valor para \\
%       & Aportes de    &  Gastos de        &           & Anual (\%)  & Acumulación \\
%       & Afiliados     & Administración    &           &             &   (\%)      \\
%   \midrule
%   \input{tablas/iess_ingrvscontri_ivm.tex}
%   \bottomrule
%   \end{tabular}
%   }
% \caption*{\scriptsize Fuente: Balance de Resultados Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\
% Elaborado: DAIE.}
%   \end{center}
% \end{table}
%
% Al realizar una comparación entre los gastos de contribución a la administradora con los ingresos por aportes, se determina que desde el año 2011 al 2020 se cumple con lo establecido en el literal c del artículo 27 de la Ley de Seguridad Social que establece como fondos propios del IESS: “El cuatro por ciento (4\%) de las recaudaciones de los aportes de los afiliados, los empleadores y/o jubilados a los seguros de pensiones”.
%
% Sin embargo se observa que en los años 2010 y 2014 la tasa de utilización anual es del 5\% y 3\% respectivamente, incumpliendo con lo establecido en artículo 27 de la Ley de Seguridad Social.
%
% % ---------------------------------------------------------------------------------------------
%
% \section{Análisis de Reservas Disponibles}
% \label{chp_infofinan:iess_reservas_IVM}
%
% Del análisis se observa un crecimiento paulatino del patrimonio entre el 2010 al 2015, mientras que desde el 2016 al 2020 dicha cuenta disminuye correspondiente al Fondo del IVM. La reserva al año 2020 alcanzó USD 7.879,66 millones, lo que implica un crecimiento promedio del 2,85\% en el período analizado.
%
%
% \begin{table}[H]
%   \begin{center}
%   \caption{Relación patrimonio gasto prestacional del Fondo del IVM}
%   \label{tab:iess_reservas_IVM}
%   {\fontsize{8}{10}\selectfont
%   \begin{tabular}{c*{4}{r}}
%   \toprule
%   Año & Gastos            &             & Relación   \\
%       & Prestacionales    &  Patrimonio & Patrimonio/           \\
%       & por pensiones     &             &   Gastos   \\
%   \midrule
%   \input{tablas/iess_reservas_IVM.tex}
%   \bottomrule
%   \end{tabular}
%   }
% \caption*{\scriptsize Fuente: Balance de Resultados Consolidado por Fondos Administrados de los Fondos Especializados - DNGF. \\
% Elaborado: DAIE.}
%   \end{center}
% \end{table}
%
% El indicador patrimonio/gasto revela la cantidad de dólares que tiene en el año de análisis, es decir por cada dólar de obligación por gastos. Esta relación mantiene una tendencia decreciente en el período 2010 al 2020, con un porcentaje promedio del 2,85\%.
%
% Finalmente al 31 de diciembre de 2020 termina con USD. 1,74 disponibles por cada dólar de obligación; cabe mencionar que el año 2013 registro la mayor relación con USD. 3,88 por cada dólar de obligación, mientras que el 2018 la más bajo del período con USD. 1,68.
%
%




%-------------------------------------------------------------------------------------------------------------------------------------
%------------------------------------------------------------------------------------------------------------------------------------
\section{Descripción del portafolio de inversiones}
\label{chp_infofinan:rentablidad}

% % El artículo 372 de la Constitución de la República del Ecuador establece: ``Los fondos y reservas del seguro universal obligatorio
% % serán propios y distintos de los del fisco, y servirán para cumplir de forma adecuada los fines de
% % su creación y sus funciones. Ninguna institución del Estado podrá intervenir o disponer de sus
% % fondos y reservas, ni menoscabar su patrimonio. Los fondos provisionales públicos y sus
% % inversiones se canalizarán a través de una institución financiera de propiedad del Instituto
% % Ecuatoriano de Seguridad Social; su gestión se sujetará a los principios de seguridad, solvencia,
% % eficiencia, rentabilidad y al control del órgano competente''.

El artículo 4 del Capítulo V ``Norma para regular las operaciones del Banco del Instituto Ecuatoriano
de Seguridad Social '' del Título XXVI del Libro I ``Normas Generales para las Instituciones del
Sistema Financiero''\footnote{La normativa citada se encuentra derogada, pero se encontraba vigente en la mayoría del período de valuación.} de la normativa de la Superintendencia
de Bancos, establecía que las inversiones del Fondo del Seguro IVM se invertirán a largo plazo; es
decir, hasta plazos mayores a cinco (5) años, en inversiones: privativas (préstamos hipotecarios,
prendarios y quirografarios, e inversión en inmuebles), no privativas en renta fija (bonos, bonos
locales, CETES \footnote{Certificados de tesorería}, certificados de depósito, papel comercial,
obligaciones, titularizaciones y pólizas de acumulación) y no privativas en renta variable
(fideicomisos mercantiles, acciones y cuotas de participación en fondos de inversión).

Para medir la rentabilidad de las inversiones, se utilizarán dos indicadores: el rendimiento
promedio ponderado y el rendimiento neto. El rendimiento promedio ponderado para cada instrumento
financiero, con pesos iguales a los saldos en valor nominal, se calcula según el artículo 5.4.1.3
del Capítulo III ``Manual operativo para valoración a precios de mercado de valores de contenido crediticio y de participación y procedimiento'' del Título III ``De las operaciones del Instituto
Ecuatoriano de Seguridad Social, del Instituto de Seguridad Social de las Fuerzas Armadas, del
Instituto de Seguridad Social de la Policía Nacional, del Servicio de Cesantía de la Policía
Nacional'' del  Libro II ``Normas de control para las entidades del sistema de seguridad
social''\footnote{La normativa citada se encuentra derogada, pero se encontraba vigente en la
mayoría del período de valuación.}, en el cual manifiesta que la fórmula para calcular el
rendimiento efectivo promedio ponderado es:
\begin{equation}
\overline{TIR}=\frac{\sum^{K}_{1} TIR_{i}\cdot VP_{i}}{\sum^{k}_{1}VP_{i}},
\end{equation}

donde:\vskip 0.5cm
$\overline{TIR}$: Rendimiento  promedio ponderado porcentual, expresado con hasta cuatro (4) decimales;
\vskip 0.3cm
$TIR_{i}$: Rendimiento efectivo de la operación de contado $i$;
\vskip 0.3cm
$VP_{i}$: Valor nominal residual o valor parcial;
\vskip 0.3cm
$k$: Número de operaciones a tener en cuenta.

El rendimiento neto de cada fondo se calcula según la metodología expuesta en el informe ``Cálculo
de rendimientos financieros de los Fondos Previsionales administrados por el Banco del Instituto
Ecuatoriano de Seguridad Social''. Los rendimientos anualizados netos analizados como indicadores de
rentabilidad, se estiman a través de la siguiente fórmula:
\begin{equation}
R_{i}=\frac{\left(I_{i}-Gop_{i}-GAdm_{i}\right)\cdot \left(12/j\right)}{\overline{FA_{i}}},
\end{equation}

donde\vskip 0.4cm
$R_{i}$: Rendimiento neto del fondo $i$ para $i=1,2,3,\ldots,9$;\vskip 0.3cm
$I_{i}$: Ingreso acumulado del fondo $i$ para $i=1,2,3,\ldots,9$;\vskip 0.3cm
$Gop_{i}$: Gasto operativo acumulado del fondo $i$ para $i=1,2,3,\ldots,9$; \vskip 0.3cm
$GAdm_{i}$: Gasto administrativo acumulado del fondo $i$ para $i=1,2,3,\ldots,9$; \vskip 0.3cm
$\overline{FA_{i}}$: Fondo administrativo promedio del fondo $i$ para $i=1,2,3,\ldots,9$.

$\overline{FA_{i}}$ hace referencia al promedio del saldo del fondo registrado
el último día de cada mes, desde el 31 de diciembre del año
anterior hasta el último día del mes considerado. Específicamente, la fórmula  de cálculo es la siguiente
\begin{equation}
\overline{FA_{i}}=\frac{FA_{i,dic}+FA_{i,ene}+FA_{i,feb}+FA_{i,mar}+\cdots+FA_{i,actual}}{j+1}.
\end{equation}

A partir de la información recopilada de los documentos\footnote{Memorando Nro.
IESS-DNGF-2018-0859-M de 2 de octubre de 2018, oficio Nro. BIESS-OF-GGEN-0315-2019 de fecha 28 de
marzo de 2019 y el informe técnico BIESS-IF-GADF-002-2018 de fecha 23 de febrero de 2018}, se
presenta la siguiente información respecto a los fondos y reservas del Seguro IVM:

A continuación, se presenta la evolución histórica del valor nominal y su respectivo rendimiento del
portafolio de inversiones del Seguro de IVM, durante el período 2011 a 2020 en la tabla \ref{tab:iess_total_inv} y la figura \ref{fig:iess_inv_tot}.

\begin{table}[H]
\captionsetup{justification=centering}
  \begin{center}
  \caption{Evolución de los Fondos del Seguro IVM administrados por el BIESS}
  \label{tab:iess_total_inv}
  \resizebox{\columnwidth}{!}{%
  \begin{tabular}{rrrrcrrc}
    \toprule
 \multicolumn{1}{c}{Año} & \multicolumn{1}{c}{Inversiones} & \multicolumn{1}{c}{Caja} & \multicolumn{1}{c}{Fondo total} & \multicolumn{1}{c}{Rendimiento Promedio}& \multicolumn{1}{c}{Rendimiento} & \multicolumn{1}{c}{Rendimiento Neto} & \multicolumn{1}{c}{Plazo Promedio}  \\
     &  \multicolumn{1}{c}{(USD)}           &\multicolumn{1}{c}{(USD)} & \multicolumn{1}{c}{administrado (USD)}&  \multicolumn{1}{c}{Ponderado (\%)}    & \multicolumn{1}{c}{Neto (\%)}   & \multicolumn{1}{c}{Real (\%)}  &  \multicolumn{1}{c}{Ponderado (días)}  \\
    \midrule
    \input{tablas/iess_total_inv.tex}
    %\bottomrule
  \end{tabular}
    }
\caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS y Dirección de Tesorería - BIESS. \\
{\bf Elaborado:} DAIE.}
  \end{center}
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica del saldo en valor nominal de las inversiones del Fondo del Seguro IVM
y su rendimiento neto}
\label{fig:iess_inv_tot}
\includegraphics[scale=0.9]{graficos/iess_inv_tot.png}
\caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS y Dirección de Tesorería - BIESS. \\
{\bf Elaborado:} DAIE}
\end{figure}

Se observa como el portafolio total de inversiones del Seguro IVM creció de USD 2.243.628.632 en el año 2011 a USD 9.030.558.911 en el año 2015, un crecimiento del 302,5\%, y, decrece a diciembre de 2020 a USD 6.091.663.365,65. En cambio, su tasa de rendimiento promedio ponderada a diciembre de 2020 es igual 8,18\%. El rendimiento neto más alto se registró en el año 2012 (10,01\%) y las más bajas fueron en el 2011 y 2018 (1,88\% y 4,87\%, respectivamente) y su promedio es 6,96\%
\%. La reducción de los rendimientos netos en el año 2018 se debió al cumplimiento de la programación de desinversión del Fondo del Seguro IVM solicitada por el IESS, en los años 2016 y 2017, anticipando los ingresos en esos años y reduciendo los ingresos para los años subsiguientes.

Se presenta un breve resumen de la situación actual de las inversiones pertenecientes al Seguro IVM,
a través del BIESS, en Bonos del Estado, titularizaciones, obligaciones, préstamos, certificados de
tesorería, cupones de interés y papel comercial, mostrando su saldo remanente de la inversión en
valor nominal, su rendimiento promedio ponderado y su rendimiento promedio ponderado real a 31 de diciembre de 2020.
\begin{table}[H]
\captionsetup{justification=centering}
  \begin{center}
  \caption{Portafolio de inversiones del Fondo del Seguro IVM administrados del BIESS a 31 de diciembre de 2020}
  \label{tab:iess_INV_Corte}
  \resizebox{\columnwidth}{!}{%
  \begin{tabular}{lrccr}
    \toprule
 \multicolumn{1}{c}{Instrumento:} & \multicolumn{1}{c}{Saldo Valor}   & \multicolumn{1}{c}{Rendimiento Promedio}  & \multicolumn{1}{c}{Rendimiento Promedio}  & \multicolumn{1}{c}{Plazo Promedio}  \\
             &  \multicolumn{1}{c}{Nominal (USD)}& \multicolumn{1}{c}{Ponderado (\%)}        & \multicolumn{1}{c}{Ponderado Real (\%)}&\multicolumn{1}{c}{Remanente (días)} \\
   \midrule
    \input{tablas/iess_inv_corte.tex}
    %\bottomrule
  \end{tabular}
    }
\caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS y Dirección de Tesorería - BIESS.\\
{\bf Elaborado:} DAIE.}
  \end{center}
\end{table}

El Fondo del Seguro de IVM presenta problemas de liquidez, que han provocado desinvertir sus reservas para el pago de prestaciones, debido a la falta de planificación de los flujos de ingresos financieros en la colocación de nuevas inversiones, lo que ha producido en que el 86,43\% (USD 5.265.128.641,05) de las inversiones al 31 de diciembre de 2020, se encuentren en bonos del Estado y préstamos hipotecarios, los cuales son inversiones a largo plazo.

% --------------------------------------------------------------------------------------------------
\subsection{Rendimiento neto de las inversiones del fondo}

La Dirección de Tesorería del BIESS envió los resultados\footnote{a través del Oficio Nro. BIESS-OF-GGEN-0591-2019 de fecha 17 de junio de 2019} de la metodología:``Cálculo de rendimientos financieros de los Fondos Previsionales administrados por el Banco del Instituto Ecuatoriano de Seguridad Social''. Para el cálculo de los rendimientos netos, se utilizaron: los ingresos, gastos operativos y gastos administrativos, el fondo administrado promedio (desde diciembre del año anterior). Además, en la tabla \ref{tab:iess_rend_inv}, se presentan la tasa de rendimiento bruta antes de gastos y la tasa de rendimiento neta, la cual es el rendimiento después de gastos. Los ingresos se detallan más tarde en la tabla \ref{tab:iess_ingre_inv} y los egresos en la tabla \ref{tab:iess_gastos_inv}.

En promedio, la diferencia entre rendimientos brutos y netos de este fondo es 1,83\%; es decir, los
gastos (operativos y administrativos) producen una reducción del 1,83\% del rendimiento bruto y,
además, presentan una baja volatilidad (desviación estándar igual a 0,54\%). La reducción del
rendimiento neto en el año 2018 (4,87\%) se debe principalmente a la venta de cupones de interés de
Bonos del Estado Ecuatoriano. Esta venta anticipada produjo ingresos anticipados por USD 267,17 millones en 2016, USD 194,24 millones en el año 2017 y USD 6,15 millones en el año 2018; en cambio, estas
desinversiones produjeron que el Fondo del Seguro IVM no percibiera ingresos por USD 9,20 millones
en el año 2016, USD 203,67 millones en el año 2017 y USD 188,52 millones en el año 2018.
En conclusión, la afectación al Fondo del Seguro del IVM fue: USD 9,43 millones en el año 2017, USD
182,37 en el año 2018, mientras que el año 2016 se presentó utilidades por esta venta anticipada por
USD 257,97 millones (Según la Dirección de Tesorería del BIESS en los insumos enviados en Oficio Nro.
BIESS-OF-GGEN-0591-2020).


\begin{table}[H]
\captionsetup{justification=centering}
  \begin{center}
  \caption{Evolución de los ingresos, gastos operativos, gastos administrativos, rendimiento bruto y rendimiento neto del portafolio de inversiones del Fondo del Seguro IVM}
  \label{tab:iess_rend_inv}
  \resizebox{\columnwidth}{!}{%
  \begin{tabular}{lrrrrrr}
    \toprule
   \multicolumn{1}{c}{Corte a:} & \multicolumn{1}{c}{Ingresos} & \multicolumn{1}{c}{Gastos}& \multicolumn{1}{c}{Gastos} & \multicolumn{1}{c}{Fondo Administrado} & \multicolumn{1}{c}{Rendimiento}  & \multicolumn{1}{c}{Rendimiento} \\
            & \multicolumn{1}{c}{(USD)} &\multicolumn{1}{c}{Operativos (USD)} & \multicolumn{1}{c}{Administrativos (USD)} &\multicolumn{1}{c}{Promedio (USD)}     & \multicolumn{1}{c}{Bruto (\%)}   & \multicolumn{1}{c}{Neto (\%)} \\
    \midrule
    \input{tablas/iess_rend_inv.tex}
    %\bottomrule
  \end{tabular}
    }
\caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS y Dirección de Tesorería - BIESS. \\
{\bf Elaborado:} DAIE.}
  \end{center}
\end{table}

Los ingresos por inversiones del Fondo del Seguro IVM se presentan en la tabla \ref{tab:iess_rend_inv} y en la tabla \ref{tab:iess_ingre_inv} se muestra sus componentes, los cuales fueron tomados de los estados de pérdidas y ganancias a corte diciembre de los respectivos años. Los ingresos financieros generados por las inversiones de este seguro tuvieron una tendencia a crecer de
USD 307.902.261,95 a USD 942.806.022,24 entre los años 2011 y 2016, respectivamente, después los ingresos decrecieron a USD 553.218.762,70 en 2020. Desde el año 2017, los ingresos por
préstamos hipotecarios han generado los mayores ingresos, logrando generar USD 333.991.802,09 en el 2020 a diferencia de los préstamos quirografarios que solo generaron USD 88.587.787,55 en el mismo año.
\begin{table}[H]
\captionsetup{justification=centering}
  \begin{center}
  \caption{Evolución de los ingresos financieros generados por las inversiones del Fondo del Seguro IVM}
  \label{tab:iess_ingre_inv}
  \resizebox{\columnwidth}{!}{%
  \begin{tabular}{{l}r*{7}{r}}
    \toprule
  \multicolumn{1}{c}{Ingresos:} & \multicolumn{1}{c}{2014} & \multicolumn{1}{c}{2015} &\multicolumn{1}{c}{2016} &\multicolumn{1}{c}{2017} &\multicolumn{1}{c}{2018} & \multicolumn{1}{c}{2019}  &  \multicolumn{1}{c}{2020}\\
    \midrule
    \input{tablas/iess_ingre_inv.tex}
    %\bottomrule
  \end{tabular}
    }
\caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS y Dirección de Tesorería - BIESS. \\
{\bf Elaborado:} DAIE}
  \end{center}
\end{table}

Los gastos operativos de las inversiones del portafolio de inversiones del Fondo del Seguro IVM se detallan en la tabla \ref{tab:iess_gastos_inv} y se puede apreciar que mantienen una tendencia a crecer, puesto a que crecieron de USD 21.244.220,82 a USD 140.209.554,80 entre el año 2012 a 2020, respectivamente, lo que significa un crecimiento de 559,99\% en seis (8) años. Los mayores gastos
operativos corresponden a las provisiones de préstamos hipotecarios \footnote{El cálculo de provisiones se lo realizó según la Resolución No. JB- 2012-2300 (derogada el 29 de diciembre de 2017), remplazada por la Circular SB-IG-2017-0241-C y de acuerdo al Capítulo II ´´ Calificación de activos de riesgo y constitución de provisiones por parte de las instituciones controladas por la
Superintendencia de Bancos ´´ del Título IX del Libro I.}, las cuales crecieron de USD 40.922.693,75 en el 2019 a USD 108.817.539,50 en el 2020 (equivale al 77,61\% de los gastos de las inversiones del fondo en 2020), lo que representa un crecimiento de 165,91\% en un solo año, esto debido al crecimiento del tamaño y de la morosidad de la cartera de créditos hipotecarios. En cambio, las provisiones de préstamos quirografarios creció de USD 1.100.923,56 a USD 3.569.932,21 entre 2019 y 2020, respectivamente; es decir, un crecimiento igual a 224,27\% en un solo año.

\begin{table}[H]
\captionsetup{justification=centering}
  \begin{center}
  \caption{Evolución de los gastos operativos producidos por las inversiones del Fondo del Seguro IVM}
  \label{tab:iess_gastos_inv}
  \resizebox{\columnwidth}{!}{%
  \begin{tabular}{{l}r*{7}{r}}
    \toprule
    \multicolumn{1}{c}{Gastos:} &   \multicolumn{1}{c}{2014} &   \multicolumn{1}{c}{2015} &  \multicolumn{1}{c}{2016} &  \multicolumn{1}{c}{2017} &  \multicolumn{1}{c}{2018} &   \multicolumn{1}{c}{2019}&  \multicolumn{1}{c}{2020}\\
    \midrule
    \input{tablas/iess_gastos_inv.tex}
    %\bottomrule
  \end{tabular}
    }
  \caption*{\scriptsize {\bf Fuente:} Dirección de Tesorería - BIESS y Balances Financieros del BIESS. \\
  {\bf Elaborado:} DAIE.}
  \end{center}
\end{table}

% --------------------------------------------------------------------------------------------------
\subsection{Inversiones privativas (préstamos)}
% De acuerdo al numeral 1 del artículo 9 del Capítulo V ``Normas para regular las operaciones del
% Banco del Instituto Ecuatoriano de Seguridad Social'' del Libro I ``Normas generales para las
% instituciones del sistema financiero''\footnote{Esta normativa se encuentra derogada, pero estaba
% vigente en la mayoría del período de valuación de este estudio.}, las inversiones privativas
% abarcan:  préstamos hipotecarios; préstamos quirografarios; préstamos prendarios a través de los
% servicios de los montes de piedad; las colocaciones financieras de las cuentas de menores
% beneficiarios del Instituto Ecuatoriano de Seguridad Social; operaciones de descuento de cartera
% hipotecaria; y adquisición, conservación y enajenación de bienes inmuebles, de acuerdo a las
% resoluciones que emita el directorio del Banco del Instituto Ecuatoriano de Seguridad Social.

En la tabla \ref{tab:iess_creditos_inv} y figura \ref{fig:iess_creditos_inv}, se muestra la evolución histórica de las inversiones en préstamos quirografarios e hipotecarios en valor nominal con su respectivo rendimiento y plazo promedio ponderado durante el período 2012 a 2020.
\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica del saldo en valor nominal de las inversiones en préstamos del Fondo
del Seguro IVM y su rendimiento promedio ponderado}
\label{fig:iess_creditos_inv}
\includegraphics[scale=1]{graficos/iess_creditos_inv.png}
  \caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS. \\
  {\bf Elaborado:} DAIE.}
\end{figure}

\begin{table}[H]
\captionsetup{justification=centering}
  \begin{center}
  \caption{Evolución de las inversiones del Fondo del Seguro IVM en préstamos}
  \label{tab:iess_creditos_inv}
  \resizebox{\columnwidth}{!}{%
  \begin{tabular}{crrrccc}
    \toprule
     \multicolumn{1}{c}{Año} &  \multicolumn{1}{c}{Préstamos}&  \multicolumn{1}{c}{Préstamos}  &  \multicolumn{1}{c}{Total}&  \multicolumn{1}{c}{Rendimiento} &  \multicolumn{1}{c}{Rendimiento Promedio}&  \multicolumn{1}{c}{Plazo} \\
      &   \multicolumn{1}{c}{Quirografarios (USD)}&  \multicolumn{1}{c}{Hipotecarios (USD)}&   \multicolumn{1}{c}{(USD)}  &   \multicolumn{1}{c}{Promedio Ponderado (\%)} &   \multicolumn{1}{c}{Ponderado Real (\%)} &    \multicolumn{1}{c}{Promedio Ponderado (días)}\\
    \midrule
    \input{tablas/iess_creditos_inv.tex}
    %\bottomrule
  \end{tabular}
    }
  \caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS y Balances Financieros del BIESS. \\
  {\bf Elaborado:} DAIE.}
  \end{center}
\end{table}

El portafolio de inversiones del Seguro IVM no registra inversiones en préstamos prendarios. La mayoría de sus inversiones en préstamos son hipotecarios (86,32\% en 2020). La evolución del saldo
remanente invertido en préstamos tuvo una tendencia creciente entre el año 2011 a 2015,
años en los que su cartera creció de USD 1.505.857.263,78 a USD 4.363.131.162,21, respectivamente.
Más tarde, en los últimos tres años su cartera decreció a USD 4.236.561.167,55 en el 2020

En cambio, su tasa de rendimiento ponderada registró su máximo en 2016 (9,25\%) y su mínimo en 2014 (8,48\%) y su promedio es 8,78\%. Cabe mencionar que este rendimiento es un promedio ponderado por tanto no considera los gastos por provisiones que estipulan la autoridad de control para este tipo de inversión como se pueden apreciar en la tabla \ref{tab:iess_gastos_inv}; por consiguiente, es necesario establecer una metodología para calcular los rendimientos netos de las inversiones en préstamos.

% --------------------------------------------------------------------------------------------------
\subsection{Inversiones no privativas con renta fija en el sector público}

De acuerdo al numeral 1 del artículo 9 del Capítulo V ``Normas para regular las operaciones del Banco del Instituto Ecuatoriano de Seguridad Social'' del Libro I ``Normas Generales para las instituciones del Sistema Financiero'', las inversiones no privativas abarcan:  títulos de renta fija; títulos de renta variable; valores que se emitan como consecuencia de procesos de titularización; inversiones en el exterior dentro de los términos de la Ley de Seguridad Social; y fideicomisos mercantiles, cuyo beneficiario sea el Banco del Instituto Ecuatoriano de Seguridad
Social.\footnote{(Reformado con Resolución No. JB-2014-3029 de 6 de agosto del 2014)}
% --------------------------------------------------------------------------------------------------
\subsubsection{Inversiones en Bonos del Estado Ecuatoriano}

En la tabla \ref{tab:iess_bonos_hist_inv} y figura \ref{fig:iess_bonos_hist_inv} se muestra la evolución histórica de las inversiones del Seguro IVM en bonos del Estado, en valor nominal (barras) a diciembre de cada año y sus tasas de rendimiento
(líneas) durante el período 2011 a 2020. Como se puede observar el rendimiento crece en el tiempo, de 5,87\% a 7,91\% entre los años 2011 y 2020, respectivamente. En cambio, el saldo en valor nominal
creció de USD 1.023.404.975,13 en diciembre de 2011 a USD 4.283.912.915,79  en diciembre de 2015,
crecimiento del 318,6\% entre 2011 a 2015, año en el cual obtuvo su máximo; más tarde, su valor
nominal disminuyó a 1.607.873.972,11 a diciembre de 2020, con un decrecimiento de  62,47\% entre 2015 y 2020.


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica del saldo en valor nominal de las inversiones en Bonos del Estado del
Fondo del Seguro IVM y su rendimiento promedio ponderado}
\label{fig:iess_bonos_hist_inv}
\includegraphics[scale=0.65]{graficos/iess_bonos_hist_inv.png}
  \caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS. \\
  {\bf Elaborado:} DAIE.}
\end{figure}


\begin{table}[H]
\captionsetup{justification=centering}
  \begin{center}
  \caption{Evolución de las inversiones del Fondo del Seguro IVM en Bonos del Estado Ecuatoriano}
  \label{tab:iess_bonos_hist_inv}
  {\fontsize{10}{12}\selectfont
  \begin{tabular}{crccr}
    \toprule
   \multicolumn{1}{c}{Año} &   \multicolumn{1}{c}{Saldo}         &   \multicolumn{1}{c}{Rendimiento Promedio} &   \multicolumn{1}{c}{Rendimiento Promedio} &   \multicolumn{1}{c}{Plazo} \\
     &   \multicolumn{1}{c}{Valor Nominal (USD)} &   \multicolumn{1}{c}{Ponderado (\%)}        &   \multicolumn{1}{c}{Ponderado Real (\%)} &   \multicolumn{1}{c}{(días)}   \\
    \midrule
    \input{tablas/iess_bonos_hist_inv.tex}
    %\bottomrule
  \end{tabular}
    }
  \caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS y Balances Financieros del BIESS. \\
  {\bf Elaborado:} DAIE.}
  \end{center}
\end{table}


% {\fontsize{10}{11}\selectfont
% \begin{longtable}[H]{lrrccr}
% \caption{Detalle de las inversiones del Fondo del Seguro IVM en Bonos del Estado Ecuatoriano a 31
% de diciembre de 2018} \\
% \label{tab:iess_bonos_detalle_inv} \\
% \toprule
%    \multicolumn{1}{l}{Referencia del} &   \multicolumn{1}{c}{Valor Nominal} &   \multicolumn{1}{c}{Saldo Valor}  &   \multicolumn{1}{c}{Tasa Cupón} &   \multicolumn{1}{c}{Plazo Remanente} &  \multicolumn{1}{c}{Amortización}\\
%    \multicolumn{1}{c}{Título}  &  \multicolumn{1}{c}{de Compra (USD)}&  \multicolumn{1}{c}{Nominal (USD)}&        \multicolumn{1}{c}{(\%)}  &   \multicolumn{1}{c}{(días)}          &              \\
% \midrule
% \endfirsthead
%
% \toprule
%    \multicolumn{1}{l}{Referencia del} &   \multicolumn{1}{c}{Valor Nominal} &   \multicolumn{1}{c}{Saldo Valor}  &   \multicolumn{1}{c}{Tasa Cupón} &   \multicolumn{1}{c}{Plazo Remanente} &  \multicolumn{1}{c}{Amortización}\\
%    \multicolumn{1}{c}{Título}  &  \multicolumn{1}{c}{de Compra (USD)}&  \multicolumn{1}{c}{Nominal (USD)}&        \multicolumn{1}{c}{(\%)}  &   \multicolumn{1}{c}{(días)}          &              \\
% \midrule
% \endhead
% \bottomrule \multicolumn{6}{c}{continúa...} \\
% \endfoot
% \bottomrule
% \caption*{\scriptsize Fuente: Subgerencia de Banca de Inversión - BIESS y Balances Financieros del BIESS. \\
%   Elaborado: DAIE.}
% \endlastfoot
%   \input{tablas/iess_bonos_detalle_inv.tex}
% \end{longtable}
% }

%\paragraph{Bonos del Estado por el 40\% del pago de las pensiones}

% El artículo 237 de la Ley de Seguridad Social establece: ``FINANCIAMIENTO.- En todos los casos
% comprendidos en este Capítulo, el IESS cubrirá el sesenta por ciento (60\%) de la pensión
% respectiva, y el Estado continuará financiando obligatoriamente el cuarenta por ciento (40\%)
% restante; pero, en cualquier circunstancia, el IESS otorgará la prestación completa”.

% Según los acuerdos suscritos entre funcionarios del IESS y del Ministerio de Finanzas el 12 de
% noviembre de 2012 y el 4 diciembre de 2012, se elaboran las actas de consolación provisional de la
% contribución del 40\% para el pago de pensiones y otras contribuciones del Estado al IESS desde el
% mes de octubre de 2012. Se comenzaron a transferir los Bonos del Estado emitidos por el Ministerio de
% Finanzas por concepto de la cancelación del 40\% de las pensiones y otras contribuciones del Estado
% al IESS desde el 15 de noviembre de 2012 hasta el 15 de abril de 2015, fecha de la última entrega de
% Bonos del Estado por este concepto. De esta manera el Estado canceló sus obligaciones por el 40\% de
% las pensiones y otras contribuciones con el IESS de los meses de octubre de 2012 hasta
% marzo de 2015. En total, se recibieron USD 1.994.219.449,82 en Bonos del Estado y todos estos bonos
% tienen una tasa de rendimiento anual igual a 7,5\% a 12 años. El detalle anual de las
% entrega de estos bonos se encuentra en la tabla \ref{tab:iess_RepBonos40_hist_inv}.
% 
% \begin{table}[H]
% \centering
% \captionsetup{justification=centering}
%  
%   \caption{Detalle de los Bonos del Estado Ecuatoriano recibidos \\ por el pago del 40\% de las pensiones
%   y otras\\ obligaciones que tiene el Estado con el IESS}
%     \label{tab:iess_RepBonos40_hist_inv}
%   {\fontsize{10}{12}\selectfont
%   \begin{tabular}{crccc}
%     \toprule
%  \multicolumn{1}{c}{Año de}     &  \multicolumn{1}{c}{Monto}         &  \multicolumn{1}{c}{Tasa} &  \multicolumn{1}{c}{Plazo} &  \multicolumn{1}{c}{Año de}  \\
%  \multicolumn{1}{c}{recepción}   &  \multicolumn{1}{c}{recibido (USD)}&  \multicolumn{1}{c}{(\%)} &   \multicolumn{1}{c}{(años)} &  \multicolumn{1}{c}{vencimiento}\\
%     \midrule
%         \input{tablas/iess_RepBonos40_hist_inv.tex}
% %    \bottomrule
%   \end{tabular}
%    }
%   \caption*{\scriptsize {\bf Fuente:} Actas de entrega de Bonos del Estado por el pago del 40\% de las
%   pensiones \\
%    {\bf Elaborado:} DAIE.}
% 
% \end{table}

% --------------------------------------------------------------------------------------------------
% \subsubsection{Certificados de Tesorería del Estado Ecuatoriano}
%
% \begin{figure}[H]
% \centering
% \caption{Evolución histórica del saldo remanente, en valor nominal, de las inversiones en Certificados de Tesorería del Fondo del Seguro IVM y su rendimiento promedio ponderado}
% \label{fig:iess_bonos_hist_inv}
% \includegraphics[scale=1.2]{graficos/iess_cetes_hist_inv.png}
% \end{figure}
%
% \begin{table}[H]
%   \begin{center}
%   \caption{Evolución de las inversiones del Fondo del Seguro IVM en Certificados de Tesorería}
%   \label{tab:iess_cetes_hist_inv}
%   \resizebox{\columnwidth}{!}{%
%   \begin{tabular}{crccr}
%     \toprule
%   \multicolumn{1}{c}{Año} &  \multicolumn{1}{c}{Saldo} &  \multicolumn{1}{c}{Rendimiento Promedio} &  \multicolumn{1}{c}{Rendimiento Promedio}&  \multicolumn{1}{c}{Plazo} \\
%   &  \multicolumn{1}{c}{Valor Nominal (USD)} &  \multicolumn{1}{c}{Ponderado (\%)} &  \multicolumn{1}{c}{Ponderado Real (\%)} &  \multicolumn{1}{c}{(días)}   \\
%     \midrule
%     \input{tablas/iess_cetes_hist_inv.tex}
%     \bottomrule
%   \end{tabular}
%    }
%   \caption*{\scriptsize Fuente: Tesoreria BIESS y Balances Financieros del BIESS. \\
%     }
%   \caption*{\scriptsize Fuente: Tesorería BIESS y Balances Financieros del BIESS. \\
%
%   Elaborado: DAIE.}
%   \end{center}
% \end{table}
% --------------------------------------------------------------------------------------------------
\subsection{Inversiones no privativas con renta fija en el sector privado}

% --------------------------------------------------------------------------------------------------
\subsubsection{Inversiones en Obligaciones en renta fija}

En la siguiente tabla \ref{tab:iess_obligaciones_hist_inv} y figura \ref{fig:iess_obligaciones_hist_inv} se muestra la evolución histórica del
saldo remanente de las inversiones en obligaciones en renta fija (barras), en valor nominal, y sus rendimientos (líneas) durante el período 2011 a 2020.
\begin{table}[H]
\centering
\captionsetup{justification=centering}

  \caption{Evolución de las inversiones del Fondo del Seguro IVM en Obligaciones en renta fija}
  \label{tab:iess_obligaciones_hist_inv}
  {\fontsize{10}{12}\selectfont
  \begin{tabular}{crccr}
    \toprule
  \multicolumn{1}{c}{Año} &  \multicolumn{1}{c}{Saldo} &  \multicolumn{1}{c}{Rendimiento Promedio} &  \multicolumn{1}{c}{Rendimiento Promedio}&  \multicolumn{1}{c}{Plazo} \\
  &  \multicolumn{1}{c}{Valor Nominal (USD)} &  \multicolumn{1}{c}{Ponderado (\%)} &  \multicolumn{1}{c}{Ponderado Real (\%)} &  \multicolumn{1}{c}{(días)}\\
    \midrule
    \input{tablas/iess_obligaciones_hist_inv.tex}
 %   \bottomrule
  \end{tabular}
   }
  \caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS. \\
  {\bf Elaborado:} DAIE.}
 
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica nominal del saldo remanente de las inversiones en obligaciones en renta fija del Fondo del Seguro IVM y su rendimiento promedio ponderado}
\label{fig:iess_obligaciones_hist_inv}
\includegraphics[scale=1]{graficos/iess_obligaciones_hist_inv.png}
  \caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS.\\
  {\bf Elaborado:} DAIE.}
\end{figure}

El saldo en valor nominal decreció de USD 13.111.109,98 a diciembre de 2013 a USD 1.107.776,50 en diciembre de 2018, año en el cual obtuvo su mínimo valor invertido; y para el 2020 se registró USD 17.885.971,60. Por último, la tasa de
rendimiento promedio ponderada es igual a 8,84\% en el año 2020 y su promedio en el período 2011 y 2020 es 8,79\%. El portafolio de inversiones en obligaciones en renta fija al corte (diciembre de 2020) se muestra
el valor nominal de compra de estos bonos corporativos, el nombre del emisor, el saldo remanente, la
tasa de cupón anual y el plazo remanente en días en la tabla \ref{tab:iess_oblig_detalle_inv}.


\begin{table}[H]
\centering
\captionsetup{justification=centering}

  \caption{Detalle de las inversiones del Fondo del Seguro IVM en obligaciones en renta fija a 31
  de diciembre de 2020}
  \label{tab:iess_oblig_detalle_inv}
    {\fontsize{8}{10}\selectfont
    \scalebox{0.8}{
      \begin{tabular}{lrrccc}
    \toprule
 \multicolumn{1}{l}{Emisor:} & \multicolumn{1}{c}{Valor Nominal} & \multicolumn{1}{c}{Saldo Valor}    & \multicolumn{1}{c}{Tasa Cupón} & \multicolumn{1}{c}{Plazo Remanente} & Amortización \\
        & \multicolumn{1}{c}{de Compra (USD)} & \multicolumn{1}{c}{Nominal (USD)} & \multicolumn{1}{c}{(\%)}      & \multicolumn{1}{c}{(días)}  &  \\
     \midrule
    \input{tablas/iess_oblig_detalle_inv.tex}
%     \bottomrule
  \end{tabular}
    }
    }
  \caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS. \\
  {\bf Elaborado:} DAIE.}

\end{table}
% \end{landscape}

El portafolio de inversiones de este seguro se compone de bonos corporativos a renta fija de quince empresas en USD 17.885.971,60, lo cual no es representativo para el tamaño del portafolio de inversiones de este fondo; pero a la vez estas obligaciones tienen altos rendimientos y no están sujetas a la volatilidad generada por la especulación del mercado de valores, como lo que sucede en las inversiones de renta variable.

% --------------------------------------------------------------------------------------------------
\subsubsection{Inversiones en Titularizaciones}

La Titularización es un mecanismo de financiamiento que consiste en: transformar activos o bienes, actuales o futuros, en valores negociables en el Mercado de Valores, para obtener liquidez en condiciones competitivas de mercado, con la consecuente reducción de los costos financieros.

En la figura \ref{fig:iess_titularizaciones_hist_inv} y la tabla
\ref{tab:iess_titularizaciones_hist_inv}, se muestra la evolución histórica del saldo (barras), en valor nominal, de las inversiones del Fondo del Seguro de IVM en titularizaciones a 31 diciembre de cada año y su rendimiento promedio ponderado (líneas) durante el período 2011 a 2020.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica del saldo remanente, en valor nominal, de las inversiones en titularizaciones en renta fija del Fondo del Seguro IVM y su rendimiento promedio ponderado}
\label{fig:iess_titularizaciones_hist_inv}
\includegraphics[scale=1]{graficos/iess_titularizaciones_hist_inv}
  \caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS. \\
  {\bf Elaborado:} DAIE.}
\end{figure}

El rendimiento promedio ponderado de las inversiones en titularizaciones ha tendido a crecer en el tiempo de 7,69\% en el año 2011 a 9,11\% en el 2017 y después sufrir un leve decrecimiento en el 2020 (8,82\%). En cambio, el
saldo en valor nominal decreció de USD 86.408.377,65 en diciembre de 2012 a USD 3.105.940,54 a diciembre de 2020. Esto implica que hubo una reducción de 96,41\% en 8 años (entre 2012 a 2020).


\begin{table}[H]
\captionsetup{justification=centering}
  \begin{center}
  \caption{Evolución de las inversiones del Fondo del Seguro IVM en titularizaciones en renta fija}
  \label{tab:iess_titularizaciones_hist_inv}
  {\fontsize{10}{12}\selectfont
  \begin{tabular}{crccr}
    \toprule
 \multicolumn{1}{c}{Año} & \multicolumn{1}{c}{Saldo} & \multicolumn{1}{c}{Rendimiento Promedio} & \multicolumn{1}{c}{Rendimiento  Promedio}& \multicolumn{1}{c}{Plazo} \\
  & \multicolumn{1}{c}{Valor Nominal (USD)} & \multicolumn{1}{c}{Ponderado (\%)} & \multicolumn{1}{c}{Ponderado Real (\%)} & \multicolumn{1}{c}{(días)}   \\
    \midrule
    \input{tablas/iess_titularizaciones_hist_inv.tex}
%    \bottomrule
  \end{tabular}
    }
  \caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS. \\
  {\bf Elaborado:} DAIE.}
  \end{center}
\end{table}

A continuación, se muestra el portafolio de inversiones en titularizaciones con fecha corte 31 de diciembre de 2020. En la tabla \ref{tab:iess_titularizaciones_hist_inv}, se presentan a detalle: el valor nominal de la Titularización, saldo al corte en valor nominal, la tasa cupón trimestral y el plazo remanente en días.
\begin{table}[H]
  \begin{center}
  \caption{Detalle del portafolio de las inversiones del Fondo del Seguro IVM en titularizaciones
  en renta fija a 31 de diciembre de 2018}
  \label{tab:iess_titularizaciones_hist_inv}
  \resizebox{\columnwidth}{!}{%
  \begin{tabular}{lrrcr}
    \toprule
 \multicolumn{1}{c}{Emisor:} & \multicolumn{1}{c}{Valor Nominal}& \multicolumn{1}{c}{Saldo Valor}   & \multicolumn{1}{c}{Tasa Cupón} & \multicolumn{1}{c}{Plazo Remanente} \\
        & \multicolumn{1}{c}{de Compra (USD)} & \multicolumn{1}{c}{Nominal (USD)} &  \multicolumn{1}{c}{trimestral (\%)}   & \multicolumn{1}{c}{(días)}   \\
    \midrule
    \input{tablas/iess_titul_detalle_inv.tex}
    %\bottomrule
  \end{tabular}
    }
    \caption*{\scriptsize Fuente: Subgerencia de Banca de Inversión - BIESS. \\
  Elaborado: DAIE.}
  \end{center}
\end{table}

A 31 de diciembre de 2020, se encuentran invertidos USD 3.105.940,54, de los cuales la mayoría (75,67\%) se encuentra invertidos en titularizaciones de la empresa GUAYAQUIL COUNTRY CLUB S.A. (USD 2.850.000,00) y lo restante en la empresa Inmobiliaria Volann (USD 341.311,31).

% % --------------------------------------------------------------------------------------------------
\subsection{Inversiones no privativas con renta variable}

La renta variable es un tipo de inversión formada por todos aquellos activos financieros en los que la rentabilidad es incierta. Es decir, la rentabilidad no está garantizada ni la devolución del capital invertido ni la rentabilidad del activo. En la renta variable, al contrario que en la renta fija, no conocemos los flujos de caja que vamos a recibir por parte de la empresa. Incluso, puede que la rentabilidad sea negativa.

Las inversiones no privativas en renta variable del Fondo del Seguro IVM pueden realizar las siguientes operaciones en fideicomisos mercantiles de inversión, inmobiliarios y  administración de acciones de cuotas  de  participación  en fondos de inversión.

% --------------------------------------------------------------------------------------------------
\subsubsection{Inversiones en fideicomisos y negocios fiduciarios}

% Se entiende por fideicomiso mercantil el contrato por el cual una o más personas llamadas
% constituyentes o fideicomitentes transfieren, de manera temporal e irrevocable, la propiedad de
% bienes muebles o inmuebles corporales o incorporales, que existen o se espera que existan, a un
% patrimonio autónomo, dotado de personalidad jurídica para que la sociedad administradora de fondos y
% fideicomisos, que es su fiduciaria y en tal calidad su representante legal, cumpla con las
% finalidades específicas instituidas en el contrato de constitución, bien en favor del propio
% constituyente o de un tercero llamado beneficiario.  En términos legales LA FIDUCIA MERCANTIL es
% definida como ``un negocio jurídico en virtud de la cual una persona, llamada fiduciante o
% fideicomiso, transmite uno o más bienes especificados a otra, llamado fiduciario, quien se obliga a
% administrarlos o enajenarlos para cumplir una finalidad determinada por el constituyente, en
% provecho de este o de un tercero llamado beneficiario o fideicomisario''.

En la figura \ref{fig:iess_fidecomisos_hist_inv} y la tabla \ref{tab:iess_fidecomisos_hist_inv}, se muestra la evolución histórica de las inversiones en fideicomisos y negocios fiduciarios, en valor nominal, registrados en el portafolio de inversiones del Fondo del Seguro IVM y su rendimiento promedio ponderado durante el período 2011 a 2020, a diciembre de cada año.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica del saldo remanente, en valor nominal, de las inversiones en fideicomisos y negocios fiduciarios del Seguro IVM y su rendimiento promedio ponderado}
\label{fig:iess_fidecomisos_hist_inv}
\includegraphics[scale=1]{graficos/iess_fidecomisos_hist_inv.png}
  \caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS. \\
  {\bf Elaborado:} DAIE.}
\end{figure}

\begin{table}[H]
\captionsetup{justification=centering}
  \begin{center}
  \caption{Evolución de las inversiones del Fondo del Seguro IVM en Fideicomisos}
  \label{tab:iess_fidecomisos_hist_inv}
  {\fontsize{10}{12}\selectfont
  \begin{tabular}{crcc}
    \toprule
 \multicolumn{1}{c}{Año} & \multicolumn{1}{c}{Saldo} & \multicolumn{1}{c}{Rendimiento Promedio} & \multicolumn{1}{c}{Rendimiento Promedio}\\
  & \multicolumn{1}{c}{Valor Nominal (USD)} & \multicolumn{1}{c}{Ponderado (\%)} & \multicolumn{1}{c}{Ponderado Real (\%)}\\
    \midrule
    \input{tablas/iess_fidecomisos_hist_inv.tex}
%    \bottomrule
  \end{tabular}
    }
  \caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS. \\
  {\bf Elaborado:} DAIE.}
  \end{center}
\end{table}
El rendimiento promedio ponderado, primeramente, ha tendido a crecer en el tiempo, de 7,9\% a 9,27\% entre los años 2011 y 2014, respectivamente, y, más tarde, ha tendido a decrecer de 9,27\% a 3,58\% entre los años 2014 y 2020, respectivamente. Su rendimiento promedio es 6,09\% durante el período 2011 a 2020 El saldo remanente en valor nominal decreció de USD 223.166.171,75 en diciembre de 2012 a USD 135.343.974,02 en diciembre de 2020 (decreció 39,35\%), año en el cual obtuvo su mínimo; en
cambio, a diciembre de 2013, se registró su máximo.

% --------------------------------------------------------------------------------------------------
\subsubsection{Inversiones en acciones (en renta variable)}

En la figura \ref{fig:iess_rv_hist_inv} y la tabla \ref{tab:iess_rv_hist_inv}, se muestra la evolución histórica del saldo remanente (valor del mercado de las acciones) de renta variable registrado en el portafolio de inversiones del Fondo del Seguro IVM y su rendimiento promedio ponderado durante el período 2011 a 2020, a diciembre de cada año. Se puede observar como el rendimiento promedio ponderado, primeramente, ha tendido a crecer de 9,73\% a 20,02\% entre los años 2011 y 2013, respectivamente,  más tarde, ha tendido a decrecer de 20,02\% a -4,49\% entre los años 2013 y 2016, respectivamente; y, finalmente, su rendimiento promedio ponderado creció de -4,49\% a 8,32\% entre los años 2016 y 2018; y, finalmente, decreció a -1,12\% en 2020, lo cual muestra su alta volatilidad en el
rendimiento de estas inversiones (desviación estándar igual a 7,61\% y promedio igual a 5,14\%).

El valor del mercado de las acciones evolucionó de la siguiente manera: primero, creció de USD
56.278.303,00 en diciembre de 2011 a USD 121.413.740,00 en diciembre de 2015 (creció 115,76\%);
luego, sucede una abrupta caída del fondo a USD 82.818.786,85 entre 2015 y 2016, respectivamente;
por último, el valor de mercado de las acciones en renta variable se situó en USD 90.892.339,83 a diciembre de 2020
\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Evolución histórica del saldo remanente, en valor nominal, de las inversiones en renta
variable del Seguro IVM y su rendimiento promedio ponderado}
\label{fig:iess_rv_hist_inv}
\includegraphics[scale=.8]{graficos/iess_rv_hist_inv.png}
  \caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS. \\
  {\bf Elaborado:} DAIE.}
\end{figure}

\begin{table}[H]
\captionsetup{justification=centering}
  \begin{center}
  \caption{Evolución de las inversiones del Fondo del Seguro IVM en acciones de renta variable}
  \label{tab:iess_rv_hist_inv}
 {\fontsize{10}{12}\selectfont
  \begin{tabular}{crrr}
    \toprule
 \multicolumn{1}{c}{Año} & \multicolumn{1}{c}{Saldo} & \multicolumn{1}{c}{Rendimiento Promedio} & \multicolumn{1}{c}{Rendimiento Promedio} \\
  & \multicolumn{1}{c}{Valor Nominal (USD)} & \multicolumn{1}{c}{Ponderado (\%)} & \multicolumn{1}{c}{Ponderado Real (\%)} \\
    \midrule
    \input{tablas/iess_rv_hist_inv.tex}
 %   \bottomrule
  \end{tabular}
    }
  \caption*{\scriptsize {\bf Fuente:} Subgerencia de Banca de Inversión - BIESS. \\
  {\bf Elaborado:} DAIE.}
  \end{center}
\end{table}

A 31 de diciembre del 2020, las inversiones de renta variable en acciones alcanzaron un valor de mercado por USD 90.892.339,83. El detalle de las acciones a 31 de diciembre de 2020 se encuentra la tabla
% \ref{tab:iess_acciones_inv}
, en la cual se detalla: el valor nominal de una acción (es el valor
total inicial o de emisión que tienen las acciones, es decir, es el resultado de multiplicar el
número de acciones compradas por el valor  nominal de emisión por acción), valor efectivo total
(valor de compra de la totalidad de las acciones), precio de compra por acción, número de acciones
compradas, valor nominal por acción (es el valor inicial o de emisión que tienen las acciones, es
decir, es el resultado de dividir el capital de una sociedad por el número de acciones de la misma),
precio al corte (31 de diciembre de 2020) y valor de mercado de las acciones (es el precio al corte
por acción multiplicado por el número de acciones).

% El portafolio del Fondo del Seguro IVM en renta variable abarca acciones de trece (13) empresas,
% entre las más importantes están: 8.539.599 acciones de HOLDING TONICORP con un valor en el mercado
% igual a USD 38.428.195,50 (39,86\% de las inversiones en este instrumento financiero) y 8.404.623
% acciones de LA FAVORITA con un valor en el mercado igual a USD 20.507.280,12 (21,27\% de las
% inversiones en este instrumento financiero).
%
% Las inversiones en acciones que han producido rendimientos positivos al Fondo del Seguro IVM son:
% HOLCIM, CONCLINA C.A., HOLDING TONICORP, SENDERO FORESTA S.A., SUPERDEPORTE S.A., SURPAPELCORP,
% ALICOSTA BK HOLDIN y LA FAVORITA. En cambio, las acciones de CARLOS SOC. AG, INDUSTRIAS ALES C.A. y
% SAN CARLOS SOC. AG han generado perdidas al portafolio.
%
% \begin{landscape}
% {\fontsize{10}{11}\selectfont
% \begin{longtable}[H]{l*{7}{r}}
% \caption{Detalle de las inversiones del Fondo del Seguro IVM en acciones en renta variable a 31 de diciembre de 2018} \\
% \label{tab:iess_acciones_inv} \\
% \toprule
% \multicolumn{1}{l}{Nombre del emisor de las acciones:} & \multicolumn{1}{c}{Valor Nominal} & \multicolumn{1}{c}{Valor efectivo}  & \multicolumn{1}{c}{Precio de}    & \multicolumn{1}{c}{No.}                        & \multicolumn{1}{c}{Valor nominal}   & \multicolumn{1}{c}{Precio}      & \multicolumn{1}{c}{Valor de}\\
%         &  \multicolumn{1}{c}{(USD)}        &    \multicolumn{1}{c}{total (USD)}& \multicolumn{1}{c}{compra (USD)} & \multicolumn{1}{c}{acciones} & \multicolumn{1}{c}{por acción (USD)}& \multicolumn{1}{c}{actual (USD)}& \multicolumn{1}{c}{mercado (USD)}\\
% \midrule
% \endfirsthead
%
% \toprule
% \multicolumn{1}{l}{Nombre del emisor de las acciones:} & \multicolumn{1}{c}{Valor Nominal} & \multicolumn{1}{c}{Valor efectivo}  & \multicolumn{1}{c}{Precio de}    & \multicolumn{1}{c}{No.}                        & \multicolumn{1}{c}{Valor nominal}   & \multicolumn{1}{c}{Precio}      & \multicolumn{1}{c}{Valor de}\\
%         &  \multicolumn{1}{c}{(USD)}        &    \multicolumn{1}{c}{total (USD)}& \multicolumn{1}{c}{compra (USD)} & \multicolumn{1}{c}{acciones} & \multicolumn{1}{c}{por acción (USD)}& \multicolumn{1}{c}{actual (USD)}& \multicolumn{1}{c}{mercado (USD)}\\
% \midrule
% \endhead
% \bottomrule \multicolumn{8}{c}{continúa...} \\
% \endfoot
% \bottomrule
%   \caption*{\scriptsize Fuente: Subgerencia de Banca de Inversión - BIESS. \\
%   Elaborado: DAIE.}
% \endlastfoot
% \input{tablas/iess_acciones_inv.tex}
% \end{longtable}
% }
% \end{landscape}
% % --------------------------------------------------------------------------------------------------
\subsection{Otras inversiones menores}
El portafolio del Fondo del Seguro IVM también posee otras inversiones, además de las expuestas
anteriormente, que se enumeran, a continuación:
\begin{enumerate}[label=\arabic*.,topsep=0pt,itemsep=1ex,parsep=1ex,partopsep=1ex]
\item Inversiones en Certificados de Tesorería por USD 60.904.987,20 y USD 50.044.114,59 a diciembre
	de los años 2012 y 2014, respectivamente, a plazos remanentes iguales a 171 y 16 días para
	el mismo período de tiempo, y rendimiento igual a 3\% y 1,27\% para los años citados.

\item Inversiones en Papeles Comerciales por USD 1.200.000 a plazos de 249 días a 31 de diciembre de
	2014 con rendimiento igual a 6,48\% y rendimiento real igual 2,71\%.

\item Reportos por USD 117.000 a plazo de 68 días y rendimiento igual a 6,76\% a 31 de diciembre de 2014.
\end{enumerate}

%---------------------------------------------------------------------------------------------------


%---------------------------------------------------------------------------------------------------
\section{Causas de desfinanciamiento}
\label{chp_infofinan:causasdesf}

En esta Sección se presentan las principales causas de desfinanciamiento que sufrió el fondo
desde el año 2015 hasta la fecha de corte del estudio, las cuales se describen a continuación:

\begin{enumerate}

% \item La ausencia de la contribución del Estado al IESS por el pago del 40\% de las
% 	pensiones y otras obligaciones que tiene el Estado con IESS.
% 	%es USD 5.879.175.192,69 (USD	5.194.761.260,54 capital y USD 684.413.932,15 lucro cesante).

% \item Cambio de las tasas de aportación de la Resolución No. C.D. 261 por la Resolución No. C.D.
% 	501.
	%se dejaron de percibir USD 2.475.438.655,70 (USD 2.197.056.726,20 capital y	278.381.929,50 lucro cesante).

\item Desinversiones realizadas desde enero de 2015 hasta la fecha corte del estudio. 
(USD 6.544.924.945,00) a la fecha de corte no permitieron que el fondo reciba USD 567.546.851,24 (lucro cesante).
\end{enumerate}

% En consecuencia, el impacto de estas causas de desfinanciamiento sobre el patrimonio de este fondo
% se resume en la tabla \ref{tab:impacto_patrimonio}:
% \begin{table}[htbp]
% \begin{center}
% \caption{Impacto sobre el patrimonio}
% \label{tab:impacto_patrimonio}
%  \resizebox{\columnwidth}{!}{%
% \begin{tabular}{lrrrc}
% \toprule
% \multicolumn{1}{l}{Concepto:}   & \multicolumn{1}{c}{Capital} & \multicolumn{1}{c}{Lucro Cesante}     & \multicolumn{1}{c}{Total}     &\multicolumn{1}{c}{\% del PIB 2018}\\ 
% \midrule
% Ausencia contribución del 40\% Estado       & 5.194.761.260,54        & 737.423.438,33     & 5.932.184.698,87  &  5,47\%  \\ 
% Diferencia aportes C.D. 261 Y C.D. 501      & 2.197.056.726,20        & 278.381.929,50     & 2.475.438.655,70  & 2,28\%\\ 
% Desinversiones                              &                         & 519.387.111,52     & 519.387.111,52    &  0,48\%\\ 
% \midrule
% Total                                       & 7.391.817.986,74        & 1.535.192.479,35   & 8.927.010.466,09     &   8,24\%\\ 
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize Fuente: DAIE y Balances Financieros del IESS. \\
%             Elaborado: DAIE.}
% \end{center}
% \end{table}
% 
% De no producirse los decrementos antes citados, el patrimonio a 31 de diciembre de 2018 debería
% incrementar en USD 8.927.010.466,09. Es decir, el patrimonio a la fecha de corte sería USD
% 15.470.212.225,85 (USD 8.927.010.466,09 + USD 6.543.201.759,76) y no USD 6.543.201.759,76 que se
% registra en la actualidad. El valor que el fondo dejó de percibir representa el 8,24\% del PIB del 2018. 
% 
% En las subsecciones \ref{chp_resultados:sin_contrib_estado}, \ref{chp_resultados:cd_501} y
% \ref{tab:iess_IVM_desinvertido_anual}, se muestran a detalle los valores
% no percibidos por Fondo del Seguro del IVM que se encuentran en la tabla
% \ref{tab:impacto_patrimonio}.

% \subsection{Ausencia de la contribución del Estado }
% \label{chp_resultados:sin_contrib_estado}
% 
% De los resultados presentados en la tabla \ref{tab:sin_contrib_estado}, se obtiene que el Estado,
% por el período abril de 2015 a 31 de diciembre de 2018, dejó de contribuir al IVM para el
% financiamiento de las pensiones y las decimotercera y decimocuarta pensiones, un monto de USD
% 5.194.761.260,54; obligando a realizar desinversiones para cubrir el pago prestacional. 
% 
% Se calcula que el IVM dejó de percibir USD 737.423.438,33 como rendimiento de estos
% valores, dando un total de  USD 5.932.184.698,87.  El cálculo se realiza aplicando la determinación de intereses en concordancia con el criterio de crecimiento de las reservas en los seguros, por el tiempo transcurrido desde abril de 2015 a la fecha de corte, período en el cual los intereses se suman al capital al final de cada año y este forma un nuevo capital que sirve para determinar el nuevo valor del lucro cesante. Si confrontamos este valor frente al valor del PIB a 31 de diciembre de 2018, de USD 108.398.058.000, representa el
% 5,47\%.
% \begin{landscape}
% \vspace*{\fill}
% \begin{table}[H]
% {\fontsize{9}{11}\selectfont
% \caption{Ausencia de la contribución del Estado}
% \label{tab:sin_contrib_estado}
%  \resizebox{\columnwidth}{!}{%
% \begin{tabular}{crrcrrrrrr}
% \toprule
% \multicolumn{1}{c}{Año} & \multicolumn{1}{c}{Valor de las}    & \multicolumn{1}{c}{Contribución del
% Estado} & \multicolumn{1}{c}{Rendimiento}   & \multicolumn{1}{c}{Rendimiento}     &
% \multicolumn{1}{c}{Rendimiento} & \multicolumn{1}{c}{Rendimiento}                   &
% \multicolumn{1}{c}{Rendimiento} & \multicolumn{1}{c}{Intereses}   & \multicolumn{1}{c}{Capital} \\ 
% &  \multicolumn{1}{c}{pensiones (USD)}& \multicolumn{1}{c}{no percibida (USD)}      &
% \multicolumn{1}{c}{anual neto (\%)}& \multicolumn{1}{c}{acumulado 2015 (USD)}
% &\multicolumn{1}{c}{acumulado 2016 (USD)}     &\multicolumn{1}{c}{acumulado 2017 (USD)}         &
% \multicolumn{1}{c}{acumulado 2018 (USD)}& \multicolumn{1}{c}{total (USD)}& \multicolumn{1}{c}{+ Intereses (USD)}\\
% \midrule
%     \input{tablas/iess_IVM_Desfi_Aportes_Estado.tex}
% \midrule
% \end{tabular}
% }
% }
% \caption*{\scriptsize Fuente: Dirección del Sistema de Pensiones. \\
%             Elaborado: DAIE.\\}
% \end{table}
% \vspace*{\fill}
% \end{landscape}
% 
% %---------------------------------------------------------------------------------------------------
% \subsection{Cambio de primas de aportes por aplicación de la Resolución No. C.D. 501}
% \label{chp_resultados:cd_501}
% 
% La Resolución No. C.D. 501 de 13 de noviembre de 2015, cambió las
% tasas de aportación del Seguro IVM, trayendo como
% consecuencia la disminución de los ingresos por aportes desde noviembre de 2015 hasta la fecha corte 
% del estudio. Las tasas de aportación de las Resoluciones No. C.D. 261 y 501 se
% pueden apreciar en la siguiente tabla \ref{tab:compara_primas} y figura \ref{fig:comp_tas_apo}.
% 
% \begin{figure}[H]
% \centering
% \caption{Comparación de las primas de aportes: Resolución C.D. 501 – Resolución C.D. 261}
% \label{fig:comp_tas_apo}
% \includegraphics[scale=1]{graficos/iess_grafico_tasas_aporte.png}
% \caption*{\scriptsize Fuente: Resoluciones No. C.D.501 y No. C.D.261 \\
%             Elaborado: DAIE.}
% \end{figure}
% 
% Esta reducción de las tasas de aportación se evidencia en la figura \ref{fig:comp_tas_apo}. El área 
% comprendida entre los puntos A, B, C y D muestra la afectación causada por esta resolución.  
% 
% \begin{table}[H]
% {\fontsize{8}{10}\selectfont
% \centering
% \caption{Comparación de las primas de aportes}
% \label{tab:compara_primas}
% \begin{tabular}{crr}
% \toprule
% \multicolumn{1}{c}{Año} & \multicolumn{1}{c}{Tasa de Aportación}  &\multicolumn{1}{c}{Tasa de Aportación}  \\ 
% \multicolumn{1}{c}{Año} & \multicolumn{1}{c}{Resolución C.D. 501} & \multicolumn{1}{c}{Resolución C.D. 261} \\ 
% \midrule
% 2012 & - & 9,74\% \\ 
% 2013 & - & 9,74\% \\ 
% 2014 & - & 9,74\% \\ 
% 2015 & 5,96\% & 9,74\% \\ 
% 2016 & 5,96\% & 9,74\% \\ 
% 2017 & 6,90\% & 9,74\% \\ 
% 2018 & 7,76\% & 9,74\% \\ 
% 2019 & 8,96\% & 9,74\% \\ 
% 2020 & 9,96\% & 9,74\% \\ 
% 2021 & 10,56\% & 9,74\% \\ 
% 2022 & 10,56\% & 9,74\% \\ 
% \bottomrule
% \end{tabular}
% \caption*{\scriptsize Fuente: Resoluciones CD.501 y CD.261 \\
%             Elaborado: DAIE.}
% }
% \end{table}
% 
% La diferencia de aporte entre las dos resoluciones considerando la masa salarial y los ingresos
% recibidos por aportaciones al Seguro IVM para los diferentes años en análisis se presenta en la
% tabla \ref{tab:impacto_CD501}. Se observa que el fondo dejó de percibir como aportes USD
% 2.197.056.726,00, lo que produjo un lucro cesante de USD 278.381.929,50 a 31 de
% diciembre de 2018, obteniéndose un perjuicio total de USD 2.475.438.655,70, valor que frente al PIB representa el 2,28\%.
% 
% \begin{landscape}
% \vspace*{\fill}
% \begin{table}[H]
% \begin{center}
% {\fontsize{8.5}{11}\selectfont
% \caption{Impacto de la aplicación de la Resolución No. C.D. 501}
% \label{tab:impacto_CD501}
%   \resizebox{\columnwidth}{!}{%
% \begin{tabular}{crrrrrrrrrr} 
% \toprule
% \multicolumn{1}{c}{Año} & \multicolumn{1}{c}{Aportes C.D. 261} & \multicolumn{1}{c}{Aportes}       &
% \multicolumn{1}{c}{Diferencia} & \multicolumn{1}{c}{Rendimiento} & \multicolumn{1}{c}{Rendimiento}
% & \multicolumn{1}{c}{Rendimiento }       & \multicolumn{1}{c}{Rendimiento}         &
% \multicolumn{1}{c}{Rendimiento}   & \multicolumn{1}{c}{Intereses} & \multicolumn{1}{c}{Capital} \\
% &  \multicolumn{1}{c}{C.D. 261 (USD)} & \multicolumn{1}{c}{C.D. 501 (USD)}&
% \multicolumn{1}{c}{(USD)}   & \multicolumn{1}{c}{neto (\%)}    & \multicolumn{1}{c}{acumulado 2015
% (USD)}& \multicolumn{1}{c}{acumulado 2016 (USD)}& \multicolumn{1}{c}{acumulado 2017 (USD)}&
% \multicolumn{1}{c}{acumulado 2018 (USD)} & \multicolumn{1}{c}{Total (USD)}& \multicolumn{1}{c}{+
% Interés (USD)} \\
% \midrule
%     \input{tablas/iess_IVM_Desfi_CD501.tex}
% \bottomrule
% \end{tabular}
% }
% \caption*{\scriptsize Fuente: Dirección del Sistema de Pensiones. \\
%             Elaborado: DAIE.}
% }
% \end{center}
% \end{table}
% \vspace*{\fill}
% \end{landscape}
% 



%---------------------------------------------------------------------------------------------------
\subsection{Desinversiones del portafolio de inversiones del Fondo del Seguro IVM}
\label{tab:iess_IVM_desinvertido_anual}

% La desinversión es retirar fondos del BIESS que podrían ir a inversiones y se le denomina en el
% presupuesto como ´´Recuperación de inversiones''. Debido a que los ingresos (aportes a la seguridad
% social, rentas de inversiones y multas, transferencias y donaciones corrientes, y otros ingresos) no
% se equiparan a los egresos (gastos prestacionales, otros gastos, gastos de inversión y gastos de
% capital) desde finales del año 2014 y, además, a la eliminación de la obligatoriedad de entregar la
% contribución del 40\% de las pensiones.

En el año 2015, se desinvirtió USD 345.000.000 versus los USD 16.718.036 presupuestado (ver
Resolución No. C.D. 475). Para el año 2016, sin el aporte del Estado por el pago del 40\% de las
pensiones y otras contribuciones del Estado con el IESS, el monto desinvertido fue USD 1.649.264.945
versus los USD 1.588.573.549 presupuestado (ver Resolución No. C.D. 507). Las desinversiones
siguieron creciendo en el año 2017 a USD 1.755.000.000 versus lo presupuestado (USD) 1.752.870.540
(ver Resolución No. C.D. 545). Por último, en el año 2018, se desinvirtió (USD) 1.762.660.000 versus
los (USD) 1.669.581.655 presupuestado (ver Resolución No. C.D. 567). De esta manera, las
desinversiones sirvieron para cubrir la brecha entre ingresos y gastos(ver tabla
\ref{tab:iess_IVM_desinvertido_vs_presupuestado}).

\begin{table}[H]
\begin{center}
  \caption{Monto desinvertido anual contra el presupuestado del Fondo del Seguro IVM}
  \label{tab:iess_IVM_desinvertido_vs_presupuestado}
{\fontsize{10}{12}\selectfont  
\begin{tabular}{@{}lrrrc@{}}
\toprule
\multirow{2}{*}{Año} & \multicolumn{1}{c}{Desinversión}   & \multicolumn{1}{c}{Desinversión}       & \multicolumn{1}{c}{Diferencia} & Resolución No.\\
                     & \multicolumn{1}{c}{realizada (USD)} & \multicolumn{1}{c}{presupuestada (USD)} & \multicolumn{1}{c}{(USD)}      & C.D.             \\ \midrule
2015                 & 345.000.000                         & 16.718.036                              & 328.281.964                    & 475            \\
2016                 & 1.649.264.945                       & 1.588.573.549                           & 60.691.396                     & 507            \\
2017                 & 1.755.000.000                       & 1.752.870.540                           & 2.129.460                      & 545            \\
2018                 & 1.762.660.000                       & 1.669.581.655                           & 93.078.345                     & 567            \\ \midrule
Total                & 5.511.924.945,00            & \multicolumn{3}{r}{}                                                                      \\ \bottomrule
\end{tabular}
}
  \caption*{\scriptsize Fuente: Dirección de Tesorería - BIESS y Resoluciones No. C.D 475, C.D. 507, C.D. 545 y C.D. 567. \\
  Elaborado: DAIE.}
  \end{center}
\end{table}

% \begin{table}[H]
%   \begin{center}
%   \caption{Monto desinvertido del Fondo del Seguro IVM y su lucro cesante}
%   \label{tab:iess_IVM_desinversiones}
%   \resizebox{\columnwidth}{!}{%
%   \begin{tabular}{crccrrr}
%     \toprule
% \multicolumn{1}{c}{Fecha} & \multicolumn{1}{c}{Capital desinvertido} &
% \multicolumn{1}{c}{Rentabilidad} & \multicolumn{1}{c}{Rentabilidad neta} &
% \multicolumn{1}{c}{Factor} & \multicolumn{1}{c}{Lucro cesante} &  \multicolumn{1}{c}{Lucro Cesante +
% capital} \\
% & \multicolumn{1}{c}{(USD)} & \multicolumn{1}{c}{neta (\%)}          &
% \multicolumn{1}{c}{mensualizada (\%)} &       &    \multicolumn{1}{c}{(USD)}      &
% \multicolumn{1}{c}{desinvertido (USD)} \\
%     \midrule
%     \input{tablas/iess_IVM_desinversiones.tex}
%     \bottomrule
%   \end{tabular}
%     }
%   \caption*{\scriptsize Fuente: Dirección de Tesorería-BIESS. \\
%   Elaborado: DAIE.}
%   \end{center}
% \end{table}



{\fontsize{9}{10}\selectfont
\begin{longtable}[H]{crccrrr}
\caption{Monto desinvertido del Fondo del Seguro IVM y su lucro cesante} \\
\label{tab:iess_IVM_desinversiones} \\
\toprule
\multicolumn{1}{c}{Fecha:} & \multicolumn{1}{c}{Capital desinvertido} &
\multicolumn{1}{c}{Rentabilidad} & \multicolumn{1}{c}{Rentabilidad neta} &
\multicolumn{1}{c}{Factor} & \multicolumn{1}{c}{Lucro cesante} &  \multicolumn{1}{c}{Lucro Cesante +
capital} \\
& \multicolumn{1}{c}{(USD)} & \multicolumn{1}{c}{neta (\%)}          &
\multicolumn{1}{c}{mensualizada (\%)} &       &    \multicolumn{1}{c}{(USD)}      &
\multicolumn{1}{c}{desinvertido (USD)} \\
\midrule
\endfirsthead
\toprule
\multicolumn{1}{c}{Fecha} & \multicolumn{1}{c}{Capital desinvertido} &
\multicolumn{1}{c}{Rentabilidad} & \multicolumn{1}{c}{Rentabilidad neta} &
\multicolumn{1}{c}{Factor} & \multicolumn{1}{c}{Lucro cesante} &  \multicolumn{1}{c}{Lucro Cesante +
capital} \\
& \multicolumn{1}{c}{(USD)} & \multicolumn{1}{c}{neta (\%)}          &
\multicolumn{1}{c}{mensualizada (\%)} &       &    \multicolumn{1}{c}{(USD)}      &
\multicolumn{1}{c}{desinvertido (USD)} \\
\midrule
\endhead
\bottomrule \multicolumn{4}{c}{continúa...} \\
\endfoot
%\bottomrule
\caption*{\scriptsize Fuente: Dirección de Tesorería-BIESS. \\
  Elaborado: DAIE.}
\endlastfoot
 \input{tablas/iess_IVM_desinversiones.tex}
\end{longtable}
}

Para el cálculo del lucro cesante (ingresos financieros dejados de percibir por las
desinversiones), se emplearon las tasas de rendimiento neto según la metodología 
``Cálculo de rendimientos financieros de los Fondos Previsionales administrados por el
Banco del Instituto Ecuatoriano de Seguridad Social´´ de la tabla \ref{tab:iess_rend_inv}. En primer
lugar, se utiliza una tasa equivalente mensual, puesto que las tasas de rendimiento netas $i_t$ son
anuales al momento $t$ de la inversión.
\begin{equation}
  j_t = ( 1 + i_t )^{\frac{1}{12}} - 1
\end{equation}

Una vez obtenida la tasa de rendimiento equivalente mensual, se procede a calcular el lucro cesante,
suponiendo la capitalización mensual de los intereses a una tasa de rendimiento neta del
correspondiente año de la siguiente manera:
\begin{equation}
L_t = \left( \prod\limits_{k = 1}^{12} \left( 1 + j_{t + \frac{k}{12}} \right) - 1 \right) C_t
\end{equation}

Donde $L_t$ es el lucro cesante de la desinversión/inversión correspondiente tiempo $t$, medido en 
años, $C_t$ es el capital desinvertido/invertido en el tiempo $t$; y $j_t$ es la  tasa de 
rendimiento correspondiente al momento $t$.

Aplicando las suposiciones y metodología expuesta, se concluye que el monto desinvertido entre marzo
2015 a diciembre de 2018 es USD 5.511.924.945,00, por lo cual el IESS dejó de percibir USD
519.387.111,48 por lucro cesante por las desinversiones; es decir, que el perjuicio al Fondo del
Seguro IVM por desinversiones es USD 6.031.312.056,52 en total. En la siguiente tabla , se registra
el capital desinvertido, lucro cesante y su total desinvertido para cada año
desde 2015 (ver tabla \ref{tab:iess_IVM_desinvertido_anual}).





\begin{table}[H]
\begin{center}
  \caption{Capital desinvertido anual del Fondo del Seguro IVM y su lucro cesante}
  \label{tab:iess_IVM_desinvertido_anual}
{\fontsize{10}{12}\selectfont
\begin{tabular}{crrr}
\toprule
\multirow{1}{*}{Año} & \multicolumn{1}{c}{Capital}        & \multicolumn{1}{c}{Lucro Cesante} &\multicolumn{1}{c}{Lucro Cesante +}\\
                    &\multicolumn{1}{c}{desinvertido (USD)}& \multicolumn{1}{c}{(USD)}          &\multicolumn{1}{c}{capital desinvertido (USD)}\\
\midrule
2015  & 345.000.000,00    & 148.585.046,60    & 493.585.046,60 \\
2016  & 1.649.264.945,00  & 543.277.772,64  & 2.192.542.717,64\\
2017  & 1.755.000.000,00  & 410.818.114,64  & 2.165.818.114,64\\
2018  & 1.762.660.000,00  & 290.677.625,44  & 2.053.337.625,44\\
2019  & 0,00              & 0,00            & 0,00\\
2020  & 1.033.000.000,00  & 30.088.427,21   & 1.063.088.427,21\\
\midrule
Total & 6.544.924.945,00 & 1.423.446.986,53 & 7.968.371.931,53\\
\bottomrule
\end{tabular}
}
  \caption*{\scriptsize Fuente: Dirección de Tesorería-BIESS y DAIE. \\
  Elaborado: DAIE.}
  \end{center}
\end{table}
