\begin{landscape}
\chapter{Anexos: Estudio Actuarial del SIVM-IESS 2010-2020}
%ANEXO 1 -------------------------------------------------------------
\begin{itemize}
  \item { \textbf{Descripci\'{o}n de la cuenta ACTIVO}}
\end{itemize}
\begin{table}[H]
\captionsetup{justification=centering}
\begin{center} % centering{}
  \label{tab:iess_anex_activos_ivm}
  {\fontsize{8}{9}\selectfont
  \begin{tabular}{lrrrrrrrrrrrr} %r right
    \toprule
    Cod.    & Descripción     & 2010 & 2011 & 2012 & 2013 & 2014 & 2015 & 2016 & 2017 & 2018 & 2019 & 2020\\
    cuentas & de las cuentas  &      &      &      &      &      &      &      &      &      &      &      \\
    \midrule
    71 & ACTIVO & 4.743.411.828 & 5.366.910.437 & 6.369.418.968 & 7.732.707.700 & 9.079.987.134 & 9.601.539.775 & 8.607.195.791 & 7.866.175.219 & 6.726.773.090 & 8.574.586.523 & 8.345.918.690 \\
   \hline
\hspace*{3mm}711 & Fondos Disponibles & 144.386.613 & 102.392.856 & 109.726.638 & 41.651.356 & 17.821.585 & 46.037.712 & 11.485.362 & 15.227.198 & 233.025.635 & 137.481.897 & 125.696.798 \\
   \hline
\hspace*{3mm}714 & Recursos/Administra x El BIESS & 3.006.420.853 & 2.993.528.057 & 5.156.022.283 & 6.528.183.254 & 7.868.943.050 & 8.537.761.132 & 7.468.154.203 & 6.629.654.761 & 5.215.026.161 & 5.753.891.730 & 5.746.473.714 \\
   \hline
\hspace*{3mm}715 & Cuentas por Cobrar & 20.860.995 & 26.398.186 & 27.440.748 & 921.540.338 & 959.043.142 & 774.843.969 & 855.279.874 & 948.107.077 & 983.058.202 & 2.364.674.766 & 2.109.729.860 \\
   \hline
\hspace*{3mm}7155 & Deuda del Gobierno & 1.225.930.076 & 1.900.210.123 & 799.208.401 &  &  &  &  &  &  &  &  \\
   \hline
\hspace*{3mm}718 & Propiedad Planta y Equipo & 273.275.359 & 267.242.027 & 204.556.062 & 218.878.748 & 227.763.743 & 237.440.679 & 265.946.059 & 266.281.678 & 270.279.955 & 293.154.994 & 338.635.182 \\
   \hline
\hspace*{3mm}7165 & Intereses por Cobrar & 170.597 & 3.070.319 & 3.070.319 &  &  &  &  &  &  &  &  \\
   \hline
\hspace*{3mm}719 & Otros Activos & 72.367.335 & 74.068.869 & 69.394.516 & 22.454.005 & 6.415.614 & 5.456.283 & 6.330.293 & 6.904.505 & 25.383.136 & 25.383.136 & 25.383.136 \\
    \bottomrule
  \end{tabular}
  }
  
  \caption*{ \scriptsize Fuente: Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
  Elaborado: DAIE.}
  \end{center}
\end{table}

\begin{quotation}
\textbf{Nota:} Cabe mencionar que los balances del IESS correspondientes al periodo 2010 al 2020 han sufrido cambios en los códigos y creación de cuentas, por lo que se presenta la variación y optimización; un ejemplo de lo mencionado se encuentra en los componentes del activo, donde algunas partidas fueron afectadas de la siguiente manera:

\begin{itemize}
\item Entre el 2010 al 2012 en los balances constan las cuentas: “Inversiones Deuda Renta Fija Sector Público” (7120), “Inversiones Privativas” (7130); a partir del 2014 estas cuentas se funcionan en una sola cuenta registrada en el plan de cuentas como “Inversiones (12)”, a partir del año 2015 la cuenta “Inversiones” cambia de denominación a “Recursos/Administra x El BIESS” con el código 714.
\item A partir del 2013 al 2020 la cuenta “Deuda del gobierno (7155)” pasa a ser una subcuenta de “Cuentas por cobrar (715)” dentro del plan de cuentas, es por ello que en la tabla la cuenta “Deuda del Gobierno” no registra ningún valor a partir del año 2013 al 2018.
 \end{itemize}
\end{quotation}

% ANEXO 2 -------------------------------------------------------------
\begin{itemize}
  \item { \textbf{Descripci\'{o}n de la cuenta PASIVO}}
\end{itemize}
\begin{table}[H]
\captionsetup{justification=centering}
  \begin{center} % centering{}
  \label{tab:iess_anex_pasivos_ivm}
  {\fontsize{8}{9}\selectfont
  \begin{tabular}{lrrrrrrrrrrrr} %r right
    \toprule
    Cod.    & Descripción     & 2010 & 2011 & 2012 & 2013 & 2014 & 2015 & 2016 & 2017 & 2018 & 2019 & 2020\\
    cuentas & de las cuentas  &      &      &      &      &      &      &      &      &      &      &      \\
    \midrule
     72 & PASIVO & 826.863.706 & 430.592.236 & 227.039.672 & 214.663.349 & 118.866.196 & 136.187.201 & 183.214.111 & 236.213.620 & 183.571.331 & 1.111.157.137 & 469.254.677 \\
   \hline
\hspace*{3mm}7210 & Prestaciones y Beneficios & 385.209.900 & 42.996.325 & 95.522.064 &  &  &  &  &  &  &  &  \\
   \hline
\hspace*{3mm}7215 & Cuentas por Pagar & 227.970.116 & 385.992.831 & 129.900.185 & 214.663.349 & 118.866.196 &  &  &  &  &  &  \\
   \hline
\hspace*{3mm}7225 & Pasivo Diferido & 213.683.689 & 1.603.080 & 1.617.423 &  &  &  &  &  &  &  &  \\
   \hline
\hspace*{3mm}721 & Pasivos Corrientes &  &  &  &  &  & 12.556.147 & 3.410.682 & 53.453.565 & 4.360.589 & 303.142.899 & 6.775.849 \\
   \hline
\hspace*{3mm}722 & Pasivos no corrientes &  &  &  &  &  & 123.631.054 & 179.803.429 & 182.760.056 & 179.210.742 & 808.014.238 & 462.478.828 \\
      \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize Fuente: Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
  Elaborado: DAIE.}
  \end{center}
\end{table}

\begin{quotation}
\textbf{Nota:} Cabe mencionar que los balances del IESS en el período 2010-2020 sufrieron cambios en los códigos de cuentas: creación de cuentas, representación del pasivo con signo negativo, entre otros.\\ La cuenta del pasivo en el plan de cuentas, dentro del período del 2010 al 2014 tenía tres componentes. A partir del año 2015 al 2020 los tres componentes son optimizados en dos cuentas, en “Pasivos corrientes (721)” y “Pasivos no corrientes (722)".

\begin{itemize}
\item Hasta el año 2012 el pasivo contaba con las cuentas “Prestaciones y Beneficios”, “Cuentas por Pagar” y “Pasivo Diferido” representadas por los códigos: 7210, 7215 y 7225 respectivamente.
\item En los años 2013 y 2014 se eliminan los códigos 7210, 7215, 7225 y se sintetizan en una sola cuenta denominada “Cuentas por Pagar” establecida dentro de Plan de Cuentas con el código 21.
\item A partir del año 2015 al 2020 la partida con el código 21 es optimizada en dos cuentas “Pasivos corrientes (721)” y “Pasivos no corrientes (722)”.
\end{itemize}
\end{quotation}
\vspace*{\fill}

% ANEXO 3 -------------------------------------------------------------
\begin{itemize}
  \item {\textbf{Descripci\'{o}n de la cuenta PATRIMONIO}}
\end{itemize}
\begin{table}[H]
\captionsetup{justification=centering}
  \begin{center} % centering{}
  \label{tab:iess_anex_patrimonio_ivm}
  {\fontsize{8}{9}\selectfont
  \begin{tabular}{lrrrrrrrrrrrr} %r right
    \toprule
    Cod.    & Descripción     & 2010 & 2011 & 2012 & 2013 & 2014 & 2015 & 2016 & 2017 & 2018 & 2019 & 2020\\
    cuentas & de las cuentas  &      &      &      &      &      &      &      &      &      &      &      \\
        \midrule
    73      &  Patrimonio     & 3.916.548.122 & 4.936.318.201 & 6.142.379.296 & 7.518.044.351 & 8.961.120.938 & 9.465.352.575 & 8.423.981.681 & 7.629.961.598 & 6.543.201.760 & 7.463.429.386 & 7.876.664.013 \\ \hline
    \hspace*{3mm}731     & Fondos             &      &      &      &      &      &      &      &      &      &      &\\
            & Capitalizados & 2.336.577.017 & 3.905.495.015 & 4.911.967.784 & 4.921.471.763 & 7.444.124.705 & 9.008.459.573 & 9.469.938.085 & 8.390.825.492 & 7.602.216.697 & 6.521.611.764 & 7.433.608.165 \\ \hline
    \hspace*{3mm}33      & Resultados      & 1.517.093.137 & 967.562.240 & 1.167.150.565 & 2.604.010.340 & 1.507.659.496 & 430.290.282 & -1.103.185.190 & -813.551.009 & -1.138.575.172 & 826.511.106 & 243.452.205 \\ \hline
    \hspace*{3mm}734     & Super\'{a}vit       &      &      &      &      &      &      &      &      &      &      &\\
            & Revaluaci\'{o}n & 62.877.968 & 63.260.946 & 63.260.946 & -7.437.752 & 9.336.737 &  &  &  &  &  &  \\ \hline
    \hspace*{3mm}732     & Reservas &  &  &  &  &  & 26.598.455 & 57.224.519 & 52.687.115 & 79.560.235 & 115.306.515 & 199.603.642 \\
   \hline
    \hspace*{3mm}733     &  Aportes       &      &      &      &      &      &      &      &      &      &      &\\
            & Patrimoniales &      &      &      &      &  & 4.265   &   4.265 &      &      &      &\\
            \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize Fuente: Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
  Elaborado: DAIE.}
  \end{center}
\end{table}

\begin{quotation}
\textbf{Nota:} Cabe mencionar que los balances del IESS en el período 2010-2020 ha sufrido cambios en los códigos de cuentas, creación de cuentas, por las resoluciones emitidas por la Superintendencia de Bancos, en el año 2012 con la Resolución No. 0859 y en el año 2014 con la Resolución No. 0823 por lo que presenta variación y optimización en las siguientes partidas:

\begin{itemize}
\item Entre el año 2010 al 2014 el Patrimonio poseía tres cuentas como son “Fondos Capitalizados (731)”, “Resultados (734)” y “Superávit Revaluación (33)”; a partir del 2015 se crea la partida “Reservas (733)” en la que se fusiona como una subcuenta “Superávit Revaluación”.
\item Del mismo modo en el 2015 y 2016 aparece la cuenta “Aportes Patrimoniales (732)”, misma que es suprimida a partir del año 2017.
\end{itemize}
\end{quotation}
% \vspace*{3.5cm}
\newpage

% ANEXO 4 -------------------------------------------------------------
\begin{itemize}
  \item {\textbf{Descripci\'{o}n de la cuenta INGRESOS}}
\end{itemize}
\begin{table}[H]
\captionsetup{justification=centering}
  \begin{center} % centering{}
  \label{tab:iess_anex_ingresos_ivm}
  {\fontsize{8}{9}\selectfont
  \begin{tabular}{lrrrrrrrrrrrr} %r right
    \toprule
    Cod.    & Descripción     & 2010 & 2011 & 2012 & 2013 & 2014 & 2015 & 2016 & 2017 & 2018 & 2019 & 2020\\
    cuentas & de las cuentas  &      &      &      &      &      &      &      &      &      &      &      \\
    \midrule
    75 & INGRESOS & 2.090.738.982 & 2.489.029.423 & 2.928.237.323 & 3.414.375.937 & 3.928.504.635 & 3.417.853.901 & 2.248.961.728 & 2.927.751.386 & 2.872.919.503 & 5.157.545.282 & 4.928.141.341 \\
   \hline
\hspace*{3mm}751 & Ingresos  &      &      &      &      &      &      &      &      &      &      &\\
            & de la  Operaci\'{o}n & 1.828.887.310 & 2.322.633.510 & 2.655.038.148 & 2.999.780.744 & 3.400.733.855 & 2.887.573.305 & 1.656.007.539 & 2.010.590.806 & 2.426.258.334 & 4.589.514.998 & 4.393.046.590 \\
   \hline
\hspace*{3mm}752 & Ingresos &      &      &      &      &      &      &      &      &      &      &\\
            & Financieros & 261.851.672 & 166.395.912 & 273.199.174 & 351.341.096 & 463.435.847 & 521.036.250 & 586.849.925 & 910.713.585 & 376.995.454 & 544.357.377 & 532.019.019 \\
   \hline
\hspace*{3mm}753 & Ingresos por  &      &      &      &      &      &      &      &      &      &      &\\
            & Arriendo &  &  &  &  &  & 1.604.806 & 1.425.124 & 1.764.631 & 2.996.697 & 1.425.163 & 1.285.684 \\
   \hline
\hspace*{3mm}757 & Ingresos &      &      &      &      &      &      &      &      &      &      &\\
            & Extraordinarios &  &  &  & 63.254.096 & 64.334.933 & 7.639.540 & 4.679.140 & 4.682.364 & 66.669.018 & 22.247.743 & 1.790.048 \\
   \hline
\hspace*{3mm}758 & Otros Resultados &      &      &      &      &      &      &      &      &      &      &\\
            & Integrales &  &  &  & 1 &  &  &  &  &  &  &  \\
    \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize Fuente: Balance de Resultados Consolidados por Fondos Administrados de los Fondos Especializados-DNGF. \\
  Elaborado: DAIE.}
  \end{center}
\end{table}

\begin{quotation}
\textbf{Nota:} Los balances del IESS en el período 2010-2020 han sufrido cambios en los códigos de cuentas, creación de cuentas, por lo que presenta variación en las siguientes partidas durante el periodo analizado:

\begin{itemize}
\item La cuenta “Ingresos por Arriendo” con código (753) se crea a partir del año 2015; considerando que desde el 2010 al 2012 es una subcuenta de “Aportes IESS”, y a partir del 2013 al 2014 se reajusta formando parte de la cuenta “Intereses, Tasas y Contribución”.
\end{itemize}
\end{quotation}
\newpage

% ANEXO 5 --------------------------------------------------------
\begin{itemize}
  \item {\textbf{Descripci\'{o}n de la cuenta GASTOS}}
\end{itemize}
\begin{table}[H]
\captionsetup{justification=centering}
  \begin{center} % centering{}
  \label{tab:iess_anex_gastos_ivm}
  {\fontsize{8}{9}\selectfont
  \begin{tabular}{lrrrrrrrrrrrr} %r right
    \toprule
    Cod.    & Descripción     & 2010 & 2011 & 2012 & 2013 & 2014 & 2015 & 2016 & 2017 & 2018 & 2019 & 2020\\
    cuentas & de las cuentas  &      &      &      &      &      &      &      &      &      &      &      \\
    \midrule
74 & GASTOS & 1.333.417.626 & 1.517.216.905 & 1.761.086.757 & 2.133.868.998 & 2.549.291.771 & 2.987.563.619 & 3.352.146.917 & 3.741.302.395 & 4.011.494.675 & 4.331.034.176 & 4.684.689.136 \\
   \hline
\hspace*{3mm}741 & Gastos Operacionales &      &      &      &      &      &      &      &      &      &      &\\
            & Directos & 1.268.297.308 & 1.444.026.382 & 1.687.028.775 & 2.133.355.766 & 2.548.782.939 & 2.890.478.565 & 3.296.544.153 & 3.670.118.378 & 3.928.646.589 & 4.221.014.327 & 4.549.572.064 \\
   \hline
\hspace*{3mm}7425 & P\'{e}rdida Venta &      &      &      &      &      &      &      &      &      &      &\\
            & Activos & 29.040 & 273 &  &  &  &  &  &  &  &  &  \\
   \hline
\hspace*{3mm}7430 & Gastos Operaci\'{o}n &      &      &      &      &      &      &      &      &      &      &\\
            &  y Ser. Varios & 63.303.039 & 67.714.170 & 73.400.224 &  &  &  &  &  &  &  &  \\
   \hline
\hspace*{3mm}7450 & Gastos Ejercicios &      &      &      &      &      &      &      &      &      &      &\\
            &  Anteriores & 720.513 & 4.556.071 & 110.883 &  &  &  &  &  &  &  &  \\
   \hline
\hspace*{3mm}7460 & Deprec. Propiedades &      &      &      &      &      &      &      &      &      &      &\\
            & y Eq. Especial. & 995.326 & 920.010 & 546.875 &  &  &  &  &  &  &  &  \\
   \hline
\hspace*{3mm}7465 & Provisiones & 72.400 &  &  &  &  &  &  &  &  &  &  \\
   \hline
\hspace*{3mm}743 & Gastos de  &      &      &      &      &      &      &      &      &      &      &\\
            & Administraci\'{o}n &  &  &  & 513.232 & 508.832 & 97.085.054 & 55.602.764 & 71.184.017 & 82.848.086 & 110.019.848 & 135.117.071 \\
     \bottomrule
  \end{tabular}
  }
  \caption*{ \scriptsize Fuente: Balance de Resultados Consolidados por Fondos Administrados de los Fondos Especializados-DNGF. \\
  Elaborado: DAIE.}
  \end{center}
\end{table}

\begin{quotation}
\textbf{Nota:} Cabe mencionar que en el Estado de Perdida y Ganancias del IESS en, el periodo 2010 al 2020 ha sufrido cambios en los códigos de cuentas, se crean nuevas cuentas, por lo que presenta variación y optimización en las siguientes partidas:

\begin{itemize}
\item Entre el año 2010 al 2012 los Gastos poseían seis cuentas como son “Egresos Prestacionales IESS”,  “Pérdida Venta Activos”, “Gastos Operación y Ser. Varios”, “Gastos Ejercicios Anteriores”, “Deprec. Propiedades y Eq. Especial” y “Provisiones”, lo cual fueron fusionadas a las cuentas “Gastos opcionales directos (741) y a la cuenta “Gastos de Administración (743)”;
\item	A partir del 2013 la cuenta “Egresos Prestacionales IESS” cambia de nombre a “Gastos Operacionales Directos”, y se crea la cuenta “Gastos de Administración (743)” en la que se consolida como una subcuenta las depreciaciones.
\end{itemize}
\end{quotation}
\end{landscape}

% ANEXO 6 -------------------------------------------------------------

\begin{itemize}
  \item {\textbf{Balance General Seguro de Invalidez, Vejez y Muerte}}
\end{itemize}

\begin{table}[H]
\captionsetup{justification=centering}
 \begin{center}
 \label{tab:iess_balance_general}
 \scalebox{0.8}{
 \begin{tabular}{|p{2.5cm}|p{10.0cm}|p{6.25cm}|}
    \toprule
     \multicolumn{3}{c} {\multirow{3}[0]{*}{INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL}}\\ [0.3cm]
     \multicolumn{3}{c} {\multirow{3}[0]{*}{Balance General Seguro de Invalidez, Vejez y Muerte}}\\ [0.3cm]
      \multicolumn{3}{c} {\multirow{3}[0]{*}{AL 31 DE DICIEMBRE DE 2020}}\\ [0.6cm]
    \midrule
    \textbf{71} & \multicolumn{1}{l|}{\textbf{ACTIVOS}} & \multicolumn{1}{c|}{\textbf{\$ 8.345.918.689,91}}\\
    \midrule
    \multicolumn{1}{|c|}{711} & \multicolumn{1}{l|}{Fondos Disponibles} & {\raggedleft \$ 125.696.797,55 \par}\\
    \midrule
    \multicolumn{1}{|c|}{714} & \multicolumn{1}{l|}{Recursos/Administra x El BIESS} & {\raggedleft \$ 5.746.473.714,17 \par}\\
    \midrule
    \multicolumn{1}{|c|}{715} & \multicolumn{1}{l|}{Cuentas Por Cobrar} & {\raggedleft \$ 2.109.729.860,44 \par}\\
    \midrule
    \multicolumn{1}{|c|}{718} & \multicolumn{1}{l|}{Propiedad Y Equipo} & {\raggedleft \$ 338.635.181,58 \par}\\
    \midrule
   \multicolumn{1}{|c|}{719} & \multicolumn{1}{l|}{Otros Activos} & {\raggedleft \$ 25.383.136,17 \par}\\
    \midrule
  \textbf{72} & \multicolumn{1}{l|}{\textbf{PASIVOS}} & \multicolumn{1}{c|}{\textbf{\$ 469.254.676,92}}\\
  \midrule
  \multicolumn{1}{|c|}{721} & \multicolumn{1}{l|}{Pasivos Corrientes} &  {\raggedleft \$ 6.775.848,92 \par}\\
  \midrule
  \multicolumn{1}{|c|}{722} & \multicolumn{1}{l|}{Pasivos No Corrientes} &  {\raggedleft \$ 462.478.828,00 \par} \\
  \midrule
  \textbf{73} & \multicolumn{1}{l|}{\textbf{PATRIMONIO}} & \multicolumn{1}{c|}{\textbf {\$ 7.876.664.012,99}}\\
  \midrule
  \multicolumn{1}{|c|}{731} & \multicolumn{1}{l|}{Fondos Capitalizados} &  {\raggedleft \$ 7.433.608.165,20 \par}\\
  \midrule
  \multicolumn{1}{|c|}{733} & \multicolumn{1}{l|}{Reservas} &  {\raggedleft \$ 199.603.642,35 \par}\\
  \midrule
\multicolumn{2}{|c|} {\textbf{PASIVO + PATRIMONIO}} & \multicolumn{1}{c|}{\textbf{\$ 8.345.918.689,91}}\\
\bottomrule
\end{tabular}
}
\caption*{ \scriptsize Fuente: Balance General Consolidado por Fondos Administrados de los Fondos Especializados-DNGF. \\
  Elaborado: DAIE.}
  \end{center}
  \end{table}

\begin{quotation}
\textbf{Nota:Dentro de las Cuentas por Cobrar se encuentra las siguientes Subcuentas:}  Cuentas por Cobrar (Deuda De Gobierno) / Cuentas Por Cobrar Varias (Arrendatarios - Por Venta De Bienes - Otras Cuentas Por Cobrar) / Provisi\'{o}n Para Cuentas Incobrables.

\textbf{Dentro de los Pasivos Corrientes se encuentran las siguientes Subcuentas:} Proveedores (Proveedores - Cuentas Por Pagar Sistemas Esp, - Beneficiarios Por Pagar, - Pagos en efectivo Retención. Judicial) / Retención en Calidad De Agentes de Retenci\'{o}n (Retenciones Sri) / Otras Cuentas Por Pagar (Valores Recibidos En Garant\'{i}a).

\textbf{Dentro de los Pasivos no Corrientes se encuentra las siguientes subcuentas:} Otros Pasivos (Dep\'{o}sitos no identificados - Diferencias Por Neteos Acreedor - Recuperaciones Biess - Recuperaci\'{o}n Inversiones - Retenciones Judiciales Jubilad. - Organizaciones Gremiales De Jubilados - Cuentas Por Pagar A\~{n}os Anterior - Valores Por Liquidar - Responsabilidad Patronal Beneficiarios - Recuperaci\'{o}n. Pr\'{e}stamos. Hipotecarios. IESS - Obligaciones. Con Beneficiarios - Dep. Deuda Estado x liquidar – Cuentas por Pagar Montes de Piedad - Cooperativas de vivienda – Cuentas por Pagar H\'{e}roes y Hero\'{i}nas - Valores x Liquidar Concesiones - Valores por Liq.40\% Pensi\'{o}n y 13ra Pen
\end{quotation}

% ANEXO 7 ---------------------------------------------------------

\begin{itemize}
  \item {\textbf{Estado de Resultados Seguro de Invalidez, Vejez y Muerte}}
\end{itemize}

\begin{table}[H]
\captionsetup{justification=centering}
 \begin{center}
 \label{tab:iess_estado_resultados}
  \scalebox{0.8}{
 \begin{tabular}{|p{2.5cm}|p{10.0cm}|p{6.25cm}|}
    \toprule
     \multicolumn{3}{c} {\multirow{3}[0]{*}{INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL}}\\ [0.3cm]
     \multicolumn{3}{c} {\multirow{3}[0]{*}{Estado de Resultados Seguro de Invalidez, Vejez y Muerte}}\\ [0.3cm]
      \multicolumn{3}{c} {\multirow{3}[0]{*}{Del 01 de enero de 2020 AL 31 de diciembre de 2020}}\\ [0.6cm]
    \midrule
    \textbf{75} & \multicolumn{1}{l|}{\textbf{INGRESOS}} & \multicolumn{1}{c|}{\textbf{\$ 4.928.141.340,94 }}\\
    \midrule
     \multicolumn{1}{|c|}{751} & \multicolumn{1}{l|}{ Ingresos De La Operaci\'{o}n} & {\raggedleft \$ 4.393.046.590,03 \par}\\
    \midrule
    \multicolumn{1}{|c|}{752} & \multicolumn{1}{l|}{Ingresos Financieros} & {\raggedleft \$ 532.019.019,01 \par}\\
     \midrule
     \multicolumn{1}{|c|}{753} & \multicolumn{1}{l|}{Ingresos Por Arriendo Y Realiz.} & {\raggedleft \$ 1.285.684,17 \par}\\
    \midrule
    \multicolumn{1}{|c|}{757} & \multicolumn{1}{l|}{ Ingresos Extraordinarios} & {\raggedleft \$ 1.790.047,73 \par}\\
    \midrule
    \textbf{74} & \multicolumn{1}{l|}{\textbf{GASTOS}} & \multicolumn{1}{c|}{\textbf{\$  (4.684.689.135,50)}}\\
     \midrule
    \multicolumn{1}{|c|}{741} & \multicolumn{1}{l|}{Gastos Operacionales Directos} & {\raggedleft \$ (4.549.572.064,04)\par}\\
     \midrule
    \multicolumn{1}{|c|}{743} & \multicolumn{1}{l|}{Gastos De Administraci\'{o}n} &  {\raggedleft \$ (135.117.071,46) \par}\\
     \midrule
\multicolumn{2}{|c|} {\textbf{RESULTADO DEL EJERCICIO }} & \multicolumn{1}{c|}{\textbf{\$ 243.452.205,44 }}\\
    \bottomrule
\end{tabular}
}
\caption*{ \scriptsize Fuente: Estados Resultados consolidado del Fondo Administrado del IVM \\
  Elaborado: DAIE.}
  \end{center}
\end{table}

\begin{quotation}
\textbf{Nota: Dentro de la Cuentas Ingresos de la Operaci\'{o}n se encuentra las siguientes Subcuentas:} Ingresos de la Seguridad Social (Aportes De Afiliados Y Patrono - Contribuciones Del Estado.) / Ingresos Complementarios Opera (Intereses – multas).

\textbf{Dentro de la Cuentas Gastos Operaci\'{o}n Directos se encuentra las siguientes Subcuentas:} Gastos Prestacionales Por Pensiones (Pensiones De Invalidez - Pensiones de Vejez y Retiro - Pensiones De Montep\'{i}o) / Gastos Prestacionales Por Subsidios (Auxilio De Funerales Y Ayuda Mortuoria) / Otros Gastos Directos.

\textbf{Dentro de la Cuentas Gastos de Administraci\'{o}n se encuentra las siguientes Subcuentas:} Contribuciones (Contribuci\'{o}n administradora) / Gastos Por Depreciaciones (Depreciaci\'{o}n Bienes Inmuebles) / Otros Gastos Por Deterioro (Gasto Por Deterioro De Propiedad).
\end{quotation}
